DECLARE @@MSG VARCHAR(MAX) = ''

IF (@isedit = 'N') AND EXISTS(SELECT 1 FROM TB_M_PLANT WHERE PLANT_CD = @PLANT_CD)
BEGIN
	SET @@MSG = 'Data with Plant Cd ' + @PLANT_CD + ' Already Exists'
	RAISERROR(@@MSG, 16, 1)
	RETURN;
END

IF(LEN(@PLANT_CD) > 4)
BEGIN
	SET @@MSG = 'Plant Code Should Not Be More Than 4 Character'
	RAISERROR(@@MSG, 16, 1)
	RETURN;
END

IF(LEN(@PLANT_NAME) > 50)
BEGIN
	SET @@MSG = 'Plant Name Should Not Be More Than 50 Character'
	RAISERROR(@@MSG, 16, 1)
	RETURN;
END

IF (@isedit = 'N')
BEGIN
	INSERT INTO TB_M_PLANT (PLANT_CD, PLANT_NAME, CREATED_BY, CREATED_DT)
	VALUES (@PLANT_CD, @PLANT_NAME, @userid, GETDATE())
END ELSE
BEGIN
	UPDATE TB_M_PLANT
		SET PLANT_NAME = @PLANT_NAME,
			CHANGED_BY = @userid,
			CHANGED_DT = GETDATE()
	WHERE PLANT_CD = @PLANT_CD
END