BEGIN TRY
	DELETE FROM TB_T_PR_ITEM WHERE PROCESS_ID = @PROCESS_ID
	DELETE FROM TB_T_PR_SUBITEM WHERE PROCESS_ID = @PROCESS_ID
	DELETE FROM TB_T_LOCK WHERE PROCESS_ID = @PROCESS_ID
	SELECT 'SUCCESS'
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE()
END CATCH
	