DECLARE @@EXISTS INT = 0
DECLARE @@MESSAGE VARCHAR(MAX) = ''

SELECT @@EXISTS = COUNT(1) FROM TB_M_ROUTINE_PR_H WHERE (DIVISION_PIC = @NOREG OR CREATED_BY = @USER_ID) AND ROUTINE_NO = @ROUTINE_NO
IF(@@EXISTS = 0)
BEGIN
	SET @@MESSAGE = 'User ' + @USER_ID + ' Cannot edit this Document. Only creator or division PIC can edit this document'
	RAISERROR(@@MESSAGE, 16, 1)
END

SELECT 'SUCCESS'