select ROUTINE_NO,
	   PR_DESC,
	   PLANT_CD,
	   SLOC_CD,
	   DIVISION_ID,
	   DIVISION_PIC,
	   SCH_TYPE,
	   PR_COORDINATOR,
	   ACTIVE_FLAG,
	   SCH_TYPE,
	   dbo.[fn_date_format](VALID_FROM) AS VALID_FROM,
	   dbo.[fn_date_format](VALID_TO) AS VALID_TO,
	   CASE WHEN SCH_TYPE = 'Y' THEN CAST(CAST(LEFT(SCH_VALUE,LEN(SCH_VALUE)-CHARINDEX('.',SCH_VALUE)) AS INT) AS VARCHAR)
			ELSE ''
	   END AS SCH_MONTH,
	   CASE WHEN (SCH_TYPE = 'M' OR SCH_TYPE = 'W') THEN CAST(SCH_VALUE AS INT)
			WHEN SCH_TYPE = 'Y' THEN CAST(CAST(RIGHT(SCH_VALUE,LEN(SCH_VALUE)-CHARINDEX('.',SCH_VALUE)) AS INT) AS VARCHAR)
			ELSE ''
	   END AS SCH_DAY
from TB_M_ROUTINE_PR_H WHERE ROUTINE_NO = @ROUTINE_NO
