SELECT  
	RPS.SUBITEM_NO,
	RPS.ITEM_NO,
	RPS.MAT_DESC AS SUBITEM_MAT_DESC,
	RPS.SUBITEM_QTY,
	RPS.SUBITEM_UOM,
	RPS.PRICE_PER_UOM,
	RPS.ORI_AMOUNT AS SUBITEM_AMOUNT,
	RPS.WBS_NO AS SUBITEM_WBS_NO,
	RPS.COST_CENTER_CD AS SUBITEM_COST_CENTER,
	RPS.GL_ACCOUNT AS SUBITEM_GL_ACCOUNT
FROM TB_M_ROUTINE_PR_SUBITEM RPS 
	JOIN TB_M_ROUTINE_PR_ITEM RPI ON RPS.ROUTINE_NO = RPI.ROUTINE_NO AND RPS.ITEM_NO = RPI.ITEM_NO AND RPI.ROUTINE_NO = @ROUTINE_NO AND RPI.ITEM_NO = @ROUTINE_ITEM_NO 
ORDER BY RPS.SUBITEM_NO ASC