--DUMMY
Declare @@EXIST INT
SELECT 
	@@EXIST = COUNT(1)
FROM
	TB_R_SYNCH_EMPLOYEE
WHERE
	GETDATE() BETWEEN VALID_FROM AND VALID_TO 
	AND NOREG = @NOREG

IF(@@EXIST > 0)
BEGIN
	SELECT 
		POSITION_LEVEL,
		DIVISION_ID,
		ORG_ID,
		NOREG AS NO_REG
	FROM
		TB_R_SYNCH_EMPLOYEE
	WHERE
		GETDATE() BETWEEN VALID_FROM AND VALID_TO 
		AND NOREG = @NOREG
END
ELSE
BEGIN
	SELECT TOP 1
		POSITION_LEVEL,
		DIVISION_ID,
		ORG_ID,
		NOREG AS NO_REG
	FROM
		TB_R_SYNCH_EMPLOYEE
	WHERE
		GETDATE() BETWEEN VALID_FROM AND VALID_TO 
		AND DIVISION_ID = 14 AND DEPARTMENT_ID = 142 AND SECTION_ID = 153
END