SELECT RPH.PR_DESC,
	   RPH.PR_COORDINATOR + CASE WHEN(ISNULL(MC.COORDINATOR_DESC, '') = '') THEN '' ELSE ' - ' + MC.COORDINATOR_DESC END AS PR_COORDINATOR,
	   RPH.DIVISION_NAME,
	   RPH.DIVISION_PIC,
	   RPH.PLANT_CD,
	   RPH.SLOC_CD,
	   RPH.SCH_TYPE_DESC,
	   RPH.SCH_VALUE,
	   RPH.ACTIVE_FLAG,
	   dbo.[fn_date_format](RPH.VALID_FROM) AS VALID_FROM,
	   dbo.[fn_date_format](RPH.VALID_TO) AS VALID_TO
FROM TB_M_ROUTINE_PR_H RPH 
     LEFT JOIN TB_M_COORDINATOR MC ON RPH.PR_COORDINATOR = MC.COORDINATOR_CD
WHERE RPH.ROUTINE_NO = @ROUTINE_NO