SELECT * FROM 
(
	SELECT DISTINCT ROW_NUMBER() OVER (ORDER BY PERSONNEL_NAME ASC) AS NUMBER, PERSONNEL_NAME, NOREG AS NO_REG 
	FROM TB_R_SYNCH_EMPLOYEE WHERE DIVISION_ID = @DIVISION_ID
	AND ((PERSONNEL_NAME LIKE '%' + ISNULL(@PIC_PARAM, '') + '%'
		AND isnull(@PIC_PARAM, '') <> ''
		OR (isnull(@PIC_PARAM, '') = '')))
)A WHERE A.NUMBER >= @start AND A.NUMBER <= @length