EXEC [dbo].[sp_routineinquiry_getList]  
		@ROUTINE_NO,
		@DESCRIPTION,
		@PR_COORDINATOR,
		@DIVISION_CD, 
		@SCH_TYPE,
		@VALID_DATEFROM, 
		@VALID_DATETO, 
		@VENDOR_CD, 
		@PLANT_CD, 
		@SLOC_CD, 
		@WBS_NO, 
		@CREATED_BY,
		@Start, 
		@Length