-- Created By   : alira.salman
-- Created Date : 20.04.2015
-- Description  : Get Announcement module data (TB_R_ANNOUNCEMENT).

DECLARE @@SQL VARCHAR(1000)

SET @@SQL = N'SELECT TOP 50 [PROCESS_ID],[MSG_TYPE],[TARGET_RECIPIENT],[MSG_CONTENT],[MSG_ATTACHMENT],[CREATED_BY],[CREATED_DT],[CHANGED_BY],[CHANGED_DT]
FROM [dbo].[TB_R_ANNOUNCEMENT] WHERE [TARGET_RECIPIENT] LIKE ''%' + @RegNo + '%'' ORDER BY [CREATED_DT] DESC'

EXEC (@@SQL)