-- Created By   : alira.salman
-- Created Date : 26.03.2015
-- Description  : Get Attachment module data (TB_R_ATTACHMENT).

SELECT 
	RA.DOC_NO,
	RA.DOC_SOURCE,
	RA.SEQ_NO,
	RA.DOC_TYPE,
	RA.FILE_PATH,
	RA.FILE_NAME_ORI,
	CASE WHEN (DOC_SOURCE = 'PO') THEN DATEPART(YEAR, POH.DOC_DT) ELSE DATEPART(YEAR, PRH.DOC_DT) END AS DOC_YEAR
FROM TB_R_ATTACHMENT RA
	LEFT JOIN TB_R_PO_H POH ON RA.DOC_NO = POH.PO_NO
	LEFT JOIN TB_R_PR_H PRH ON RA.DOC_NO = PRH.PR_NO
WHERE RA.DOC_NO = @DOC_NO
ORDER BY RA.SEQ_NO ASC