USE [PAS_DB_QA]
GO
/****** Object:  StoredProcedure [dbo].[sp_BudgetConfig_GetBudgetConfig]    Script Date: 11/8/2017 10:32:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SAP_Synchronous_GetMaterialFtpCredential]
AS
BEGIN
	SELECT
	(SELECT SYSTEM_VALUE + 'MM/TO_SAP/' FROM dbo.TB_M_SYSTEM WHERE FUNCTION_ID = 'FTP' AND SYSTEM_CD = 'URL') + ';' +
    (SELECT SYSTEM_VALUE FROM dbo.TB_M_SYSTEM WHERE FUNCTION_ID = 'FTP' AND SYSTEM_CD = 'UNAME') + ';' +
    (SELECT SYSTEM_VALUE FROM dbo.TB_M_SYSTEM WHERE FUNCTION_ID = 'FTP' AND SYSTEM_CD = 'PASSW') 
END

