EXEC sp_price_validateSave 
		@PRICE_TYPE, 
		@MAT_NO, 
		@MAT_DESC, 
		@VENDOR_CD, 
		@PRODUCTION_PURPOSE, 
		@CURR_CD, 
		@PRICE_AMT, 
		@VALID_DT_FROM,
		@WARP_BUYER_CD,
		@PACKING_TYPE,
		@PART_COLOR_SFX,
		@SOURCE_TYPE,
		@PRICE_STS