ALTER PROCEDURE [dbo].[sp_Home_GetAllNotification]
	@RegNo VARCHAR(30)
AS
BEGIN
	SELECT NOTIFICATION_ID, NOTIFICATION_GRP_ID, TITLE, CONTENT, AUTHOR, CREATED_BY, CREATED_DT, CHANGED_BY, CHANGED_DT, VALID_FROM, VALID_TO
	FROm TB_R_NOTIFICATION
		WHERE RECIPIENT = @RegNo AND  CONVERT(DATE, GETDATE()) BETWEEN VALID_FROM AND VALID_TO 
END