DELETE FROM TB_M_NON_COMPONENT_PART_LIST
WHERE PROC_USAGE_CD = @ProcUsage AND
	  GENTANI_HEADER_TYPE = @HeaderType AND
	  GENTANI_HEADER_CD = @HeaderCd AND
	  MAT_NO = @MatNo AND
	  VALID_DT_FR = @ValidDt	