DECLARE @@SQL VARCHAR(MAX)

SET @@SQL = 'SELECT * FROM
(
SELECT ROW_NUMBER() OVER (ORDER BY CREATED_DT DESC, CHANGED_DT DESC) AS Number,
	DIVISION_ID AS DIVISION_ID,
	DIVISION_NAME AS DIVISION_NAME,
	WBS_NO,	
	QUOTA_TYPE AS QUOTA_TYPE,
	TYPE_DESCRIPTION AS TYPE_DESCRIPTION,
	ORDER_COORD AS ORDER_COORD,
	ORDER_COORD_NAME AS ORDER_COORD_NAME,
	QUOTA_AMOUNT,
	QUOTA_AMOUNT_TOL,	
	CREATED_BY AS CREATED_BY,
	dbo.fn_date_format(CREATED_DT) AS CREATED_DT,
	CHANGED_BY AS CHANGED_BY,
	dbo.fn_date_format(CHANGED_DT) AS CHANGED_DT
	FROM TB_M_QUOTA
	WHERE 1=1 
'
IF (ISNULL(@DIVISION_ID, '') <> '')
	SET @@SQL = @@SQL + ' AND DIVISION_ID = ''' + @DIVISION_ID + ''''

IF (ISNULL(@WBS_NO, '') <> '')
	SET @@SQL = @@SQL + ' AND WBS_NO LIKE ''%' + @WBS_NO + '%'''

IF (ISNULL(@TYPE, '') <> '')
	SET @@SQL = @@SQL + ' AND QUOTA_TYPE = ''' + @TYPE + ''''

IF (ISNULL(@ORD_COORD, '') <> '')
	SET @@SQL = @@SQL + ' AND ORDER_COORD = ''' + @ORD_COORD + ''''
	
SET @@SQL = @@SQL + '
GROUP BY
	DIVISION_ID ,
	DIVISION_NAME,	
	WBS_NO,
	QUOTA_TYPE ,
	TYPE_DESCRIPTION ,
	ORDER_COORD ,
	ORDER_COORD_NAME,
	QUOTA_AMOUNT,
	QUOTA_AMOUNT_TOL,	
	CREATED_BY,
	CREATED_DT,
	CHANGED_BY,
	CHANGED_DT
) TB' 
EXEC (@@SQL)