DECLARE @@TOL DECIMAL(18,2),@@USG DECIMAL(18,2)

SET @@TOL = (SELECT isnull(QUOTA_AMOUNT_TOL,0) FROM TB_M_QUOTA WHERE DIVISION_ID = @DivisionID AND QUOTA_TYPE = @QuotaType)
SET @@USG = (SELECT isnull(SUM(AMOUNT),0)
             FROM TB_R_QUOTA_CONSUME 
             WHERE DOC_NO = '-' AND 
                   --QUOTA_MONTH = left(REPLACE(CAST(GETDATE() AS DATE), '-', ''),6) AND
				   QUOTA_MONTH = @ConsumeMonth AND
				   TRANS_STATUS = 'R' AND
				   QUOTA_TYPE = @QuotaType AND 
				   DIVISION_ID = @DivisionID
		     )

select CONSUME_MONTH,DIVISION_ID,DIVISION_NAME,WBS_NO,QUOTA_TYPE as TYPE,TYPE_DESCRIPTION, ORDER_COORD as ORDER_COORD2,
       ORDER_COORD_NAME,QUOTA_AMOUNT,ADDITIONAL_AMOUNT,USAGE_AMOUNT,
	   QUOTA_AMOUNT + ADDITIONAL_AMOUNT - USAGE_AMOUNT AS REMAINING,
	   @@TOL - @@USG AS TOLERANCE 
from TB_R_QUOTA 
where CONSUME_MONTH = @ConsumeMonth and DIVISION_ID = @DivisionID and QUOTA_TYPE = @QuotaType