WITH getData AS
		(
		SELECT ROW_NUMBER() OVER(ORDER BY CREATED_DT) AS Number,
		        CONSUME_MONTH,			 
			    DIVISION_ID,
				DIVISION_NAME,
				WBS_NO,
				QUOTA_TYPE AS TYPE,	
				TYPE_DESCRIPTION,
				ORDER_COORD AS ORDER_COORD2,
				ORDER_COORD_NAME AS ORDER_COORD_NAME,
				QUOTA_AMOUNT,
				ADDITIONAL_AMOUNT,
				isnull(UNCONFIRM_AMOUNT,0) as UNCONFIRM_AMOUNT,
				USAGE_AMOUNT,	
				QUOTA_AMOUNT + ADDITIONAL_AMOUNT - USAGE_AMOUNT AS REMAINING
		FROM TB_R_QUOTA	 
		WHERE CONSUME_MONTH LIKE cast(year(getdate()) as varchar(4)) + '%' AND
              CONSUME_MONTH LIKE + '%' + cast(MONTH(getdate()) as varchar(2)) 
		      AND ((DIVISION_ID = @DIVISION_ID) OR (@DIVISION_ID = '0'))
	          AND (QUOTA_TYPE like '%' + @TYPE + '%' OR TYPE_DESCRIPTION like '%' + @TYPE + '%' )
			  AND (ORDER_COORD like '%' + @ORD_COORD + '%' OR ORDER_COORD_NAME like '%' + @ORD_COORD + '%' )
			  AND (WBS_NO like '%' + @WBS_NO + '%')			 	
		)
SELECT *
FROM getData
WHERE NUMBER >= @Start AND NUMBER <= @End
