-- Created By   : alira.salman
-- Created Date : 02.03.2015
-- Description  : Get PRApproval module history data (TB_R_WORKFLOW).

DECLARE 
	@@@MAX_RECORD AS BIGINT

SELECT @@@MAX_RECORD = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'MAX_SEARCH';
SELECT @@@MAX_RECORD = MIN(ROWMIN) FROM (VALUES (@@@MAX_RECORD), (@PAGE_INDEX * @PAGE_SIZE)) B(ROWMIN);

SELECT TOP (@@@MAX_RECORD) ROW_NUMBER() OVER (ORDER BY PRAPPROVALHISTORY_UNORDERED.DOCUMENT_SEQ DESC) AS 'NUMBER', PRAPPROVALHISTORY_UNORDERED.*
FROM
(
	SELECT TOP (@@@MAX_RECORD)
		W.DOCUMENT_NO AS 'DOCUMENT_NO',
		W.ITEM_NO AS 'ITEM_NO',
		W.DOCUMENT_SEQ AS 'DOCUMENT_SEQ',
		@DOC_TYPE AS 'DOCUMENT_TYPE', 
		W.APPROVAL_DESC AS 'APPROVAL_DESC',
		W.APPROVER_NAME AS 'APPROVED_BY',
		W.APPROVED_DT AS 'APPROVED_DT',
		W.STRUCTURE_ID AS 'STRUCTURE_ID',
		W.STRUCTURE_NAME AS 'STRUCTURE_NAME',
		W.APPROVER_POSITION AS 'APPROVER_POSITION'
	FROM TB_R_WORKFLOW W
	WHERE
		W.DOCUMENT_NO = @DOC_NO
		AND W.ITEM_NO = @ITEM_NO
		AND (ISNULL(W.IS_DISPLAY, '') = '' OR W.IS_DISPLAY = 'Y')
) AS PRAPPROVALHISTORY_UNORDERED
;