SELECT ISNULL(MAX(Number), 0) FROM
(
	SELECT ROW_NUMBER() OVER (ORDER BY CURR_CD ASC) AS Number 
	FROM TB_M_EXCHANGE_RATE
	WHERE CURR_CD= @CURR_CD AND CAST(CREATED_DT AS DATE) = CAST(GETDATE() AS DATE)
) AS TB

