IF EXISTS(SELECT 1 FROM TB_M_EXCHANGE_RATE WHERE CURR_CD = @CURR_CD AND VALID_DT_FROM = @VALID_DT_FROM)
BEGIN
	UPDATE TB_M_EXCHANGE_RATE 
	SET VALID_DT_TO = @VALID_DT_TO,
		FOREX_TYPE = @FOREX_TYPE,
		RELEASED_FLAG = CASE WHEN(@RELEASED_FLAG = 'Y') THEN '1' ELSE '0' END,
		CHANGED_BY = @USER_ID,
		CHANGED_DT = GETDATE()
	WHERE CURR_CD = @CURR_CD AND VALID_DT_FROM = @VALID_DT_FROM 
END
ELSE
BEGIN
	UPDATE TB_M_EXCHANGE_RATE 
		SET VALID_DT_TO =  DATEADD(DAY, -1, @VALID_DT_FROM),
			CHANGED_BY = @USER_ID,
			CHANGED_DT = GETDATE()
	WHERE CURR_CD = @CURR_CD AND VALID_DT_TO = '9999-12-31'

	INSERT INTO [dbo].[TB_M_EXCHANGE_RATE]
           ([CURR_CD]
           ,[EXCHANGE_RATE]
           ,[VALID_DT_FROM]
           ,[VALID_DT_TO]
           ,[FOREX_TYPE]
           ,[RELEASED_FLAG]
           ,[CREATED_BY]
           ,[CREATED_DT]
           ,[CHANGED_BY]
           ,[CHANGED_DT]
           ,[DECIMAL_FORMAT])
     VALUES
           (@CURR_CD
           ,CAST(@EXCHANGE_RATE AS DECIMAL(7,2))
           ,@VALID_DT_FROM
           ,@VALID_DT_TO
           ,@FOREX_TYPE
           ,CASE WHEN(@RELEASED_FLAG = 'Y') THEN '1' ELSE '0' END
           ,@USER_ID
           ,GETDATE()
           ,NULL
           ,NULL
           ,@DECIMAL_FORMAT)
END

SELECT 'SUCCESS'

IF EXISTS(SELECT 1 FROM [BMS_DEV].[NEW_BMS_DB].[dbo].[TB_M_EXCHANGE_RATE] WHERE CURR_CD = @CURR_CD AND VALID_FROM_DT = @VALID_DT_FROM)
BEGIN
	UPDATE [BMS_DEV].[NEW_BMS_DB].[dbo].[TB_M_EXCHANGE_RATE]
	SET VALID_TO_DT = @VALID_DT_TO,
		CHANGED_BY = @USER_ID,
		CHANGED_DT = GETDATE()
	WHERE CURR_CD = @CURR_CD AND VALID_FROM_DT = @VALID_DT_FROM 
END
ELSE
BEGIN
	UPDATE [BMS_DEV].[NEW_BMS_DB].[dbo].[TB_M_EXCHANGE_RATE]
		SET VALID_TO_DT =  DATEADD(DAY, -1, @VALID_DT_FROM),
			CHANGED_BY = @USER_ID,
			CHANGED_DT = GETDATE()
	WHERE CURR_CD = @CURR_CD AND VALID_TO_DT = '9999-12-31'

	INSERT INTO [BMS_DEV].[NEW_BMS_DB].[dbo].[TB_M_EXCHANGE_RATE]
           ([CURR_CD]
           ,[VALID_FROM_DT]
           ,[VALID_TO_DT]
           ,[EXCHANGE_RATE]
           ,[CREATED_BY]
           ,[CREATED_DT]
           ,[CHANGED_BY]
           ,[CHANGED_DT])
     VALUES
           (@CURR_CD
           ,@VALID_DT_FROM
           ,@VALID_DT_TO
		   ,CAST(@EXCHANGE_RATE AS DECIMAL(7,2))
           ,@USER_ID
           ,GETDATE()
           ,NULL
           ,NULL)
END

SELECT 'SUCCESS'