DECLARE @@VALID INT

SELECT @@VALID = COUNT(1)
	FROM TB_M_EXCHANGE_RATE
	WHERE CURR_CD = @CURR_CD AND VALID_DT_FROM = @VALID_DT_FROM
		  AND @VALID_DT_TO='9999-12-31'

IF(@@VALID = 0)
BEGIN
	SELECT 'Only Last Exchange Rate can be deleted !'
END
ELSE
BEGIN
	SELECT ''
END