DECLARE @@MESSAGE VARCHAR(MAX)

BEGIN TRY
	EXEC sp_ImportPO_SAP @PROCESS_ID
	SET @@MESSAGE = 'SUCCESS'
END TRY
BEGIN CATCH
	SELECT @@MESSAGE = ERROR_MESSAGE()
	RAISERROR(@@MESSAGE, 16, 1)
END CATCH

SELECT @@MESSAGE