
CREATE PROCEDURE [dbo].[sp_PurchasingGroup_GetUserListByCode]
    @purchasingGroup VARCHAR(6)
AS
BEGIN
    SELECT cm.NOREG RegNo, cm.PIC_NAME [Name],
    cm.DIVISION_ID DivisionId, sed.DIVISION_NAME DivisionTitle,
    cm.DEPARTMENT_ID DepartmentId, sedp.DEPARTMENT_NAME DepartmentTitle,
    cm.SECTION_ID SectionId, ses.SECTION_NAME SectionTitle
    FROM TB_M_COORDINATOR_MAPPING cm
    JOIN TB_M_COORDINATOR co ON cm.COORDINATOR_CD = co.COORDINATOR_CD
    JOIN (
        SELECT DIVISION_ID, DIVISION_NAME
        FROM TB_R_SYNCH_EMPLOYEE
        WHERE DIVISION_ID IS NOT NULL
        GROUP BY DIVISION_ID, DIVISION_NAME
    ) sed ON cm.DIVISION_ID = sed.DIVISION_ID
    JOIN (
        SELECT DIVISION_ID, DEPARTMENT_ID, DEPARTMENT_NAME
        FROM TB_R_SYNCH_EMPLOYEE
        WHERE DIVISION_ID IS NOT NULL AND DEPARTMENT_ID IS NOT NULL
        GROUP BY DIVISION_ID, DEPARTMENT_ID, DEPARTMENT_NAME
    ) sedp ON cm.DIVISION_ID = sedp.DIVISION_ID
    AND cm.DEPARTMENT_ID = sedp.DEPARTMENT_ID
    JOIN (
        SELECT DIVISION_ID, DEPARTMENT_ID, SECTION_ID, SECTION_NAME
        FROM TB_R_SYNCH_EMPLOYEE
        WHERE DIVISION_ID IS NOT NULL AND DEPARTMENT_ID IS NOT NULL AND SECTION_ID IS NOT NULL
        GROUP BY DIVISION_ID, DEPARTMENT_ID, SECTION_ID, SECTION_NAME
    ) ses ON cm.DIVISION_ID = ses.DIVISION_ID
    AND cm.DEPARTMENT_ID = ses.DEPARTMENT_ID
    AND cm.SECTION_ID = ses.SECTION_ID
    WHERE cm.COORDINATOR_CD = @purchasingGroup AND co.COOR_FUNCTION = 'PG'
END