CREATE PROCEDURE [dbo].[sp_PurchasingGroup_GetUserMapDivisionList]
AS
BEGIN
    SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY se.DIVISION_NAME ASC) [No],
    se.DIVISION_NAME [Name], pc.DIVISION_ID [Value]
    FROM TB_M_PROCUREMENT_CHANNEL pc
    JOIN (
        SELECT DIVISION_ID, DIVISION_NAME
        FROM TB_R_SYNCH_EMPLOYEE
        WHERE DIVISION_ID IS NOT NULL
        GROUP BY DIVISION_ID, DIVISION_NAME
    ) se ON pc.DIVISION_ID = se.DIVISION_ID
END
