CREATE PROCEDURE [dbo].[sp_PurchasingGroup_GetUserMapSectionList]
    @divisionId VARCHAR(5), @deptId VARCHAR(5)
AS
BEGIN
    SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY se.SECTION_NAME ASC) [No],
    se.SECTION_NAME [Name], se.SECTION_ID [Value]
    FROM TB_M_PROCUREMENT_CHANNEL pc
    JOIN (
        SELECT DIVISION_ID, DEPARTMENT_ID, SECTION_ID, SECTION_NAME
        FROM TB_R_SYNCH_EMPLOYEE
        WHERE DIVISION_ID IS NOT NULL AND DEPARTMENT_ID IS NOT NULL AND SECTION_ID IS NOT NULL
        GROUP BY DIVISION_ID, DEPARTMENT_ID, SECTION_ID, SECTION_NAME
    ) se ON pc.DIVISION_ID = se.DIVISION_ID
    WHERE pc.DIVISION_ID = @divisionId AND se.DEPARTMENT_ID = @deptId
END