DECLARE @@ERROR_MESSAGE VARCHAR(MAX) = '',
		@@EXIST INT

SET NOCOUNT ON;

SELECT @@EXIST = COUNT(*) FROM TB_T_LOCK WHERE PROCESS_ID = @Process_Id AND MODULE_ID = '2' AND FUNCTION_ID = '201002'
IF(@@EXIST < 1)
BEGIN
	SELECT @@ERROR_MESSAGE = MESSAGE_TEXT from TB_M_MESSAGE where MESSAGE_ID = 'ERR00101';
	SET @@ERROR_MESSAGE = REPLACE(@@ERROR_MESSAGE,'xxxxxx',@Process_Id);
END

SELECT 
	CASE WHEN @@ERROR_MESSAGE <> '' THEN 'EXCEPTION' ELSE 'SUCCESS' END AS PROCESS_STATUS, 
	CASE WHEN @@ERROR_MESSAGE <> '' THEN @@ERROR_MESSAGE ELSE '' END AS [MESSAGE]