DECLARE @@SIZE BIGINT
DECLARE @@NAME VARCHAR(MAX)

BEGIN TRY
	SELECT @@SIZE = FILE_SIZE, @@NAME = FILE_NAME_ORI FROM TB_T_ATTACHMENT WHERE PROCESS_ID = @PROCESS_ID AND DOC_NO = @PR_NO AND SEQ_NO = @SEQ_NO
	UPDATE TB_T_ATTACHMENT SET DELETE_FLAG = 'Y' WHERE PROCESS_ID = @PROCESS_ID AND DOC_NO = @PR_NO AND SEQ_NO = @SEQ_NO
	
	SELECT 'SUC' AS PROCESS_STATUS,
		   @@SIZE AS FILE_SIZE,
		   @@NAME AS FILE_NAME_ORI
END TRY
BEGIN CATCH
	SELECT  'ERR' AS PROCESS_STATUS,
			ERROR_MESSAGE() AS MESSAGE_CONTENT
END CATCH