BEGIN TRY
	DELETE FROM TB_T_PR_ITEM WHERE PROCESS_ID = @PROCESS_ID
	DELETE FROM TB_T_PR_SUBITEM WHERE PROCESS_ID = @PROCESS_ID
	DELETE FROM TB_T_ATTACHMENT WHERE PROCESS_ID = @PROCESS_ID AND DOC_NO = @PR_NO
	UPDATE TB_R_PR_H SET PROCESS_ID = NULL WHERE PR_NO = @PR_NO
	UPDATE TB_R_PR_ITEM SET PROCESS_ID = NULL WHERE PR_NO = @PR_NO AND PROCESS_ID = @PROCESS_ID
	DELETE FROM TB_T_LOCK WHERE PROCESS_ID = @PROCESS_ID
	SELECT 'SUCCESS'
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE()
END CATCH
	