UPDATE TB_T_PR_ITEM
	SET DELETE_FLAG = 'Y',
	    NEW_AMOUNT = 0,
		NEW_LOCAL_AMOUNT = 0
	WHERE PROCESS_ID = @PROCESS_ID

UPDATE TB_T_PR_SUBITEM
	SET DELETE_FLAG = 'Y',
	    NEW_AMOUNT = 0,
		NEW_LOCAL_AMOUNT = 0
	WHERE PROCESS_ID = @PROCESS_ID

UPDATE TB_T_PR_SUBITEM
	SET DELETE_FLAG = 'Y',
	    NEW_AMOUNT = 0,
		NEW_LOCAL_AMOUNT = 0
	WHERE PROCESS_ID = @PROCESS_ID
	AND ITEM_NO NOT IN (SELECT ITEM_NO FROM TB_T_PR_ITEM WHERE PROCESS_ID = @PROCESS_ID)