DECLARE @@EXIST INT,
		@@NEW INT,
		@@USED_QTY DECIMAL(7,2)

BEGIN TRY
	SELECT @@EXIST = COUNT(1) FROM TB_T_PR_ITEM WHERE ITEM_NO = @ITEM_NO AND PROCESS_ID = @PROCESS_ID
	SELECT @@NEW = COUNT(1) FROM TB_T_PR_ITEM WHERE ITEM_NO = @ITEM_NO AND PROCESS_ID = @PROCESS_ID AND NEW_FLAG = 'Y'
	IF(@@EXIST = 0 OR @@NEW > 0) --Subitem baru atau level itemnya belum disave
	BEGIN
		UPDATE TB_T_PR_SUBITEM
			SET DELETE_FLAG = 'Y',
			    NEW_AMOUNT = 0,
				NEW_LOCAL_AMOUNT = 0
			WHERE ITEM_NO = @ITEM_NO AND PROCESS_ID = @PROCESS_ID AND SUBITEM_NO = @SUBITEM_NO
	END
	ELSE
	BEGIN --Already saved subitem
		SELECT @@USED_QTY = ISNULL(PRI.USED_QTY, 0) FROM TB_R_PR_ITEM PRI JOIN TB_R_PR_H PRH ON PRH.PROCESS_ID = @PROCESS_ID AND PRH.PR_NO = PRI.PR_NO AND PRI.PR_ITEM_NO = @ITEM_NO
		IF(@@USED_QTY = 0)
		BEGIN
			UPDATE TB_T_PR_SUBITEM
				SET DELETE_FLAG = 'Y',
					NEW_AMOUNT = 0,
					NEW_LOCAL_AMOUNT = 0
				WHERE ITEM_NO = @ITEM_NO AND PROCESS_ID = @PROCESS_ID AND SUBITEM_NO = @SUBITEM_NO
		END
		ELSE
		BEGIN
			RAISERROR('Cannot delete this subitem. Some quantity of this item already used by Purchase Order', 16, 1);
		END
	END
	SELECT ''
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE()
END CATCH