DECLARE @@NEW_FLAG CHAR(1),
		@@USED_QTY DECIMAL(7, 2) = 0

BEGIN TRY
	SELECT @@NEW_FLAG = NEW_FLAG FROM TB_T_PR_ITEM WHERE ITEM_NO = @ITEM_NO AND PROCESS_ID = @PROCESS_ID

	IF(@@NEW_FLAG = 'Y')
	BEGIN
		UPDATE TB_T_PR_ITEM
			SET DELETE_FLAG = 'Y',
				NEW_AMOUNT = 0,
				NEW_LOCAL_AMOUNT = 0
			WHERE ITEM_NO = @ITEM_NO AND PROCESS_ID = @PROCESS_ID

		UPDATE TB_T_PR_SUBITEM
			SET DELETE_FLAG = 'Y',
				NEW_AMOUNT = 0,
				NEW_LOCAL_AMOUNT = 0
			WHERE ITEM_NO = @ITEM_NO AND PROCESS_ID = @PROCESS_ID
	END
	ELSE
	BEGIN
		SELECT @@USED_QTY = ISNULL(PRI.USED_QTY, 0) FROM TB_R_PR_ITEM PRI JOIN TB_R_PR_H PRH ON PRH.PROCESS_ID = @PROCESS_ID AND PRH.PR_NO = PRI.PR_NO AND PRI.PR_ITEM_NO = @ITEM_NO
		IF(@@USED_QTY = 0)
		BEGIN
			UPDATE TB_T_PR_ITEM
				SET DELETE_FLAG = 'Y',
					NEW_AMOUNT = 0,
					NEW_LOCAL_AMOUNT = 0
				WHERE ITEM_NO = @ITEM_NO AND PROCESS_ID = @PROCESS_ID

			UPDATE TB_T_PR_SUBITEM
				SET DELETE_FLAG = 'Y',
					NEW_AMOUNT = 0,
					NEW_LOCAL_AMOUNT = 0
				WHERE ITEM_NO = @ITEM_NO AND PROCESS_ID = @PROCESS_ID
		END
		ELSE
		BEGIN
			RAISERROR('Cannot delete this item. Some quantity of this item already used by Purchase Order', 16, 1);
		END
	END

	SELECT 'SUCCESS'
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE()
END CATCH