DECLARE @@PR_PREFIX VARCHAR(4),
		@@MSG VARCHAR(MAX),
		@@TEMP_LOG LOG_TEMP,
		@@MODULE VARCHAR(10) = '2',
		@@FUNCTION VARCHAR(20) = '201002',
		@@LOCATION VARCHAR(512) = 'Generating New PR Number',
		@@MSG_ID VARCHAR(12),
		@@EXIST INT,
		@@PR_NO VARCHAR(MAX),
		@@PR_TYPE_DESC VARCHAR(50)

SET NOCOUNT ON;

BEGIN TRY
	SET @@MSG = 'Generate New PR Number Started'
	SET @@MSG_ID = 'MSG0000002'
	EXEC dbo.sp_PutLog @@MSG, @USER_ID, @@LOCATION, @PROCESS_ID , @@MSG_ID, 'INF', @@MODULE, @@FUNCTION, 1;
	
	SELECT @@PR_PREFIX = NUMBERING_PREFIX FROM TB_M_PROCUREMENT_TYPE WHERE PROCUREMENT_TYPE = @PR_TYPE

	IF EXISTS(SELECT 1 FROM TB_M_DOC_NUMBERING 
			  WHERE NUMBERING_PREFIX = SUBSTRING(@@PR_PREFIX, 1, 2) AND VARIANT = SUBSTRING(@@PR_PREFIX, 3, 4))
	BEGIN
		
		DECLARE @@STATUS VARCHAR(10) = 'FALSE'

		WHILE(@@STATUS = 'FALSE')
		BEGIN
			DECLARE @@NEW_SEQ INT
			SELECT @@NEW_SEQ = CAST(CURRENT_NUMBER AS INT) + 1 FROM TB_M_DOC_NUMBERING 
			WHERE NUMBERING_PREFIX = SUBSTRING(@@PR_PREFIX, 1, 2) AND VARIANT = SUBSTRING(@@PR_PREFIX, 3, 4)

			SELECT @@PR_NO = NUMBERING_PREFIX + REPLICATE('0', 8-LEN(CAST(@@NEW_SEQ AS VARCHAR(8)))) + CAST(@@NEW_SEQ AS VARCHAR(8)) 
			FROM TB_M_DOC_NUMBERING WHERE NUMBERING_PREFIX = SUBSTRING(@@PR_PREFIX, 1, 2) AND VARIANT = SUBSTRING(@@PR_PREFIX, 3, 4) 

			IF EXISTS
				(SELECT 1 FROM TB_M_DOC_NUMBERING 
				 WHERE NUMBERING_PREFIX = SUBSTRING(@@PR_PREFIX, 1, 2) AND VARIANT = SUBSTRING(@@PR_PREFIX, 3, 4)
					   AND MAXIMUM_RANGE = SUBSTRING(@@PR_NO, 3, LEN(@@PR_NO)))
			BEGIN
				SET @@MSG = 'Doc. Numbering for this prefix already reach maximum range'
				RAISERROR(@@MSG, 16, 1)
			END

			SELECT @@EXIST = COUNT(1) FROM TB_H_DOCUMENT_NUMBER WHERE DOC_NO = @@PR_NO AND PROCESS_ID <> @PROCESS_ID AND USED_STATUS = 'Y'
			IF(@@EXIST = 0)
			BEGIN
				UPDATE TB_M_DOC_NUMBERING SET CURRENT_NUMBER = SUBSTRING(@@PR_NO, 3, LEN(@@PR_NO)) WHERE NUMBERING_PREFIX = SUBSTRING(@@PR_PREFIX, 1, 2) AND VARIANT = SUBSTRING(@@PR_PREFIX, 3, 4)
				SET @@STATUS = 'TRUE'
				INSERT INTO [dbo].[TB_H_DOCUMENT_NUMBER]
					   ([DOC_NO]
					   ,[PROCESS_ID]
					   ,[USED_STATUS]
					   ,[CREATED_BY]
					   ,[CREATED_DT]
					   ,[CHANGED_BY]
					   ,[CHANGED_DT])
				 VALUES
					   (@@PR_NO
					   ,@PROCESS_ID
					   ,'Y'
					   ,@USER_ID
					   ,GETDATE()
					   ,null
					   ,null)
				SET @@STATUS = 'TRUE'
			END
		END
	END
	ELSE
	BEGIN
		SELECT @@PR_TYPE_DESC = PROCUREMENT_DESC FROM TB_M_PROCUREMENT_TYPE WHERE PROCUREMENT_TYPE = @PR_TYPE
		SET @@MSG = 'Prefix for procurement type ' + @@PR_TYPE_DESC + ' not registered yet in doc. numbering master'
		RAISERROR(@@MSG, 16, 1)
	END

	SET @@MSG = 'Success Generate New PR Number ' + @@PR_NO
	SET @@MSG_ID = 'MSG0000003'
	EXEC dbo.sp_PutLog @@MSG, @USER_ID, @@LOCATION, @PROCESS_ID , @@MSG_ID, 'SUC', @@MODULE, @@FUNCTION, 2;
END TRY
BEGIN CATCH
	SET @@MSG = ERROR_MESSAGE()
	SET @@MSG_ID = 'EXCEPTION'
	EXEC dbo.sp_PutLog @@MSG, @USER_ID, @@LOCATION, @PROCESS_ID, @@MSG_ID, 'ERR', @@MODULE, @@FUNCTION, 3;
	SET @@PR_NO = 'FAILED'
END CATCH

SELECT @@PR_NO