SELECT DISTINCT
	  A.[ITEM_NO]
      ,A.[SUBITEM_NO]
      ,A.[MAT_DESC] AS SUBITEM_MAT_DESC
      ,A.[COST_CENTER_CD] AS SUBITEM_COST_CENTER
	  ,C.[COST_CENTER_DESC] AS SUBITEM_COST_CENTER_DESC
      ,A.[WBS_NO] AS SUBITEM_WBS_NO
      ,A.[GL_ACCOUNT] AS SUBITEM_GL_ACCOUNT
	  ,B.[GL_ACCOUNT_DESC] AS SUBITEM_GL_ACCOUNT_DESC
      ,A.[NEW_SUBITEM_QTY] AS SUBITEM_QTY
      ,A.[SUBITEM_UOM]
	  ,D.[CALC_VALUE]
      ,A.[NEW_PRICE_PER_UOM] AS PRICE_PER_UOM
      ,A.[NEW_AMOUNT] AS SUBITEM_AMOUNT
FROM TB_T_PR_SUBITEM A
LEFT JOIN TB_M_GL_ACCOUNT B
	ON A.GL_ACCOUNT = B.GL_ACCOUNT_CD
LEFT JOIN TB_M_COST_CENTER C
	ON A.COST_CENTER_CD = C.COST_CENTER_CD
LEFT JOIN TB_M_UNIT_OF_MEASURE D
	ON A.SUBITEM_UOM = D.UNIT_OF_MEASURE_CD
WHERE A.PROCESS_ID = @PROCESS_ID AND A.ITEM_NO = @ITEM_NO AND ISNULL(DELETE_FLAG, 'N') <> 'Y'
ORDER BY A.SUBITEM_NO