DECLARE @@MULTIPLY INT

IF EXISTS(SELECT 1 FROM TB_M_DOC_NUMBERING DN JOIN TB_M_PROCUREMENT_TYPE PT 
		  ON PT.PROCUREMENT_TYPE = @PR_TYPE AND DN.NUMBERING_PREFIX = SUBSTRING(PT.NUMBERING_PREFIX, 1, 2) AND DN.VARIANT = SUBSTRING(PT.NUMBERING_PREFIX, 3, 4))
BEGIN
	SELECT @@MULTIPLY = DN.MULTIPLY FROM TB_M_DOC_NUMBERING DN JOIN TB_M_PROCUREMENT_TYPE PT 
	ON PT.PROCUREMENT_TYPE = @PR_TYPE AND DN.NUMBERING_PREFIX = SUBSTRING(PT.NUMBERING_PREFIX, 1, 2) AND DN.VARIANT = SUBSTRING(PT.NUMBERING_PREFIX, 3, 4)

	SELECT TOP 1 REPLICATE('0', 5-LEN(CAST((ISNULL(MAX(CAST(ITEM_NO AS INT)),0) + @@MULTIPLY) AS VARCHAR(5)))) + CAST((ISNULL(MAX(CAST(ITEM_NO AS INT)),0) + @@MULTIPLY) AS VARCHAR(5)) AS SEQNO 
	FROM TB_T_PR_ITEM WHERE PROCESS_ID = @PROCESS_ID
END
ELSE
BEGIN
	RAISERROR('Prefix for this procurement type not registered yet in doc numbering master', 16, 1)
END