SELECT DISTINCT TOP 1
	PR_TYPE as PR_TYPE,
	ISNULL(PR_DESC,'') as PR_DESC,
	PR_COORDINATOR,
	ISNULL(PLANT_CD,'') as PLANT_CD,
	ISNULL(SLOC_CD,'') as SLOC_CD,
	ISNULL(DIVISION_ID,'') as DIVISION_ID,
	URGENT_DOC,
	[dbo].[fn_date_format](DELIVERY_PLAN_DT) as DELIVERY_DATE,
	ISNULL(PROJECT_NO,'') as PROJECT_NO,
	ISNULL(EQUIP_NO,'') as MAIN_ASSET_NO,
	ISNULL(PR_NOTES,'') as PR_NOTES,
	PR_STATUS
FROM TB_T_PR_H
WHERE PROCESS_ID = @PROCESS_ID