DECLARE @@SEQ_NO_EXIST INT,
		@@ITEM_EXIST INT,
		@@CALC_VALUE DECIMAL(7,4),
		@@EXIST_SUBITEM INT,
		@@WBS_EXIST_SUBITEM VARCHAR(30),
		@@MESSAGE VARCHAR(MAX) = ''

BEGIN TRANSACTION
BEGIN TRY
	SELECT @@ITEM_EXIST = COUNT(*) FROM TB_T_PR_ITEM WHERE PROCESS_ID = @PROCESS_ID AND ITEM_NO = @ITEM_NO
	SELECT @@SEQ_NO_EXIST = COUNT(*) FROM TB_T_PR_SUBITEM WHERE PROCESS_ID = @PROCESS_ID AND SUBITEM_NO = @SUBITEM_NO AND ITEM_NO = @ITEM_NO
	SELECT @@CALC_VALUE = CALC_VALUE FROM TB_M_UNIT_OF_MEASURE WHERE UNIT_OF_MEASURE_CD = @SUBITEM_UOM

	SELECT @@EXIST_SUBITEM = COUNT(*) FROM TB_T_PR_SUBITEM WHERE PROCESS_ID = @PROCESS_ID AND ITEM_NO = @ITEM_NO AND SUBITEM_NO != @SUBITEM_NO AND DELETE_FLAG = 'N'
	SELECT TOP 1 @@WBS_EXIST_SUBITEM = WBS_NO FROM TB_T_PR_SUBITEM WHERE PROCESS_ID = @PROCESS_ID AND SUBITEM_NO != @SUBITEM_NO AND ITEM_NO = @ITEM_NO AND DELETE_FLAG = 'N'
	
	IF(@@EXIST_SUBITEM > 0)
	BEGIN
		IF( @WBS_NO != @@WBS_EXIST_SUBITEM )
		BEGIN
			SET @@MESSAGE = 'Sub item for Item Class Service must Choose the same WBS No'
			RAISERROR(@@MESSAGE, 16, 1)
		END
	END


	IF(@@SEQ_NO_EXIST = 0)
	BEGIN
	INSERT INTO [dbo].[TB_T_PR_SUBITEM]
           ([PROCESS_ID]
           ,[ITEM_NO]
           ,[SUBITEM_NO]
           ,[MAT_DESC]
           ,[COST_CENTER_CD]
           ,[WBS_NO]
           ,[GL_ACCOUNT]
           ,[ORI_SUBITEM_QTY]
		   ,[NEW_SUBITEM_QTY]
           ,[SUBITEM_UOM]
		   ,[ORI_PRICE_PER_UOM]
           ,[NEW_PRICE_PER_UOM]
           ,[ORI_AMOUNT]
		   ,[NEW_AMOUNT]
           ,[ORI_LOCAL_AMOUNT]
		   ,[NEW_LOCAL_AMOUNT]
           ,[CREATED_BY]
           ,[CREATED_DT]
           ,[CHANGED_BY]
           ,[CHANGED_DT]
		   ,[NEW_FLAG]
		   ,[UPDATE_FLAG]
		   ,[DELETE_FLAG])
		VALUES (
			@PROCESS_ID,
			@ITEM_NO,
			@SUBITEM_NO,
			@MAT_DESC,
			@COST_CENTER_CD,
			@WBS_NO,
			@GL_ACCOUNT,
			0, --ORI_SUBITEM_QTY
			@SUBITEM_QTY, --NEW_SUBITEM_QTY
			@SUBITEM_UOM, --SUBITEM_UOM
			0, --ORI_PRICE_PER_UOM
			@PRICE_PER_UOM, --NEW_PRICE_PER_UOM
			0, --ORI_AMOUNT
			(@SUBITEM_QTY * @PRICE_PER_UOM * @@CALC_VALUE), --NEW_AMOUNT
			0, --ORI_LOCAL_AMOUNT
			0, --NEW_LOCAL_AMOUNT
			@USERID,
			GETDATE(),
			NULL,
			NULL,
			'Y',
			'N',
			'N'
		)
	END
	ELSE
	BEGIN
		DECLARE @@RATE DECIMAL (9,2) = (SELECT EXCHANGE_RATE FROM TB_T_PR_ITEM WHERE PROCESS_ID = @PROCESS_ID AND ITEM_NO = @ITEM_NO)
		UPDATE TB_T_PR_SUBITEM SET 
				MAT_DESC = @MAT_DESC, 
				COST_CENTER_CD = @COST_CENTER_CD, 
				WBS_NO = @WBS_NO, 
				GL_ACCOUNT = @GL_ACCOUNT,
				NEW_SUBITEM_QTY = @SUBITEM_QTY,
				SUBITEM_UOM = @SUBITEM_UOM, 
				NEW_PRICE_PER_UOM = @PRICE_PER_UOM, 
				NEW_AMOUNT = (@SUBITEM_QTY * @PRICE_PER_UOM),
				NEW_LOCAL_AMOUNT = (@SUBITEM_QTY * @PRICE_PER_UOM ),
				CHANGED_BY = @USERID, 
				CHANGED_DT = GETDATE(),
				UPDATE_FLAG = 'Y'
			WHERE PROCESS_ID = @PROCESS_ID AND SUBITEM_NO = @SUBITEM_NO AND ITEM_NO = @ITEM_NO


	END

	IF(@@ITEM_EXIST > 0)
	BEGIN
		DECLARE @@ITEM_AMOUNT DECIMAL(18, 2)
		
		SELECT @@ITEM_AMOUNT = SUM(ISNULL(NEW_AMOUNT, 0)) FROM TB_T_PR_SUBITEM WHERE PROCESS_ID = @PROCESS_ID AND ITEM_NO = @ITEM_NO

		UPDATE TB_T_PR_ITEM
			SET NEW_AMOUNT = @@ITEM_AMOUNT
			WHERE PROCESS_ID = @PROCESS_ID AND ITEM_NO = @ITEM_NO
	END

	UPDATE TB_T_PR_ITEM 
		SET IS_PARENT = 'Y'
		WHERE ITEM_NO = @ITEM_NO
	
	COMMIT TRANSACTION
	SELECT 'SUCCESS'
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	SELECT ERROR_MESSAGE()
END CATCH