SELECT PRI.ITEM_NO, 
	   PRS.SUBITEM_NO, 
	   CASE WHEN(ISNULL(PRI.MAT_NO, 'X') = 'X') THEN PRI.MAT_DESC ELSE PRI.MAT_NO + ' - ' + PRI.MAT_DESC END
	   +
	   CASE WHEN(ISNULL(PRS.MAT_DESC, '') <> '') THEN ' - ' + PRS.MAT_DESC ELSE '' END AS MAT_DESC
FROM TB_T_PR_ITEM PRI LEFT JOIN TB_T_PR_SUBITEM PRS
	ON PRI.PROCESS_ID = PRS.PROCESS_ID AND PRI.ITEM_NO = PRS.ITEM_NO 
WHERE PRI.PROCESS_ID = @PROCESS_ID AND ISNULL(PRI.DELETE_FLAG, 'N') <> 'Y' AND ISNULL(PRS.DELETE_FLAG, 'N') <> 'Y' 
ORDER BY PRI.ITEM_NO, PRS.SUBITEM_NO ASC