DECLARE @@PROCESS_ID BIGINT = 0,
		@@PR_NO VARCHAR(11) = '0',
		@@MODULE VARCHAR(4) = '2',
		@@FUNCTION VARCHAR(6) = '201002'

--Get locking process id for unsaved PR (not PR Edit)
SELECT TOP 1 @@PROCESS_ID = ISNULL(PROCESS_ID, 0) FROM TB_T_LOCK WHERE [USER_ID] = @USERID 
			AND PROCESS_ID NOT IN (SELECT DISTINCT PROCESS_ID FROM TB_R_PR_H WHERE PROCESS_ID IS NOT NULL) 
			AND FUNCTION_ID = @@FUNCTION AND MODULE_ID = @@MODULE
	ORDER BY CREATED_DT DESC

IF(@@PROCESS_ID = 0)
BEGIN
	--If not found locking process id, get locking processid for saved PR (PR Edit)
	SELECT TOP 1 @@PROCESS_ID = ISNULL(PROCESS_ID, 0) FROM TB_T_LOCK WHERE [USER_ID] = @USERID AND FUNCTION_ID = @@FUNCTION AND MODULE_ID = @@MODULE
	ORDER BY CREATED_DT DESC
END

IF(@@PROCESS_ID <> 0)
BEGIN
	--Update TB_R_PR_H where locked by same user
	UPDATE PRH
		SET PROCESS_ID = NULL
	FROM TB_R_PR_H PRH JOIN TB_T_LOCK TL ON PRH.PROCESS_ID = TL.PROCESS_ID AND TL.[USER_ID] = @USERID AND TL.FUNCTION_ID = @@FUNCTION AND TL.MODULE_ID = @@MODULE
	WHERE PRH.PROCESS_ID IS NOT NULL AND PRH.PROCESS_ID <> @@PROCESS_ID

	--Delete TB_T_LOCK of edited PR that still locked by same user
	DELETE TL
	FROM TB_R_PR_H PRH JOIN TB_T_LOCK TL ON PRH.PROCESS_ID = TL.PROCESS_ID AND TL.[USER_ID] = @USERID AND TL.FUNCTION_ID = @@FUNCTION AND TL.MODULE_ID = @@MODULE
	WHERE PRH.PROCESS_ID IS NOT NULL AND PRH.PROCESS_ID <> @@PROCESS_ID
END

--Update processid TB_R_PR_H if processid not registered in TB_T_LOCK
UPDATE TB_R_PR_H
	SET PROCESS_ID = NULL
WHERE PROCESS_ID IS NOT NULL AND PROCESS_ID NOT IN (SELECT PROCESS_ID FROM TB_T_LOCK)

IF(@@PROCESS_ID <> 0)
BEGIN
	SELECT @@PR_NO = ISNULL(PR_NO, '0') FROM TB_R_PR_H WHERE PROCESS_ID = @@PROCESS_ID
END

SELECT @@PROCESS_ID AS PROCESS_ID, @@PR_NO AS PR_NO