CREATE PROCEDURE [dbo].[sp_Material_UpdateMaterial]
		@Kelas char (1),
		@MAT_NO VARCHAR (23),
		@MAT_DESC VARCHAR (50),
		@UOM VARCHAR (4),
		@CAR_FAMILY_CD VARCHAR (4),
		@MAT_TYPE_CD VARCHAR(4),
		@MAT_GRP_CD VARCHAR(9) ,
		@MRP_TYPE VARCHAR (2),
		@RE_ORDER_VALUE DECIMAL,
		@RE_ORDER_METHOD VARCHAR (2),
		@STD_DELIVERY_TIME INT,
		@AVG_DAILY_CONSUMPTION DECIMAL,
		@MIN_STOCK DECIMAL,
		@MAX_STOCK DECIMAL,
		@PCS_PER_KANBAN DECIMAL,
		@MRP_FLAG CHAR (1),
		@VALUATION_CLASS VARCHAR (4),
		@STOCK_FLAG CHAR (1),
		@ASSET_FLAG CHAR (1),
		@QUOTA_FLAG CHAR (1),
		@CONSIGNMENT_CD VARCHAR (1),
		@PROC_USAGE_CD VARCHAR (5),
		@MATL_GROUP VARCHAR(20),
		@DELETION_FLAG CHAR (1),
		@UserId VARCHAR(20)
AS
BEGIN
DECLARE
		@ProcessId BIGINT,
		@Message VARCHAR (MAX),
		@StatusEdit VARCHAR(1),
		@StatusSukses VARCHAR(10)

SET @StatusSukses = 'SUCCESS'

BEGIN TRY
--EXEC dbo.sp_PutLog 'Update Material Started', @UserId, 'Update Material', @ProcessId output, 'MSG', 'INF', '000', '0000',0;
	--IF(@StatusEdit = '1') --INSERT NEW PR_H
	IF(@Kelas = 'P')
	BEGIN
	--EXEC dbo.sp_PutLog 'Update Data TB_M_MATERIAL Started', @UserId, 'Update Material', @ProcessId , 'MSG', 'INF', '000', '0000',1;
		UPDATE TB_M_MATERIAL_PART SET
			MAT_DESC = @MAT_DESC ,
			ORDER_UOM = @UOM ,
			CAR_FAMILY_CD = @CAR_FAMILY_CD,
			MAT_TYPE_CD = @MAT_TYPE_CD ,
			MAT_GRP_CD = @MAT_GRP_CD ,
			MRP_TYPE = @MRP_TYPE ,
			RE_ORDER_VALUE = @RE_ORDER_VALUE,
			RE_ORDER_METHOD = @RE_ORDER_METHOD ,
			STD_DELIVERY_TIME = @STD_DELIVERY_TIME ,
			AVG_DAILY_CONSUMPTION = @AVG_DAILY_CONSUMPTION ,
			MIN_STOCK = @MIN_STOCK ,
			MAX_STOCK = @MAX_STOCK ,
			PCS_PER_KANBAN = @PCS_PER_KANBAN ,
			MRP_FLAG = @MRP_FLAG ,
			VALUATION_CLASS = @VALUATION_CLASS,
			STOCK_FLAG = @STOCK_FLAG,
			ASSET_FLAG = @ASSET_FLAG,
			QUOTA_FLAG = @QUOTA_FLAG,
			CONSIGNMENT_CD = @CONSIGNMENT_CD,
			PROC_USAGE_GROUP = @PROC_USAGE_CD,
			MATL_GROUP = @MATL_GROUP,
			DELETION_FLAG = @DELETION_FLAG ,
			CHANGED_BY = @UserId,
			CHANGED_DT = GETDATE()
		WHERE MAT_NO = @MAT_NO
		--SET @Message = 'Update Data Material With Material Number : ' + @MAT_NO +' Into TB_M_MATERIAL Success'
		--EXEC dbo.sp_PutLog @Message , @UserId, 'Update Material', @ProcessId , 'MSG', 'INF', '000', '0000',2;
	END
	ELSE
		BEGIN
			UPDATE TB_M_MATERIAL_NONPART SET
			MAT_DESC = @MAT_DESC ,
			ORDER_UOM = @UOM,
			MRP_TYPE = @MRP_TYPE ,
			RE_ORDER_VALUE = @RE_ORDER_VALUE,
			RE_ORDER_METHOD = @RE_ORDER_METHOD ,
			STD_DELIVERY_TIME = @STD_DELIVERY_TIME ,
			AVG_DAILY_CONSUMPTION = @AVG_DAILY_CONSUMPTION ,
			MIN_STOCK = @MIN_STOCK ,
			MAX_STOCK = @MAX_STOCK ,
			PCS_PER_KANBAN = @PCS_PER_KANBAN ,
			MRP_FLAG = @MRP_FLAG ,
			VALUATION_CLASS = @VALUATION_CLASS,
			STOCK_FLAG = @STOCK_FLAG,
			ASSET_FLAG = @ASSET_FLAG,
			QUOTA_FLAG = @QUOTA_FLAG,
			CONSIGNMENT_CD = @CONSIGNMENT_CD,
			PROC_USAGE_GROUP = @PROC_USAGE_CD,
			MATL_GROUP = @MATL_GROUP,
			DELETION_FLAG = @DELETION_FLAG ,
			CHANGED_BY = @UserId,
			CHANGED_DT = GETDATE()
		WHERE MAT_NO = @MAT_NO
		END
	SET @StatusSukses = 'SUCCESS'
END TRY
BEGIN CATCH
	--ROLLBACK TRAN
	--SELECT @Message = 'Update Data Into TB_M_MATERIAL FAILED : ' + ERROR_MESSAGE()
	--EXEC dbo.sp_PutLog @Message, @UserId, 'Update Material', @ProcessId , 'MSG', 'ERR', '000', '0000',3;
	SET @StatusSukses = 'FAILED'
END CATCH
SELECT @StatusSukses
END