SELECT 
	VENDOR_CD AS VENDOR_CD,
	VENDOR_NAME AS VENDOR_NAME,
	VENDOR_PLANT AS VENDOR_PLANT,
	SAP_VENDOR_ID AS SAP_VENDOR_ID,
	PAYMENT_METHOD_CD AS PAYMENT_METHOD_CD,
	PAYMENT_TERM_CD AS PAYMENT_TERM_CD,
	DELETION_FLAG AS DELETION_FLAG
FROM TB_M_VENDOR
WHERE VENDOR_CD = @Criteria