INSERT INTO TB_M_VENDOR
	([VENDOR_CD]
    ,[VENDOR_NAME]
    ,[VENDOR_PLANT]
    ,[SAP_VENDOR_ID]
    ,[PAYMENT_METHOD_CD]
    ,[PAYMENT_TERM_CD]
    ,[DELETION_FLAG]
    ,[CREATED_BY]
    ,[CREATED_DT]
    ,[CHANGED_BY]
    ,[CHANGED_DT])
VALUES (
	@VENDOR_CD,
	@VENDOR_NAME,
	@VENDOR_PLANT,
	@SAP_VENDOR_ID,
	@PAYMENT_METHOD_CD,
	@PAYMENT_TERM_CD,
	'0',
	'System',
	GETDATE(),
	null,
	null
)