DECLARE @@SQL VARCHAR(MAX)

SET @@SQL = 'SELECT * FROM
(
	SELECT ROW_NUMBER() OVER (ORDER BY VENDOR_CD ASC) AS Number,
		  VENDOR_CD AS VENDOR_CD
		  ,VENDOR_NAME AS VENDOR_NAME
		  ,VENDOR_PLANT AS VENDOR_PLANT
		  ,SAP_VENDOR_ID AS SAP_VENDOR_ID
		  ,PAYMENT_METHOD_CD AS PAYMENT_METHOD_CD
		  ,PAYMENT_TERM_CD AS PAYMENT_TERM_CD
		  ,DELETION_FLAG AS DELETION_FLAG
		  ,CREATED_BY AS CREATED_BY
		  ,CREATED_DT AS CREATED_DT
		  ,CHANGED_BY AS CHANGED_BY
		  ,CHANGED_DT AS CHANGED_DT

	FROM TB_M_VENDOR
	WHERE 1=1
	'

	IF (ISNULL(@VENDOR_CD, '') <> '')
		SET @@SQL = @@SQL + ' AND VENDOR_CD = ''' + @VENDOR_CD + ''''

	IF (ISNULL(@VENDOR_NAME, '') <> '')
		SET @@SQL = @@SQL + ' AND VENDOR_NAME LIKE ''%' + @VENDOR_NAME + '%'''

	IF (ISNULL(@VENDOR_PLANT, '') <> '')
		SET @@SQL = @@SQL + ' AND VENDOR_PLANT LIKE ''%' + @VENDOR_PLANT + '%'''
	
	IF (ISNULL(@SAP_VENDOR_ID, '') <> '')
		SET @@SQL = @@SQL + ' AND SAP_VENDOR_ID LIKE ''%' + @SAP_VENDOR_ID + '%'''
	
	IF (ISNULL(@PAYMENT_METHOD_CD, '') <> '')
		SET @@SQL = @@SQL + ' AND PAYMENT_METHOD_CD LIKE ''%' + @PAYMENT_METHOD_CD + '%'''
	
	IF (ISNULL(@PAYMENT_TERM_CD, '') <> '')
		SET @@SQL = @@SQL + ' AND PAYMENT_TERM_CD LIKE ''%' + @PAYMENT_TERM_CD + '%'''
	
	IF (ISNULL(@DELETION_FLAG, '') <> '')
		SET @@SQL = @@SQL + ' AND DELETION_FLAG = ''' + @DELETION_FLAG + ''''
		
	SET @@SQL = @@SQL + ' ) TB WHERE Number BETWEEN ' + CAST(@Start AS VARCHAR) + ' AND ' + CAST(@End AS VARCHAR)

EXEC (@@SQL)