CREATE PROCEDURE [dbo].[sp_Country_GetList]
AS
BEGIN
    SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTRY_NAME) DataNo,
    COUNTRY_ID CountryCode,
    COUNTRY_NAME CountryName
    FROM TB_M_COUNTRY
    ORDER BY COUNTRY_NAME
END