
/****** Object:  UserDefinedFunction [dbo].[GetNextDocNumbering]    Script Date: 7/6/2017 8:54:00 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER FUNCTION [dbo].[GetFixedBudgetReff](@PROCESS_ID bigint, @PR_NO VARCHAR(10), @TBT_PR_ITEMNO VARCHAR(5), @TBT_ORI_CURR_CD VARCHAR(3), @TBT_CURRENT_BUDGET_REF VARCHAR(10))
    RETURNS NVARCHAR (MAX)
AS
BEGIN
	DECLARE @@RESULT VARCHAR(10)
    DECLARE
        @@LAST_BUDGET_REF VARCHAR(10)= (SELECT TOP 1 A.BUDGET_REF FROM TB_R_PR_ITEM A 
					INNER JOIN TB_T_PR_ITEM B ON A.PR_ITEM_NO = B.ITEM_NO 
					INNER JOIN TB_R_PR_H C ON
						A.PR_NO = C.PR_NO AND 
						C.PROCESS_ID = B.PROCESS_ID AND
						B.PROCESS_ID = @PROCESS_ID ORDER BY A.BUDGET_REF DESC)

	SET @@LAST_BUDGET_REF = ISNULL(@@LAST_BUDGET_REF,@TBT_CURRENT_BUDGET_REF)

    SELECT @@RESULT = CASE WHEN ISNULL((SELECT TOP 1 PRI.ORI_CURR_CD FROM TB_R_PR_ITEM PRI WHERE PRI.PR_NO = @PR_NO AND PRI.PR_ITEM_NO = @TBT_PR_ITEMNO),@TBT_ORI_CURR_CD) <> @TBT_ORI_CURR_CD AND NOT EXISTS(SELECT 1 FROM TB_R_PR_ITEM WHERE PR_NO = @PR_NO AND ORI_CURR_CD = @TBT_ORI_CURR_CD)
								THEN (SELECT 
									CASE 
										WHEN CAST(@@LAST_BUDGET_REF AS INT)+1 > 99 THEN CAST(CAST(@@LAST_BUDGET_REF AS INT)+1 AS VARCHAR)
										WHEN CAST(@@LAST_BUDGET_REF AS INT)+1 <= 99 AND CAST(@@LAST_BUDGET_REF AS INT)+1 > 9 THEN '0' + CAST(CAST(@@LAST_BUDGET_REF AS INT)+1 AS VARCHAR)
										WHEN CAST(@@LAST_BUDGET_REF AS INT)+1 <= 9 THEN '00' + CAST(CAST(@@LAST_BUDGET_REF AS INT)+1 AS VARCHAR)
									END)
								ELSE  
									CASE WHEN EXISTS(SELECT 1 FROM TB_R_PR_ITEM WHERE PR_NO = @PR_NO AND ORI_CURR_CD = @TBT_ORI_CURR_CD)
										THEN (SELECT TOP 1 BUDGET_REF FROM TB_R_PR_ITEM WHERE PR_NO = @PR_NO AND ORI_CURR_CD = @TBT_ORI_CURR_CD) 
									ELSE @TBT_CURRENT_BUDGET_REF END
								END
    RETURN @@RESULT
END

GO


