select DISTINCT B.REG_NO AS NOTICE_TO_USER, CONCAT(B.[FIRST_NAME], ' ' ,B.[LAST_NAME]) AS NOTICE_TO_ALIAS
from TB_M_USER_APPLICATION U
INNER JOIN TB_M_APPLICATION A ON(U.[APPLICATION] = A.[ID])
INNER JOIN TB_M_USER B ON(U.[USERNAME] = B.[USERNAME])
INNER JOIN TB_M_ROLE C ON(A.[ID] = C.[APPLICATION])
WHERE A.[ID] = 'GPS'  AND B.[COMPANY] IN ('807B', '807D', '1000')
ORDER BY NOTICE_TO_ALIAS ASC