CREATE PROCEDURE [dbo].[sp_Util_ViewSchema]
    @tableOrViewName VARCHAR(100)
AS
BEGIN
    SELECT TABLE_NAME, COLUMN_NAME, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE
    FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME LIKE '%' + @tableOrViewName + '%'
    ORDER BY ORDINAL_POSITION ASC
END