EXEC [sp_PRApproval_ApproveHeader_HERMAN_07.08.2023] 
@DOC_NO_PARAM, 
@DOC_TYPE_PARAM, 
@VENDOR_CD_PARAM, 
@DIVISION_ID_PARAM, 
@DATE_FROM_PARAM, 
@DATE_TO_PARAM,
@HEADER_MODE_PARAM, 
@DOC_LIST_PARAM,
@DOC_ITEM_LIST_PARAM,
@REG_NO_PARAM, 
@USER_ID_PARAM,
@USER_TYPE_PARAM,
@TYPEAPPROVE_PARAM