EXEC [sp_PRApproval_GetListForAccounting] 
	 @DOC_NO, 
	 @DOC_TYPE, 
	 @DOC_DESC, 
	 @DATE_FROM, 
	 @DATE_TO, 
	 @PR_COORDINATOR, 
	 @PLANT_CD, 
	 @SLOC_CD,  
	 @DIVISION_ID, 
	 @USER_TYPE,
	 @REG_NO, 
	 @ORDER_BY,
	 @PAGE_INDEX, 
	 @PAGE_SIZE