SELECT [PR_NO] AS DOC_NO,[DOC_DT] AS DOC_DT,[PR_DESC] AS DOC_DESC,[PR_STATUS] AS STATUS_CD,
		[PLANT_CD] AS PLANT_CD,[SLOC_CD] AS SLOC_CD,[PR_COORDINATOR] AS PR_COORDINATOR,[DIVISION_ID] AS DIVISION_ID,
		[DIVISION_NAME] AS DIVISION_NAME,[LOCAL_CURR_CD] AS CURR,[LOCAL_AMOUNT] AS AMOUNT, [URGENT_DOC] AS URGENT_DOC,
		[CREATED_BY],[CREATED_DT],[CHANGED_BY],[CHANGED_DT]
  FROM [dbo].[TB_R_PR_H] WHERE PR_NO = @DOC_NO