SELECT DISTINCT
	  A.[PR_SUBITEM_NO] AS SUBITEM_NO
	  ,A.PR_ITEM_NO AS ITEM_NO
      ,A.[MAT_DESC] AS MAT_DESC
      ,A.[COST_CENTER_CD] AS COST_CENTER
	  ,C.[COST_CENTER_DESC] AS CENTER_DESC
      ,A.[WBS_NO] AS WBS_NO
      ,A.[GL_ACCOUNT] AS GL_ACCOUNT
	  ,B.[GL_ACCOUNT_DESC] AS GL_ACCOUNT_DESC
      ,A.[SUBITEM_QTY] AS QTY
      ,A.[SUBITEM_UOM] AS UOM
      ,A.[PRICE_PER_UOM] AS PRICE_PER_UOM
      ,A.[ORI_AMOUNT] AS AMOUNT
FROM TB_R_PR_SUBITEM A
LEFT JOIN TB_M_GL_ACCOUNT B
	ON A.GL_ACCOUNT = B.GL_ACCOUNT_CD
LEFT JOIN TB_M_COST_CENTER C
	ON A.COST_CENTER_CD = C.COST_CENTER_CD
WHERE A.PR_ITEM_NO = @ITEM_NO AND PR_NO = @DOC_NO
ORDER BY A.PR_SUBITEM_NO