DECLARE @@DB_CONNECTION VARCHAR(30),
        @@SQL_QUERY VARCHAR(MAX),
		@@DIV_PARAMETER VARCHAR(10)
		,@@DB_SCHEMA VARCHAR(30)
            
SELECT @@DB_CONNECTION =  SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'BudgetControl'
SELECT @@DB_SCHEMA =  SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'BudgetControlSchema'

SET @@SQL_QUERY = '
		EXEC ' + @@DB_CONNECTION + '.' + @@DB_SCHEMA + '.[dbo].[sp_BudgetControlGetSingleDataWBS] '''+@WBS_NO+'''
	'
EXEC(@@SQL_QUERY)
