SELECT 
	COST_CENTER_CD AS COST_CENTER_CD,
	COST_CENTER_DESC AS COST_CENTER_DESC,
	COST_CENTER_GRP_CD AS COST_CENTER_GRP_CD,
	dbo.fn_date_format(VALID_DT_FROM) AS VALID_DT_FROM,
	dbo.fn_date_format(VALID_DT_TO) AS VALID_DT_TO

FROM TB_M_COST_CENTER
WHERE COST_CENTER_CD = @COST_CENTER_CD