UPDATE TB_M_COST_CENTER
	SET 
		COST_CENTER_CD = @COST_CENTER_CD,
		COST_CENTER_DESC = @COST_CENTER_DESC,
		COST_CENTER_GRP_CD = @COST_CENTER_GRP_CD,
		VALID_DT_FROM = @VALID_DT_FROM,
		VALID_DT_TO = DATEADD(DAY, -1, GETDATE()),
		CHANGED_BY = 'System',
		CHANGED_DT = GETDATE()
WHERE COST_CENTER_CD = @COST_CENTER_CD

