Select  A.PROC_USAGE_CD,
		A.GENTANI_HEADER_TYPE,
		A.MODEL,
		A.DESCRIPTION  
FROM TB_M_GENTANI_TYPE A
WHERE A.PROC_USAGE_CD = @ProcUsage AND
	  A.GENTANI_HEADER_TYPE = @HeaderType AND
	  A.MODEL = @Model 
	 