IF(@Kelas = 'P')
BEGIN
	SELECT COUNT(MAT_NO)
	FROM TB_M_MATERIAL_PART
	WHERE MAT_NO IN (SELECT MAT_NO FROM TB_M_MATERIAL_PART WHERE MAT_NO LIKE @MAT_NO)
END
ELSE
BEGIN
	SELECT COUNT(MAT_NO)
	FROM TB_M_MATERIAL_NONPART
	WHERE MAT_NO IN (SELECT MAT_NO FROM TB_M_MATERIAL_NONPART WHERE MAT_NO LIKE @MAT_NO)
END