-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[sp_price_validateSave] 
	@PRICE_TYPE VARCHAR(10), 
	@MAT_NO VARCHAR(23), 
	@MAT_DESC VARCHAR(70), 
	@VENDOR_CD VARCHAR(6), 
	@PRODUCTION_PURPOSE VARCHAR(5), 
	@CURR_CD VARCHAR(3),
    @PRICE_AMT DECIMAL(18,4), 
	@VALID_DT_FROM VARCHAR(15),
	@WARP_BUYER_CD VARCHAR(15) = 'X',
	@PACKING_TYPE VARCHAR(15) = '0',
	@PART_COLOR_SFX VARCHAR(12) = 'X',
	@SOURCE_TYPE VARCHAR(10) = '1',
	@PRICE_STS VARCHAR(10) = 'F'
AS
BEGIN

DECLARE @STATUS VARCHAR(MAX) = 'SUC|SUC',
		@LATEST_DT_FROM VARCHAR(15),
		@COUNT INT

SELECT @COUNT = COUNT(*) FROM TB_M_MATERIAL_PART WHERE MAT_NO = @MAT_NO
IF(@COUNT <= 0)
BEGIN
	SELECT @COUNT = COUNT(*) FROM TB_M_MATERIAL_NONPART WHERE MAT_NO = @MAT_NO
	IF(@COUNT <= 0)
	BEGIN
		SET @STATUS = 'ERR|Material Number ' + @MAT_NO + ' Doesnt exist in Material Master'
		SELECT @STATUS
		RETURN
	END
END

SELECT @COUNT = COUNT(*) FROM TB_M_SOURCE_LIST 
	WHERE MAT_NO = @MAT_NO AND VENDOR_CD = @VENDOR_CD AND
		  GETDATE() >= VALID_DT_FROM AND GETDATE() <= VALID_DT_TO
					
IF(@COUNT <= 0)
BEGIN
	SET @STATUS = 'ERR|Material Number ' + @MAT_NO + ' And Vendor CD ' + @VENDOR_CD + ' Doesnt exist in Source List Master'
	SELECT @STATUS
	RETURN
END

IF(@PRICE_TYPE = 'Master')
BEGIN
	SELECT @COUNT = COUNT(*) FROM TB_M_MATERIAL_PRICE 
			WHERE MAT_NO = @MAT_NO AND 
				  WARP_BUYER_CD = @WARP_BUYER_CD AND
				  SOURCE_TYPE = @SOURCE_TYPE AND
				  PART_COLOR_SFX = @PART_COLOR_SFX AND
				  PACKING_TYPE = @PACKING_TYPE AND
				  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND 
				  VENDOR_CD = @VENDOR_CD AND
				  VALID_DT_FROM = @VALID_DT_FROM
	IF(@COUNT > 0)
	BEGIN
		SET @STATUS = 'ERR|Data is already exist in Material Master'
		SELECT @STATUS
		RETURN
	END

	SELECT @LATEST_DT_FROM = CONVERT(VARCHAR, MAX(VALID_DT_FROM))
	FROM TB_M_MATERIAL_PRICE 
	WHERE MAT_NO = @MAT_NO AND
			  VENDOR_CD = @VENDOR_CD AND
			  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND
			  WARP_BUYER_CD = @WARP_BUYER_CD AND
			  SOURCE_TYPE = @SOURCE_TYPE AND
			  PART_COLOR_SFX = @PART_COLOR_SFX AND
			  PACKING_TYPE = @PACKING_TYPE

	IF(CONVERT(DATE, @VALID_DT_FROM) < CONVERT(DATE, @LATEST_DT_FROM))
	BEGIN
		SET @STATUS = 'ERR|New Valid Date From (' + dbo.fn_date_format(@VALID_DT_FROM) + ') Cannot under Latest Valid Date From (' + dbo.fn_date_format(@LATEST_DT_FROM) + ')'
		SELECT @STATUS
		RETURN
	END
END
ELSE
BEGIN
	SELECT @COUNT = COUNT(*) FROM TB_M_DRAFT_MATERIAL_PRICE 
			WHERE MAT_NO = @MAT_NO AND 
				  WARP_BUYER_CD = @WARP_BUYER_CD AND
				  SOURCE_TYPE = @SOURCE_TYPE AND
				  PART_COLOR_SFX = @PART_COLOR_SFX AND
				  PACKING_TYPE = @PACKING_TYPE AND
				  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND 
				  VENDOR_CD = @VENDOR_CD AND
				  VALID_DT_FROM = @VALID_DT_FROM
	IF(@COUNT > 0)
	BEGIN
		SET @STATUS = 'ERR|Data is already exist in Material Draft'
		SELECT @STATUS
		RETURN
	END

	SELECT @COUNT = COUNT(*) FROM TB_M_MATERIAL_PRICE 
			WHERE MAT_NO = @MAT_NO AND 
				  WARP_BUYER_CD = @WARP_BUYER_CD AND
				  SOURCE_TYPE = @SOURCE_TYPE AND
				  PART_COLOR_SFX = @PART_COLOR_SFX AND
				  PACKING_TYPE = @PACKING_TYPE AND
				  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND 
				  VENDOR_CD = @VENDOR_CD AND
				  VALID_DT_FROM = @VALID_DT_FROM
	IF(@COUNT > 0)
	BEGIN
		SET @STATUS = 'ERR|Data is already exist in Material Price Master'
		SELECT @STATUS
		RETURN
	END

	SELECT @LATEST_DT_FROM = CONVERT(VARCHAR, MAX(VALID_DT_FROM))
	FROM TB_M_DRAFT_MATERIAL_PRICE 
	WHERE MAT_NO = @MAT_NO AND
			  VENDOR_CD = @VENDOR_CD AND
			  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND
			  WARP_BUYER_CD = @WARP_BUYER_CD AND
			  SOURCE_TYPE = @SOURCE_TYPE AND
			  PART_COLOR_SFX = @PART_COLOR_SFX AND
			  PACKING_TYPE = @PACKING_TYPE

	IF(CONVERT(DATE, @VALID_DT_FROM) < CONVERT(DATE, @LATEST_DT_FROM))
	BEGIN
		SET @STATUS = 'ERR|New Valid Date From (' + dbo.fn_date_format(@VALID_DT_FROM) + ') Cannot under Latest Valid Date From (' + dbo.fn_date_format(@LATEST_DT_FROM) + '/Price Draft)'
		SELECT @STATUS
		RETURN
	END

	SELECT @LATEST_DT_FROM = CONVERT(VARCHAR, MAX(VALID_DT_FROM))
	FROM TB_M_MATERIAL_PRICE 
	WHERE MAT_NO = @MAT_NO AND
			  VENDOR_CD = @VENDOR_CD AND
			  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND
			  WARP_BUYER_CD = @WARP_BUYER_CD AND
			  SOURCE_TYPE = @SOURCE_TYPE AND
			  PART_COLOR_SFX = @PART_COLOR_SFX AND
			  PACKING_TYPE = @PACKING_TYPE

	IF(CONVERT(DATE, @VALID_DT_FROM) < CONVERT(DATE, @LATEST_DT_FROM))
	BEGIN
		SET @STATUS = 'ERR|New Valid Date From (' + dbo.fn_date_format(@VALID_DT_FROM) + ') Cannot under Latest Valid Date From (' + dbo.fn_date_format(@LATEST_DT_FROM) + '/Price Master)'
		SELECT @STATUS
		RETURN
	END
END

SELECT @STATUS
END