ALTER PROCEDURE [dbo].[sp_price_processingSave] 
	@USER_ID VARCHAR(50),
	@PRICE_TYPE VARCHAR(10), 
	@MAT_NO VARCHAR(23), 
	@MAT_DESC VARCHAR(70), 
	@VENDOR_CD VARCHAR(6), 
	@PRODUCTION_PURPOSE VARCHAR(5), 
	@CURR_CD VARCHAR(3),
    @PRICE_AMT DECIMAL(18,4), 
	@VALID_DT_FROM VARCHAR(15),
	@WARP_BUYER_CD VARCHAR(15) = 'X',
	@PACKING_TYPE VARCHAR(15) = '0',
	@PART_COLOR_SFX VARCHAR(12) = 'X',
	@SOURCE_TYPE VARCHAR(10) = '1',
	@PRICE_STS VARCHAR(10) = 'F'
AS
BEGIN

DECLARE @LATEST_DT_FROM VARCHAR(15),
		@STATUS VARCHAR(MAX)

IF(@PRICE_TYPE = 'Master')
BEGIN
	SELECT @LATEST_DT_FROM = CONVERT(VARCHAR, MAX(VALID_DT_FROM))
	FROM TB_M_MATERIAL_PRICE 
	WHERE MAT_NO = @MAT_NO AND
			  VENDOR_CD = @VENDOR_CD AND
			  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND
			  WARP_BUYER_CD = @WARP_BUYER_CD AND
			  SOURCE_TYPE = @SOURCE_TYPE AND
			  PART_COLOR_SFX = @PART_COLOR_SFX AND
			  PACKING_TYPE = @PACKING_TYPE

	BEGIN TRY
		UPDATE TB_M_MATERIAL_PRICE 
		SET VALID_DT_TO = DATEADD(DAY, -1, @VALID_DT_FROM),
			CHANGED_BY = @USER_ID,
			CHANGED_DT = GETDATE()
		WHERE MAT_NO = @MAT_NO AND
				  VENDOR_CD = @VENDOR_CD AND
				  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND
				  VALID_DT_FROM = @LATEST_DT_FROM AND
				  WARP_BUYER_CD = @WARP_BUYER_CD AND
				  SOURCE_TYPE = @SOURCE_TYPE AND
				  PART_COLOR_SFX = @PART_COLOR_SFX AND
				  PACKING_TYPE = @PACKING_TYPE
		SET @STATUS = 'SUCCESS'
	END TRY
	BEGIN CATCH
		SET @STATUS = 'ERR|' + ERROR_MESSAGE()
	END CATCH

	IF(@STATUS = 'SUCCESS')
	BEGIN
		BEGIN TRY
			INSERT INTO TB_M_MATERIAL_PRICE
					(
						MAT_NO,
						VENDOR_CD,
						WARP_BUYER_CD,
						SOURCE_TYPE,
						PRODUCTION_PURPOSE,
						PART_COLOR_SFX,
						PACKING_TYPE,
						VALID_DT_FROM,
						VALID_DT_TO,
						PRICE_STATUS,
						DELETION_FLAG,
						CURR_CD,
						PRICE_AMT,
						CREATED_BY,
						CREATED_DT
					)
			SELECT
					@MAT_NO,
					@VENDOR_CD,
					ISNULL(@WARP_BUYER_CD, 'X'),
					ISNULL(@SOURCE_TYPE, '1'),
					@PRODUCTION_PURPOSE,
					ISNULL(@PART_COLOR_SFX, 'X'),
					ISNULL(@PACKING_TYPE, '0'),
					@VALID_DT_FROM,
					'9999-12-31',
					ISNULL(@PRICE_STS, 'F'),
					'N',
					@CURR_CD,
					@PRICE_AMT,
					@USER_ID,
					GETDATE()
			SET @STATUS = 'SUC|Data Has Been Saved'
		END TRY
		BEGIN CATCH
			UPDATE TB_M_MATERIAL_PRICE 
			SET VALID_DT_TO = '9999-12-31',
				CHANGED_BY = @USER_ID,
				CHANGED_DT = GETDATE()
			WHERE MAT_NO = @MAT_NO AND
					  VENDOR_CD = @VENDOR_CD AND
					  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND
					  VALID_DT_FROM = @LATEST_DT_FROM AND
					  WARP_BUYER_CD = @WARP_BUYER_CD AND
					  SOURCE_TYPE = @SOURCE_TYPE AND
					  PART_COLOR_SFX = @PART_COLOR_SFX AND
					  PACKING_TYPE = @PACKING_TYPE
		
			SET @STATUS = 'ERR|' + ERROR_MESSAGE()
		END CATCH
	END
	SELECT @STATUS
END
ELSE
BEGIN
	SELECT @LATEST_DT_FROM = CONVERT(VARCHAR, MAX(VALID_DT_FROM))
	FROM TB_M_DRAFT_MATERIAL_PRICE 
	WHERE MAT_NO = @MAT_NO AND
			  VENDOR_CD = @VENDOR_CD AND
			  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND
			  WARP_BUYER_CD = @WARP_BUYER_CD AND
			  SOURCE_TYPE = @SOURCE_TYPE AND
			  PART_COLOR_SFX = @PART_COLOR_SFX AND
			  PACKING_TYPE = @PACKING_TYPE

	BEGIN TRY
		UPDATE TB_M_DRAFT_MATERIAL_PRICE 
		SET VALID_DT_TO = DATEADD(DAY, -1, @VALID_DT_FROM),
			CHANGED_BY = @USER_ID,
			CHANGED_DT = GETDATE()
		WHERE MAT_NO = @MAT_NO AND
				  VENDOR_CD = @VENDOR_CD AND
				  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND
				  VALID_DT_FROM = @LATEST_DT_FROM AND
				  WARP_BUYER_CD = @WARP_BUYER_CD AND
				  SOURCE_TYPE = @SOURCE_TYPE AND
				  PART_COLOR_SFX = @PART_COLOR_SFX AND
				  PACKING_TYPE = @PACKING_TYPE
		SET @STATUS = 'SUCCESS'
	END TRY
	BEGIN CATCH
		SET @STATUS = 'ERR|' + ERROR_MESSAGE()
	END CATCH

	IF(@STATUS = 'SUCCESS')
	BEGIN
		BEGIN TRY
			INSERT INTO TB_M_DRAFT_MATERIAL_PRICE
					(
						MAT_NO,
						VENDOR_CD,
						WARP_BUYER_CD,
						SOURCE_TYPE,
						PRODUCTION_PURPOSE,
						PART_COLOR_SFX,
						PACKING_TYPE,
						VALID_DT_FROM,
						VALID_DT_TO,
						PRICE_STATUS,
						DELETION_FLAG,
						CURR_CD,
						PRICE_AMT,
						CPP_FLAG,
						CREATED_BY,
						CREATED_DT
					)
			SELECT
					@MAT_NO,
					@VENDOR_CD,
					@WARP_BUYER_CD,
					@SOURCE_TYPE,
					@PRODUCTION_PURPOSE,
					@PART_COLOR_SFX,
					@PACKING_TYPE,
					@VALID_DT_FROM,
					'9999-12-31',
					@PRICE_STS,
					'N',
					@CURR_CD,
					@PRICE_AMT,
					'X',
					@USER_ID,
					GETDATE()
			SET @STATUS = 'SUC|Data Has Been Saved'
		END TRY
		BEGIN CATCH
			UPDATE TB_M_DRAFT_MATERIAL_PRICE 
			SET VALID_DT_TO = '9999-12-31',
				CHANGED_BY = @USER_ID,
				CHANGED_DT = GETDATE()
			WHERE MAT_NO = @MAT_NO AND
					  VENDOR_CD = @VENDOR_CD AND
					  PRODUCTION_PURPOSE = @PRODUCTION_PURPOSE AND
					  VALID_DT_FROM = @LATEST_DT_FROM AND
					  WARP_BUYER_CD = @WARP_BUYER_CD AND
					  SOURCE_TYPE = @SOURCE_TYPE AND
					  PART_COLOR_SFX = @PART_COLOR_SFX AND
					  PACKING_TYPE = @PACKING_TYPE
		
			SET @STATUS = 'ERR|' + ERROR_MESSAGE()
		END CATCH
	END
	SELECT @STATUS
END
END