CREATE PROCEDURE [dbo].[sp_CostCenter_GetCostCenterList]
    @currentRegNo VARCHAR(50)
AS
BEGIN
    SELECT
    ROW_NUMBER() OVER (ORDER BY COST_CENTER_CD ASC) Number,
    COST_CENTER_CD CostCenterCd,
    COST_CENTER_DESC CostCenterDesc
    FROM TB_M_COST_CENTER
    WHERE DIVISION_ID = (SELECT TOP 1 DIVISION_ID
        FROM TB_R_SYNCH_EMPLOYEE WHERE NOREG = @currentRegNo
        ORDER BY POSITION_LEVEL ASC)
    AND GETDATE() BETWEEN VALID_DT_FROM AND VALID_DT_TO
END