SELECT COUNT(1)
	FROM TB_R_PO_ITEM A 
		JOIN TB_R_PO_CONDITION B ON A.PO_NO = B.PO_NO AND A.PO_ITEM_NO = B.PO_ITEM_NO
		JOIN TB_M_COMP_PRICE C ON B.COMP_PRICE_CD = C.COMP_PRICE_CD
		JOIN TB_M_SYSTEM D ON B.CALCULATION_TYPE = D.SYSTEM_VALUE AND D.FUNCTION_ID = '114001' AND D.SYSTEM_CD LIKE 'CALCULATION_TYPE_%'
		AND A.PO_NO = @DOC_NO