SELECT DISTINCT
	  A.[PO_SUBITEM_NO] AS SUBITEM_NO
	  ,A.PO_ITEM_NO AS ITEM_NO
      ,A.[MAT_DESC] AS MAT_DESC
      ,A.[PO_QTY_ORI] AS QTY
      ,A.[UOM] AS UOM
      ,A.[PRICE_PER_UOM] AS PRICE_PER_UOM
      ,A.[ORI_AMOUNT] AS AMOUNT
      ,CASE WHEN A.WBS_NO = 'X' THEN '' ELSE A.WBS_NO END WBS_NO
      ,CASE WHEN A.COST_CENTER_CD = 'X' THEN '' ELSE A.COST_CENTER_CD END COST_CENTER
      ,CASE WHEN A.GL_ACCOUNT = 'X' THEN '' ELSE A.GL_ACCOUNT END GL_ACCOUNT
FROM TB_R_PO_SUBITEM A
	 JOIN TB_R_PO_ITEM B
	 ON A.PO_NO = B.PO_NO
WHERE A.PO_ITEM_NO = @ITEM_NO AND A.PO_NO = @DOC_NO
ORDER BY A.PO_SUBITEM_NO