SELECT COST_CENTER_GRP_CD AS CostCenterGroupCd,
	   COST_CENTER_GRP_DESC AS CostCenterGroupDesc,
	   DIVISION_CD AS DivisionCd
FROM TB_M_COST_CENTER_GRP 
WHERE COST_CENTER_GRP_CD = @CostGroupCd AND DIVISION_CD = @DivisionCd