INSERT INTO TB_M_COST_CENTER_GRP
	([COST_CENTER_GRP_CD]
    ,[COST_CENTER_GRP_DESC]
    ,[DIVISION_CD]
    ,[CREATED_BY]
    ,[CREATED_DT]
    ,[CHANGED_BY]
    ,[CHANGED_DT])
VALUES
(
	@COST_CENTER_GRP_CD,
	@COST_CENTER_GRP_DESC,
	@DIVISION_CD,
	'System',
	GETDATE(),
	null,
	null
)