DECLARE @@SQL VARCHAR(MAX)

SET @@SQL = 'SELECT * FROM (
	SELECT ROW_NUMBER() OVER (ORDER BY COST_CENTER_GRP_CD ASC) AS Number,
		COST_CENTER_GRP_CD AS COST_CENTER_GRP_CD,
		COST_CENTER_GRP_DESC AS COST_CENTER_GRP_DESC,
		DIVISION_CD AS DIVISION_CD,
		CREATED_BY AS CREATED_BY,
		dbo.fn_date_format(CREATED_DT) AS CREATED_DT,
		CHANGED_BY AS CHANGED_BY,
		dbo.fn_date_format(CHANGED_DT) AS CHANGED_DT

	FROM TB_M_COST_CENTER_GRP
	WHERE 1=1
	'
	IF (ISNULL(@COST_CENTER_GRP_CD, '') <> '')
			SET @@SQL = @@SQL + ' AND COST_CENTER_GRP_CD = ''' + @COST_CENTER_GRP_CD + ''''

	IF (ISNULL(@COST_CENTER_GRP_DESC, '') <> '')
		SET @@SQL = @@SQL + ' AND COST_CENTER_GRP_DESC LIKE ''%' + @COST_CENTER_GRP_DESC + '%'''

	IF (ISNULL(@DIVISION_CD, '') <> '')
		SET @@SQL = @@SQL + ' AND DIVISION_CD = ''' + @DIVISION_CD + ''''
		
	SET @@SQL = @@SQL + ' ) TB WHERE Number BETWEEN ' + CAST(@Start AS VARCHAR) + ' AND ' + CAST(@End AS VARCHAR)

EXEC (@@SQL)