UPDATE TB_M_COST_CENTER_GRP
	SET 
		COST_CENTER_GRP_CD = @COST_CENTER_GRP_CD,
		COST_CENTER_GRP_DESC = @COST_CENTER_GRP_DESC,
		DIVISION_CD = @DIVISION_CD,
		CHANGED_BY = 'System',
		CHANGED_DT = GETDATE()
WHERE COST_CENTER_GRP_CD = @COST_CENTER_GRP_CD