DECLARE @@NEXT_DOC_SEQ INT = 0,
		@@MAX_DOC_SEQ INT = 0,
		@@RELEASE_DOC_SEQ INT = 0

SELECT TOP 1 @@NEXT_DOC_SEQ = DOCUMENT_SEQ 
FROM TB_H_WORKFLOW 
WHERE DOCUMENT_NO = @DOC_NO AND ISNULL(IS_APPROVED, '') = 'N' 
ORDER BY DOCUMENT_SEQ ASC

SELECT @@MAX_DOC_SEQ = MAX(DOCUMENT_SEQ) 
FROM TB_H_WORKFLOW 
WHERE DOCUMENT_NO = @DOC_NO

SELECT TOP 1 @@RELEASE_DOC_SEQ = DOCUMENT_SEQ
FROM TB_H_WORKFLOW
WHERE DOCUMENT_NO = @DOC_NO AND ISNULL(IS_APPROVED, '') = 'Y' AND DOCUMENT_SEQ = @@MAX_DOC_SEQ

SELECT
	COUNT(1)
FROM(
	SELECT
		DENSE_RANK() OVER(ORDER BY DOCUMENT_SEQ DESC) rown,
		DOCUMENT_SEQ,
		ITEM_NO,
		APPROVAL_CD,
		APPROVED_BY,
		APPROVED_DT,
		IS_APPROVED
	FROM TB_H_WORKFLOW 
	WHERE DOCUMENT_NO = @DOC_NO
		  AND ((DOCUMENT_SEQ < @@NEXT_DOC_SEQ AND @@RELEASE_DOC_SEQ = 0) OR ((DOCUMENT_SEQ = @@RELEASE_DOC_SEQ) AND @@RELEASE_DOC_SEQ <> 0))
)TBL WHERE rown = 1