SELECT DISTINCT
	A.PR_NO as PR_NO,
	A.PR_DESC as PR_DESC,
	A.PLANT_CD + ' - ' + ISNULL(E.PLANT_NAME, '') as PLANT_CD,
	A.SLOC_CD + ' - ' + ISNULL(F.SLOC_NAME, '') as SLOC_CD,
	A.DIVISION_ID as DIVISION_ID,
	A.DIVISION_NAME as DIVISION_NAME,
	A.PR_STATUS as STATUS_CD,
	B.STATUS_DESC as STATUS_DESC,
	CASE WHEN A.URGENT_DOC = 'N' THEN 'No' ELSE 'Yes' END AS URGENT_DOC,
	[dbo].[fn_date_format](A.DELIVERY_PLAN_DT) as DELIVERY_DATE,
	A.PROJECT_NO as PROJECT_NO,
	D.PROCUREMENT_DESC as PR_TYPE,
	A.PR_TYPE as PR_TYPE_CD,
	A.PR_NOTES,
	A.PR_COORDINATOR as PR_COORDINATOR,
	C.COORDINATOR_DESC as PR_COORDINATOR_DESC,
	H.DOC_NO
FROM TB_R_PR_H A LEFT JOIN TB_M_STATUS B ON B.STATUS_CD = A.PR_STATUS
				 LEFT JOIN TB_M_COORDINATOR C ON C.COORDINATOR_CD = A.PR_COORDINATOR AND C.COOR_FUNCTION = 'CH'
				 LEFT JOIN TB_M_PROCUREMENT_TYPE D ON D.PROCUREMENT_TYPE = A.PR_TYPE
				 LEFT JOIN TB_M_PLANT E ON A.PLANT_CD = E.PLANT_CD
				 LEFT JOIN TB_M_SLOC F ON A.SLOC_CD = F.SLOC_CD AND F.PLANT_CD = E.PLANT_CD
				 LEFT JOIN TB_R_NOTICE H ON A.PR_NO = H.DOC_NO
WHERE A.PR_NO = @PR_NO