DECLARE @@NEXT_DOC_SEQ INT = 0,
		@@MAX_DOC_SEQ INT = 0,
		@@RELEASE_DOC_SEQ INT = 0

SELECT TOP 1 @@NEXT_DOC_SEQ = DOCUMENT_SEQ 
FROM TB_H_WORKFLOW 
WHERE DOCUMENT_NO = @DOC_NO AND ISNULL(IS_APPROVED, '') = 'N' 
ORDER BY DOCUMENT_SEQ ASC

SELECT @@MAX_DOC_SEQ = MAX(DOCUMENT_SEQ) 
FROM TB_H_WORKFLOW 
WHERE DOCUMENT_NO = @DOC_NO

SELECT TOP 1 @@RELEASE_DOC_SEQ = DOCUMENT_SEQ
FROM TB_H_WORKFLOW
WHERE DOCUMENT_NO = @DOC_NO AND ISNULL(IS_APPROVED, '') = 'Y' AND DOCUMENT_SEQ = @@MAX_DOC_SEQ

SELECT
	ITEM_NO,
	APPROVAL_DESC LAST_STATUS,
	MAX(E.PERSONNEL_NAME) LAST_APPROVED_BY,
	[dbo].[fn_date_format](APPROVED_DT) LAST_APPROVED_DT,
	IS_APPROVED
FROM
(
	SELECT
		ROW_NUMBER() OVER(ORDER BY ITEM_NO) row_no,
		TBL.*
	FROM(
		SELECT
			DENSE_RANK() OVER(ORDER BY DOCUMENT_SEQ DESC) rown,
			DOCUMENT_SEQ,
			ITEM_NO,
			APPROVAL_DESC,
			APPROVED_BY,
			APPROVED_DT,
			IS_APPROVED
		FROM TB_H_WORKFLOW 
		WHERE DOCUMENT_NO = @DOC_NO
			  AND ((DOCUMENT_SEQ < @@NEXT_DOC_SEQ AND @@RELEASE_DOC_SEQ = 0) OR ((DOCUMENT_SEQ = @@RELEASE_DOC_SEQ) AND @@RELEASE_DOC_SEQ <> 0))
	)TBL WHERE rown = 1
)TBL1
	LEFT JOIN TB_R_SYNCH_EMPLOYEE E
		ON E.NOREG = TBL1.APPROVED_BY
WHERE row_no >= 1 AND row_no <= 10
GROUP BY
	ITEM_NO,
	APPROVAL_DESC,
	APPROVED_DT,
	IS_APPROVED