DECLARE @@PROCESS_ID BIGINT,
		@@MODULE VARCHAR(1) = '2',
		@@FUNCTION VARCHAR(6) = '202002',
		@@MSG VARCHAR(MAX),
		@@MSG_ID VARCHAR(10),
		@@LOCATION VARCHAR(MAX) = 'Cancel PR Initialization',
		@@STATUS VARCHAR(10) = 'FAILED'

SET @@MSG = 'Cancel PR Process Initialization'
SET @@MSG_ID = 'MSG0000085'
EXEC dbo.sp_PutLog @@MSG, @USER_ID, @@LOCATION, @@PROCESS_ID OUTPUT, @@MSG_ID, 'INF', @@MODULE, @@FUNCTION, 1;

BEGIN TRY
	INSERT INTO [dbo].[TB_T_LOCK]
			([PROCESS_ID]
			,[MODULE_ID]
			,[FUNCTION_ID]
			,[USER_ID]
			,[USER_NAME]
			,[CREATED_BY]
			,[CREATED_DT]
			,[CHANGED_BY]
			,[CHANGED_DT])
		VALUES
			(@@PROCESS_ID
			,@@MODULE
			,@@FUNCTION
			,@USER_ID
			,@USERNAME
			,@USER_ID
			,GETDATE()
			,null
			,null)
	
	UPDATE TB_R_PR_H SET PROCESS_ID = @@PROCESS_ID WHERE PR_NO = @PR_NO
	SET @@STATUS = 'SUCCESS'
	SET @@MSG = CONVERT(VARCHAR, @@PROCESS_ID)
END TRY
BEGIN CATCH
	SELECT @@MSG = ERROR_MESSAGE()
	SET @@STATUS = 'ERROR'
END CATCH

SELECT @@MSG AS [MESSAGE], @@STATUS AS PROCESS_STATUS