DECLARE @@AUTH INT,
		@@EXIST INT,
		@@MESSAGE VARCHAR(MAX)

SELECT @@AUTH = COUNT(1) 
FROM TB_T_LOCK A INNER JOIN TB_R_PR_H B
	ON A.PROCESS_ID = B.PROCESS_ID AND A.[USER_ID] = @USER_ID
	AND B.PR_NO = @PR_NO 

SELECT @@EXIST = COUNT(1) 
FROM TB_T_LOCK A INNER JOIN TB_R_PR_H B
	ON A.PROCESS_ID = B.PROCESS_ID AND B.PR_NO = @PR_NO 

IF(@@AUTH <> 0 OR @@EXIST = 0)
BEGIN
	BEGIN TRY
		UPDATE TB_R_PR_H SET PROCESS_ID = NULL WHERE PR_NO = @PR_NO
		UPDATE TB_R_PR_ITEM SET PROCESS_ID = NULL WHERE PR_NO = @PR_NO AND PROCESS_ID = @PROCESS_ID
		DELETE FROM TB_T_LOCK WHERE PROCESS_ID = @PROCESS_ID
		SET @@MESSAGE = 'SUCCESS'
	END TRY
	BEGIN CATCH
		SELECT @@MESSAGE = ERROR_MESSAGE()
	END CATCH
END
ELSE
BEGIN
	SELECT @@MESSAGE = MESSAGE_TEXT FROM TB_M_MESSAGE WHERE MESSAGE_ID = 'WRN00009'
END

SELECT @@MESSAGE