DECLARE @@OPEN_QTY DECIMAL(7,2), @@STATUS VARCHAR(64), @@PR_ITEM_NO VARCHAR(10)

SELECT @@PR_ITEM_NO = REPLICATE('0', 5-LEN(@ITEM_NO)) + @ITEM_NO

BEGIN TRY
	BEGIN TRANSACTION
	SELECT @@OPEN_QTY = OPEN_QTY 
	FROM TB_R_PR_ITEM 
	WHERE PR_NO = @PR_NO AND PR_ITEM_NO = @@PR_ITEM_NO

	UPDATE TB_R_PR_ITEM
	SET	OPEN_QTY = 0,
		CANCEL_QTY = ISNULL(CANCEL_QTY,0) + @@OPEN_QTY,
		CHANGED_BY = @USER_ID,
		CHANGED_DT = GETDATE()
	WHERE PR_NO = @PR_NO AND PR_ITEM_NO = @@PR_ITEM_NO

	SET @@STATUS = 'SUCCESS'
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	SET @@STATUS = 'ERROR'
	ROLLBACK TRANSACTION
END CATCH

SELECT @@STATUS