SELECT DISTINCT PROCESS_ID ProcessId, 
	ACTION, 
	CAST(SEND_PRIORITY AS INT) [Priority],
	(CASE WHEN ACTION = 'I' THEN 'Insert' WHEN ACTION = 'U' THEN 'Update' ELSE 'Cancel' END) Variable
FROM TB_H_FUND_COMMITMENT_REQUEST
WHERE PROCESS_ID = @ProcessId
ORDER BY CAST(SEND_PRIORITY AS INT) ASC