UPDATE A
SET EARMARK_FUND_DOC_NO = B.FUND_DOCUMENT_DOC_NO,
	EARMARK_FUND_ITEM_NO = B.FUND_DOCUMENT_DOC_LINE_ITEM,
	CHANGED_BY = @Username,
	CHANGED_DT = GETDATE()
FROM TB_T_PR_ITEM A
JOIN TB_H_FUND_COMMITMENT_RESPONSE B ON A.PROCESS_ID = B.PROCESS_ID
	AND A.ITEM_NO = B.DOCUMENT_LINE_ITEM_NO
WHERE B.PROCESS_ID = @ProcessId
	AND B.ACTION = @Action

UPDATE A
SET EARMARK_FUND_DOC_NO = B.FUND_DOCUMENT_DOC_NO,
	EARMARK_FUND_ITEM_NO = B.FUND_DOCUMENT_DOC_LINE_ITEM,
	CHANGED_BY = @Username,
	CHANGED_DT = GETDATE()
FROM TB_R_PR_ITEM A
JOIN TB_H_FUND_COMMITMENT_RESPONSE B ON A.PR_NO = LEFT(DOCUMENT_NO, 10)
	AND A.PR_ITEM_NO = B.DOCUMENT_LINE_ITEM_NO
WHERE B.PROCESS_ID = @ProcessId
	AND B.ACTION = @Action