SELECT A.START_DT AS StartDt,
	   A.END_DT AS EndDt,
	   C.FUNCTION_NAME AS FunctionName,
	   A.PROCESS_ID AS ProcessId,
	   A.PROCESS_STATUS AS Status,
	   B.SYSTEM_VALUE AS StatusValue,
	   A.CREATED_BY AS CreatedBy
FROM TB_R_LOG_H A 
	INNER JOIN TB_M_SYSTEM B ON B.SYSTEM_REMARK = 'Process Status Master'
		AND B.FUNCTION_ID = '00000'
		AND A.PROCESS_STATUS = B. SYSTEM_CD
		AND A.PROCESS_ID = @ProcessId
	INNER JOIN TB_M_FUNCTION C ON A.FUNCTION_ID = C.FUNCTION_ID