SELECT COUNT(1)
	FROM TB_M_VALUATION_CLASS A
		INNER JOIN TB_M_PROCUREMENT_TYPE B
			ON A.PROCUREMENT_TYPE = B.PROCUREMENT_TYPE
		--INNER JOIN TB_M_PURCHASING_GRP C
		--	ON A.PURCHASING_GROUP_CD = C.PURCHASING_GRP_CD
		INNER JOIN TB_M_COORDINATOR C
			ON A.PURCHASING_GROUP_CD = C.COORDINATOR_CD
		INNER JOIN TB_M_CALCULATION_SCHEME D
			ON A.CALCULATION_SCHEME_CD = D.CALCULATION_SCHEME_CD
		--LEFT JOIN TB_M_PURCHASING_GRP E
		--	ON A.FD_GROUP_CD = E.PURCHASING_GRP_CD
		LEFT JOIN TB_M_COORDINATOR E
			ON (A.FD_GROUP_CD = E.COORDINATOR_CD) OR A.PR_COORDINATOR= E.COORDINATOR_CD
		--LEFT JOIN TB_M_PR_COORDINATOR F
		--	ON A.PR_COORDINATOR = F.PR_COORDINATOR_CD
		WHERE ((VALUATION_CLASS LIKE '%' + @VALUATION_CLASS + '%'
				AND isnull(@VALUATION_CLASS, '') <> ''
				OR (isnull(@VALUATION_CLASS, '') = '')))
		AND ((VALUATION_CLASS_DESC LIKE '%' + @VALUATION_CLASS_DESC + '%'
			AND isnull(@VALUATION_CLASS_DESC, '') <> ''
			OR (isnull(@VALUATION_CLASS_DESC, '') = '')))
		AND ((AREA_DESC LIKE '%' + @AREA_DESC + '%'
			AND isnull(@AREA_DESC, '') <> ''
			OR (isnull(@AREA_DESC, '') = '')))
		AND ((A.PROCUREMENT_TYPE = @PROCUREMENT_TYPE
			AND isnull(@PROCUREMENT_TYPE, '') <> ''
			OR (isnull(@PROCUREMENT_TYPE, '') = '')))
		AND ((A.PURCHASING_GROUP_CD = @PURCHASING_GROUP_CD
			AND isnull(@PURCHASING_GROUP_CD, '') <> ''
			OR (isnull(@PURCHASING_GROUP_CD, '') = '')))
		AND ((A.CALCULATION_SCHEME_CD = @CALCULATION_SCHEME_CD
			AND isnull(@CALCULATION_SCHEME_CD, '') <> ''
			OR (isnull(@CALCULATION_SCHEME_CD, '') = '')))
		AND ((A.FD_GROUP_CD = @FD_GROUP_CD
			AND isnull(@FD_GROUP_CD, '') <> ''
			OR (isnull(@FD_GROUP_CD, '') = '')))
		AND ((A.PR_COORDINATOR LIKE '%' + @PR_COORDINATOR + '%'
			AND isnull(@PR_COORDINATOR, '') <> ''
			OR (isnull(@PR_COORDINATOR, '') = '')))