SELECT VALUATION_CLASS,
	   VALUATION_CLASS_DESC,
	   PR_COORDINATOR as PR_COORDINATOR_CD, -- add by khanif hanafi 17-07-2019
	   ITEM_CLASS, -- add by khanif hanafi 17-07-2019
	   AREA_DESC,
	   PROCUREMENT_TYPE,
	   PURCHASING_GROUP_CD,
	   FD_GROUP_CD,
	   CALCULATION_SCHEME_CD,
	   'A' AS STATUS,
	   MATL_GROUP				---added : 20190710 : isid.rgl
FROM TB_M_VALUATION_CLASS
	 WHERE VALUATION_CLASS = @VALUATION_CLASS AND PROCUREMENT_TYPE = @PR_TYPE