declare @@PROC_CH varchar(max)

set @@PROC_CH = (select distinct top  1 PROC_CHANNEL_CD from TB_M_COORDINATOR where COORDINATOR_CD = @PURCHASING_GROUP_CD)

IF(@IS_EDIT = 0)
BEGIN
	INSERT INTO [dbo].[TB_M_VALUATION_CLASS]
			   ([VALUATION_CLASS]
			   ,[VALUATION_CLASS_DESC]
			   ,[AREA_DESC]
			   ,[PROCUREMENT_TYPE]
			   ,[CALCULATION_SCHEME_CD]
			   ,[PURCHASING_GROUP_CD]
			   ,[PROC_CHANNEL_CD]
               ,[MATL_GROUP]
			   ,[FD_GROUP_CD]
			   ,[STATUS]
			   ,[CREATED_BY]
			   ,[CREATED_DT]
			   ,[CHANGED_BY]
			   ,[CHANGED_DT]
			   ,[ITEM_CLASS]
			   ,[PR_COORDINATOR]
			   ,[ITEM_TYPE]
			   ,[APPROVAL_INTERVAL])
		 VALUES
			   (@VALUATION_CLASS
			   ,@VALUATION_CLASS_DESC
			   ,@AREA_DESC
			   ,@PROCUREMENT_TYPE
			   ,@CALCULATION_SCHEME_CD
			   ,@PURCHASING_GROUP_CD
			   ,@@PROC_CH
               ,@MATL_GROUP
			   ,@FD_GROUP_CD
			   ,@STATUS
			   ,@USER_ID
			   ,GETDATE()
			   ,null
			   ,null
			   ,@ITEM_CLASS
			   ,@PR_COORDINATOR_CD
			   ,'N'
			   ,1
			   )
END
ELSE
BEGIN
	UPDATE TB_M_VALUATION_CLASS
		SET VALUATION_CLASS_DESC = @VALUATION_CLASS_DESC,
			AREA_DESC = @AREA_DESC,
			PROCUREMENT_TYPE = @PROCUREMENT_TYPE,
			PURCHASING_GROUP_CD = @PURCHASING_GROUP_CD,
			FD_GROUP_CD = @FD_GROUP_CD,
            MATL_GROUP = @MATL_GROUP,
			CALCULATION_SCHEME_CD = @CALCULATION_SCHEME_CD,
			[STATUS] = @STATUS,
			ITEM_CLASS = @ITEM_CLASS,
			PROC_CHANNEL_CD =@@PROC_CH,
			PR_COORDINATOR = @PR_COORDINATOR_CD,
			CHANGED_BY = @USER_ID,
			CHANGED_DT = GETDATE()
		WHERE VALUATION_CLASS = @VALUATION_CLASS
END
SELECT ''