DECLARE @@EXIST INT,
		@@MESSAGE VARCHAR(MAX) = ''

SELECT @@EXIST = COUNT(1)
	FROM TB_M_VALUATION_CLASS
	WHERE VALUATION_CLASS = @VALUATION_CLASS

IF(@@EXIST > 0)
BEGIN
	SET @@MESSAGE = 'Valuation Class ' + @VALUATION_CLASS + ' already exist in master data'
END

SELECT @@MESSAGE
