SELECT 	A.PROC_USAGE_CD,
		A.GENTANI_HEADER_TYPE,
		A.GENTANI_HEADER_CD,				  		  
		CONVERT(varchar(10),A.VALID_DT_FR,102) VALID_DT_FR,	
		CONVERT(varchar(10),A.VALID_DT_TO,102) VALID_DT_TO,
		A.CREATED_BY,			  
		CONVERT(varchar(10),A.CREATED_DT,102) CREATED_DT,
		A.CHANGED_BY,			  
		CONVERT(varchar(10),A.CHANGED_DT,102) CHANGED_DT
FROM TB_M_GENTANI_HEADER A	 
WHERE   ((A.PROC_USAGE_CD = @ProcUsage) OR (@ProcUsage = 'x'))
		AND (A.GENTANI_HEADER_TYPE like '%' + @HeaderType + '%')
		AND (A.GENTANI_HEADER_CD like '%' + @HeaderCd + '%')		
		AND (@ValidDt BETWEEN A.VALID_DT_FR AND A.VALID_DT_TO) 