
SELECT COUNT(*) FROM(
SELECT DISTINCT 
	DENSE_RANK() OVER (ORDER BY GL_ACCOUNT_CD ASC) AS number,  
	GL_ACCOUNT_CD, 
	GL_ACCOUNT_DESC 
FROM (
	SELECT GL_ACCOUNT_CD, GL_ACCOUNT_DESC FROM TB_M_GL_ACCOUNT 
	WHERE GL_ACCOUNT_CD IN (SELECT GL_CODE FROM fnt_GetGLAccountMappingWBSList(@WBS_NO))
) TBL  
WHERE 
(((GL_ACCOUNT_CD LIKE '%' + @GL_ACCOUNT_PARAM + '%'
	AND isnull(@GL_ACCOUNT_PARAM, '') <> ''
	OR (isnull(@GL_ACCOUNT_PARAM, '') = '')))
OR ((GL_ACCOUNT_DESC LIKE '%' +   @GL_ACCOUNT_PARAM  + '%'
	AND isnull(@GL_ACCOUNT_PARAM, '') <> ''
	OR (isnull(@GL_ACCOUNT_PARAM, '') = ''))))
) TBL1 WHERE number >= @start AND number <= @length
