SELECT COUNT(DISTINCT VALUATION_CLASS) FROM TB_M_VALUATION_CLASS
WHERE
((PR_COORDINATOR = @PR_COORDINATOR
	AND isnull(@PR_COORDINATOR, '') <> ''
	OR (isnull(@PR_COORDINATOR, '') = '')))
AND ((PROCUREMENT_TYPE = @PR_TYPE
	AND isnull(@PR_TYPE, '') <> ''
	OR (isnull(@PR_TYPE, '') = '')))
AND (((VALUATION_CLASS LIKE '%' + @VALUATION_CLASS_PARAM + '%'
	AND isnull(@VALUATION_CLASS_PARAM, '') <> ''
	OR (isnull(@VALUATION_CLASS_PARAM, '') = '')))
OR ((VALUATION_CLASS_DESC LIKE '%' + @VALUATION_CLASS_PARAM  + '%'
	AND isnull(@VALUATION_CLASS_PARAM, '') <> ''
	OR (isnull(@VALUATION_CLASS_PARAM, '') = ''))))
