IF SUBSTRING(@GL_ACCOUNT_PARAM,1,1)='6'
BEGIN
	SELECT DISTINCT 
		COST_CENTER_CD as COST_CENTER, 
		COST_CENTER_DESC 
	FROM TB_M_COST_CENTER WHERE DIVISION_ID = @DIVISION_ID AND GETDATE() BETWEEN VALID_DT_FROM AND VALID_DT_TO
	AND COST_CENTER_CD LIKE 'AA%'
END
ELSE
BEGIN
	SELECT DISTINCT 
		COST_CENTER_CD as COST_CENTER, 
		COST_CENTER_DESC 
	FROM TB_M_COST_CENTER WHERE DIVISION_ID = @DIVISION_ID AND GETDATE() BETWEEN VALID_DT_FROM AND VALID_DT_TO
END