DECLARE @@ASSET_NO_PAR VARCHAR(MAX)
DECLARE @@SUB_ASSET_NO_PAR VARCHAR(MAX)

SET @@ASSET_NO_PAR = @ASSET_NO;
SET @@SUB_ASSET_NO_PAR = @SUB_ASSET_NO;

SELECT DISTINCT 
	COST_CENTER as COST_CENTER, 
	COST_CENTER COST_CENTER_DESC
FROM [FAMS_DB].[FAMS_DB].[dbo].[GET_LIST_ASSET]
WHERE ASSET_NO = @@ASSET_NO_PAR
	AND SUB_ASSET_NO = @@SUB_ASSET_NO_PAR