IF(@ITEM_TYPE = 'P')
BEGIN
	SELECT * FROM(
	SELECT DISTINCT 
		DENSE_RANK() OVER (ORDER BY A.MAT_NO ASC) AS number, 
		A.MAT_NO AS MAT_NUMBER,
		A.MAT_DESC AS MAT_DESC,
		A.CAR_FAMILY_CD as CAR_FAMILY_CD,
		A.CAR_FAMILY_CD as CAR_FAMILY_DESC,
		A.MAT_TYPE_CD as MAT_TYPE_CD,
		A.MAT_TYPE_CD as MAT_TYPE_DESC,
		A.MAT_GRP_CD as MAT_GRP_CD,
		A.MAT_GRP_CD as MAT_GRP_DESC,
		A.ORDER_UOM as UOM,
		A.VALUATION_CLASS as VALUATION_CLASS,
		ISNULL(C.CURR_CD, '') as CURR,
		ISNULL(C.PRICE_AMOUNT, 0) as PRICE,
		A.QUOTA_FLAG as QUOTA_FLAG,
		B.VALUATION_CLASS_DESC as VALUATION_CLASS_DESC,
		A.CONSIGNMENT_CD
	FROM TB_M_MATERIAL_PART A
	JOIN TB_M_VALUATION_CLASS B ON A.VALUATION_CLASS = B.VALUATION_CLASS
	JOIN TB_M_SOURCE_LIST D ON D.MAT_NO = A.MAT_NO AND D.PLANT_CD = @PLANT_CD AND D.PROC_CHANNEL_CD = B.PROC_CHANNEL_CD AND GETDATE() BETWEEN D.VALID_DT_FROM AND D.VALID_DT_TO
	LEFT JOIN TB_M_MATERIAL_PRICE C  
			ON C.MAT_NO = A.MAT_NO 
			AND GETDATE() >= C.VALID_DT_FROM 
			AND GETDATE() <= C.VALID_DT_TO
	WHERE
	((A.VALUATION_CLASS LIKE '%' +   @VALUATION_CLASS  + '%'
		AND isnull(@VALUATION_CLASS, '') <> ''
		OR (isnull(@VALUATION_CLASS, '') = '')))
	AND ((B.PR_COORDINATOR = @PR_COORDINATOR
		AND isnull(@PR_COORDINATOR, '') <> ''
		OR (isnull(@PR_COORDINATOR, '') = '')))
	AND ((B.PROCUREMENT_TYPE = @PR_TYPE
		AND isnull(@PR_TYPE, '') <> ''
		OR (isnull(@PR_TYPE, '') = '')))
	AND (((A.MAT_NO LIKE '%' + @MAT_NUMBER_PARAM + '%'
		AND isnull(@MAT_NUMBER_PARAM, '') <> ''
		OR (isnull(@MAT_NUMBER_PARAM, '') = '')))
	OR ((A.MAT_DESC LIKE '%' +   @MAT_NUMBER_PARAM  + '%'
		AND isnull(@MAT_NUMBER_PARAM, '') <> ''
		OR (isnull(@MAT_NUMBER_PARAM, '') = '')))
	OR ((A.CAR_FAMILY_CD LIKE '%' +   @MAT_NUMBER_PARAM  + '%'
		AND isnull(@MAT_NUMBER_PARAM, '') <> ''
		OR (isnull(@MAT_NUMBER_PARAM, '') = '')))
	OR ((A.MAT_TYPE_CD LIKE '%' +   @MAT_NUMBER_PARAM  + '%'
		AND isnull(@MAT_NUMBER_PARAM, '') <> ''
		OR (isnull(@MAT_NUMBER_PARAM, '') = '')))
	OR ((A.MAT_GRP_CD LIKE '%' +   @MAT_NUMBER_PARAM  + '%'
		AND isnull(@MAT_NUMBER_PARAM, '') <> ''
		OR (isnull(@MAT_NUMBER_PARAM, '') = ''))))
	) TBL1
	WHERE number >= @start AND number <= @length
END
ELSE
BEGIN
	SELECT * FROM(
	SELECT DISTINCT 
		DENSE_RANK() OVER (ORDER BY A.MAT_NO ASC) AS number, 
		A.MAT_NO AS MAT_NUMBER,
		A.MAT_DESC AS MAT_DESC,
		'' as CAR_FAMILY_CD,
		'' as CAR_FAMILY_DESC,
		'' as MAT_TYPE_CD,
		'' as MAT_TYPE_DESC,
		'' as MAT_GRP_CD,
		'' as MAT_GRP_DESC,
		A.ORDER_UOM as UOM,
		A.VALUATION_CLASS as VALUATION_CLASS,
		C.CURR_CD as CURR,
		C.PRICE_AMOUNT as PRICE,
		A.QUOTA_FLAG as QUOTA_FLAG,
		B.VALUATION_CLASS_DESC as VALUATION_CLASS_DESC,
		A.CONSIGNMENT_CD
	FROM TB_M_MATERIAL_NONPART A
	JOIN TB_M_VALUATION_CLASS B ON A.VALUATION_CLASS = B.VALUATION_CLASS
	--JOIN TB_M_SOURCE_LIST D ON D.MAT_NO = A.MAT_NO AND D.PLANT_CD = @PLANT_CD AND D.PROC_CHANNEL_CD = B.PROC_CHANNEL_CD AND GETDATE() BETWEEN D.VALID_DT_FROM AND D.VALID_DT_TO
	LEFT JOIN TB_M_MATERIAL_PRICE C 
			ON C.MAT_NO = A.MAT_NO 
			AND GETDATE() >= C.VALID_DT_FROM 
			AND GETDATE() <= C.VALID_DT_TO
	WHERE
	((A.VALUATION_CLASS LIKE '%' +   @VALUATION_CLASS  + '%'
		AND isnull(@VALUATION_CLASS, '') <> ''
		OR (isnull(@VALUATION_CLASS, '') = '')))
	AND ((B.PR_COORDINATOR = @PR_COORDINATOR
		AND isnull(@PR_COORDINATOR, '') <> ''
		OR (isnull(@PR_COORDINATOR, '') = '')))
	AND ((B.PROCUREMENT_TYPE = @PR_TYPE
		AND isnull(@PR_TYPE, '') <> ''
		OR (isnull(@PR_TYPE, '') = '')))
	AND (((A.MAT_NO LIKE '%' + @MAT_NUMBER_PARAM + '%'
		AND isnull(@MAT_NUMBER_PARAM, '') <> ''
		OR (isnull(@MAT_NUMBER_PARAM, '') = '')))
	OR ((A.MAT_DESC LIKE '%' +   @MAT_NUMBER_PARAM  + '%'
		AND isnull(@MAT_NUMBER_PARAM, '') <> ''
		OR (isnull(@MAT_NUMBER_PARAM, '') = ''))))
	) TBL1
	WHERE number >= @start AND number <= @length
END