--SELECT PURCHASING_GRP_CD AS FD_GROUP_CD,
--	   PURCHASING_GRP_DESC AS FD_GROUP_DESC
--FROM TB_M_PURCHASING_GRP

SELECT [SYSTEM_CD] AS ITEM_CLASS
      ,[SYSTEM_VALUE] AS ITEM_CLASS_DESC
  FROM [dbo].[TB_M_SYSTEM]
  WHERE FUNCTION_ID = 'VCTYPE'