SELECT * FROM (
	SELECT ROW_NUMBER() OVER (ORDER BY MAT_NO ASC) Number,
	MAT_NO AS MAT_NO,
	VENDOR_CD AS VENDOR_CD,
	VALID_DT_FROM AS VALID_DT_FROM,
	VALID_DT_TO AS VALID_DT_TO,
	CREATED_BY AS CREATED_BY,
	CONVERT(VARCHAR(20),CREATED_DT, 105) AS CREATED_DT,
	CHANGED_BY AS CHANGED_BY,
	CONVERT(VARCHAR(20),CHANGED_DT, 105) AS CHANGED_DT

	FROM TB_M_SOURCE_LIST
	WHERE MAT_NO LIKE + '%' + ISNULL(@Criteria,'') + '%'
) AS TB
WHERE NUMBER BETWEEN @Start AND @Length