CREATE PROCEDURE sp_Currency_GetAllCurrency
AS
BEGIN
    SELECT DISTINCT CURR_CD, EXCHANGE_RATE, VALID_DT_FROM, VALID_DT_TO, DECIMAL_FORMAT FROM TB_M_EXCHANGE_RATE WHERE YEAR(VALID_DT_TO) = 9999 ORDER BY CURR_CD
END