CREATE PROCEDURE sp_Currency_GetCurrency
    @currencyCode VARCHAR(3)
AS
BEGIN
    SELECT CURR_CD, EXCHANGE_RATE, VALID_DT_FROM, VALID_DT_TO FROM TB_M_EXCHANGE_RATE WHERE YEAR(VALID_DT_TO) = 9999 AND CURR_CD = @currencyCode ORDER BY CURR_CD
END