USE [PAS_DB]
GO
/****** Object:  StoredProcedure [dbo].[sp_PRApproval_GetDetailDivisionList]    Script Date: 3/8/2021 8:51:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[sp_PRApproval_GetDetailDivisionList]
		@PR_NO varchar(11)='5000041131',
		@start bigint=1,
		@length bigint=10
AS
BEGIN
DECLARE @@STATUS_REGISTERED CHAR(2),
		@@STATUS_SH CHAR(2),
		@@STATUS_DPH CHAR(2),
		@@STATUS_DH CHAR(2)

DECLARE @@STATUS TABLE(
			SEQ INT,
			STATUS_CD CHAR(2)
		)

INSERT INTO @@STATUS
	SELECT ROW_NUMBER() OVER (ORDER BY STATUS_CD) AS SEQ,
		   STATUS_CD FROM TB_M_STATUS WHERE SEGMENTATION_CD = 1

SELECT @@STATUS_REGISTERED = STATUS_CD FROM @@STATUS WHERE SEQ = 1
SELECT @@STATUS_SH = STATUS_CD FROM @@STATUS WHERE SEQ = 2
SELECT @@STATUS_DPH = STATUS_CD FROM @@STATUS WHERE SEQ = 3
SELECT @@STATUS_DH = STATUS_CD FROM @@STATUS WHERE SEQ = 4


SELECT*FROM(
SELECT ROW_NUMBER() OVER (ORDER BY TBL.ITEM_NO ASC) AS NUMBER,
	CAST(CAST(TBL.ITEM_NO AS INT) AS VARCHAR) AS ITEM_NO, REG.PIC_REGISTERED, REG.ACTUAL_REGISTERED,
	SH.PIC_SH, SH.PLAN_SH, SH.ACTUAL_SH, SH.PLNLT_SH, CASE WHEN ISNULL(SH.ACTUAL_SH, '') <> '' THEN [dbo].[fn_datediff_workday](REG.ACTUAL_REGISTERED, SH.ACTUAL_SH) END AS ACTLT_SH,
	DPH.PIC_DPH, DPH.PLAN_DPH, DPH.ACTUAL_DPH, DPH.PLNLT_DPH, CASE WHEN ((ISNULL(SH.ACTUAL_SH, '') <> '') AND (ISNULL(DPH.ACTUAL_DPH, '') <> '')) THEN [dbo].[fn_datediff_workday](SH.ACTUAL_SH, DPH.ACTUAL_DPH) END AS ACTLT_DPH,
	DH.PIC_DH, DH.PLAN_DH, DH.ACTUAL_DH, DH.PLNLT_DH, CASE WHEN ((ISNULL(DPH.ACTUAL_DPH, '') <> '') AND (ISNULL(DH.ACTUAL_DH, '') <> '')) THEN [dbo].[fn_datediff_workday](DPH.ACTUAL_DPH, DH.ACTUAL_DH) END AS ACTLT_DH

FROM
(SELECT DISTINCT ITEM_NO FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO ) AS TBL
LEFT JOIN
--
(SELECT ITEM_NO, 
	   APPROVER_NAME AS PIC_REGISTERED, 
	   CASE WHEN(IS_APPROVED <> 'Y') THEN NULL ELSE CONVERT(VARCHAR, APPROVED_DT)  END AS ACTUAL_REGISTERED
FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO AND IS_DISPLAY = 'Y' AND APPROVAL_CD = @@STATUS_REGISTERED) AS REG ON REG.ITEM_NO=TBL.ITEM_NO
LEFT JOIN 
--
(SELECT ITEM_NO, 
	   APPROVER_NAME AS PIC_SH, 
	   [dbo].[fn_date_format]([dbo].[fn_dateadd_workday]((APPROVAL_INTERVAL-1)*(-1), INTERVAL_DATE)) AS PLAN_SH,
	   CASE WHEN(IS_APPROVED <> 'Y') THEN NULL ELSE CONVERT(VARCHAR, APPROVED_DT)  END AS ACTUAL_SH,
	   CONVERT(VARCHAR, APPROVAL_INTERVAL) AS PLNLT_SH
FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO AND IS_DISPLAY = 'Y' AND APPROVAL_CD = @@STATUS_SH) AS SH ON SH.ITEM_NO=TBL.ITEM_NO
LEFT JOIN 
--
(SELECT ITEM_NO, 
	   APPROVER_NAME AS PIC_DPH, 
	   [dbo].[fn_date_format]([dbo].[fn_dateadd_workday]((APPROVAL_INTERVAL-1)*(-1), INTERVAL_DATE)) AS PLAN_DPH,
	   CASE WHEN(IS_APPROVED <> 'Y') THEN NULL ELSE CONVERT(VARCHAR, APPROVED_DT)  END AS ACTUAL_DPH,
	   CONVERT(VARCHAR, APPROVAL_INTERVAL) AS PLNLT_DPH
FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO AND IS_DISPLAY = 'Y' AND APPROVAL_CD = @@STATUS_DPH) AS DPH ON DPH.ITEM_NO=TBL.ITEM_NO
LEFT JOIN
--
(SELECT ITEM_NO, 
	   APPROVER_NAME AS PIC_DH, 
	   [dbo].[fn_date_format]([dbo].[fn_dateadd_workday]((APPROVAL_INTERVAL-1)*(-1), INTERVAL_DATE)) AS PLAN_DH,
	   CASE WHEN(IS_APPROVED <> 'Y') THEN NULL ELSE CONVERT(VARCHAR, APPROVED_DT)  END AS ACTUAL_DH,
	   CONVERT(VARCHAR, APPROVAL_INTERVAL) AS PLNLT_DH
FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO AND IS_DISPLAY = 'Y' AND APPROVAL_CD = @@STATUS_DH) AS DH ON DH.ITEM_NO=TBL.ITEM_NO
)AS D
WHERE D.NUMBER >= @start AND D.NUMBER <= @length

END