USE [PAS_DB]
GO
/****** Object:  StoredProcedure [dbo].[sp_PRApproval_GetDetailCoordinatorList]    Script Date: 3/8/2021 8:51:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[sp_PRApproval_GetDetailCoordinatorList]
		@PR_NO varchar(11)='5000041131',
		@start bigint=1,
		@length bigint=10
AS
BEGIN
DECLARE @@STATUS_LAST_DIV CHAR(2),
		@@STATUS_STAFF CHAR(2),
		@@STATUS_SH CHAR(2),
		@@STATUS_DPH CHAR(2),
		@@STATUS_DH CHAR(2)


DECLARE @@STATUS TABLE(
			SEQ INT,
			STATUS_CD CHAR(2)
		)

INSERT INTO @@STATUS
	SELECT ROW_NUMBER() OVER (ORDER BY STATUS_CD) AS SEQ,
		   STATUS_CD FROM TB_M_STATUS WHERE SEGMENTATION_CD = 2

SELECT TOP 1 @@STATUS_LAST_DIV = STATUS_CD FROM TB_R_WORKFLOW W JOIN 
		   TB_M_STATUS S ON W.APPROVAL_CD = S.STATUS_CD AND S.SEGMENTATION_CD = 1 AND W.DOCUMENT_NO = @PR_NO 
		   AND IS_DISPLAY = 'Y' ORDER BY W.ITEM_NO DESC
SELECT @@STATUS_STAFF = STATUS_CD FROM @@STATUS WHERE SEQ = 1
SELECT @@STATUS_SH = STATUS_CD FROM @@STATUS WHERE SEQ = 2
SELECT @@STATUS_DPH = STATUS_CD FROM @@STATUS WHERE SEQ = 3
SELECT @@STATUS_DH = STATUS_CD FROM @@STATUS WHERE SEQ = 4

SELECT*FROM(
SELECT ROW_NUMBER() OVER (ORDER BY TBL.ITEM_NO ASC) AS NUMBER,
	CAST(CAST(TBL.ITEM_NO AS INT) AS VARCHAR) AS ITEM_NO,
	STA.PIC_STAFF, 
	STA.PLAN_STAFF, 
	[dbo].[fn_date_format] (STA.ACTUAL_STAFF) AS ACTUAL_STAFF, 
	STA.PLNLT_STAFF,
	CASE WHEN(ISNULL(DIV.ACTUAL_DIVISION, '') <> '') THEN [dbo].[fn_datediff_workday](DIV.ACTUAL_DIVISION, STA.ACTUAL_STAFF) END AS ACTLT_STAFF,

	SH.PIC_SH, 
	SH.PLAN_SH, 
	[dbo].[fn_date_format] (SH.ACTUAL_SH) AS ACTUAL_SH, 
	SH.PLNLT_SH,
	CASE WHEN(ISNULL(DIV.ACTUAL_DIVISION, '') <> '') THEN [dbo].[fn_datediff_workday](DIV.ACTUAL_DIVISION, SH.ACTUAL_SH) END AS ACTLT_SH,

	DPH.PIC_DPH, 
	DPH.PLAN_DPH, 
	CASE WHEN(ISNULL(SH.ACTUAL_SH, '') <> '') THEN [dbo].[fn_date_format] (DPH.ACTUAL_DPH) END AS ACTUAL_DPH, 
	DPH.PLNLT_DPH,
	CASE WHEN((ISNULL(SH.ACTUAL_SH, '') <> '') AND (ISNULL(DPH.ACTUAL_DPH, '') <> '')) THEN [dbo].[fn_datediff_workday](SH.ACTUAL_SH, DPH.ACTUAL_DPH) END AS ACTLT_DPH

FROM

(SELECT DISTINCT ITEM_NO FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO ) AS TBL
LEFT JOIN
--
(SELECT ITEM_NO, 
	   CONVERT(VARCHAR, APPROVED_DT) AS ACTUAL_DIVISION
FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO AND IS_DISPLAY = 'Y' AND APPROVAL_CD = @@STATUS_LAST_DIV) AS DIV ON DIV.ITEM_NO=TBL.ITEM_NO
LEFT JOIN 
--
(SELECT ITEM_NO, 
	   CASE WHEN(APPROVER_NAME = '-' AND IS_APPROVED = 'N') THEN '-' ELSE CASE WHEN(APPROVER_NAME = '-' AND IS_APPROVED = 'Y') THEN (SELECT TOP 1 SE.PERSONNEL_NAME FROM TB_R_SYNCH_EMPLOYEE SE WHERE SE.NOREG = APPROVED_BYPASS ) ELSE APPROVER_NAME END END AS PIC_STAFF, 
	   [dbo].[fn_date_format]([dbo].[fn_dateadd_workday]((APPROVAL_INTERVAL-1)*(-1), INTERVAL_DATE)) AS PLAN_STAFF,
	   CASE WHEN(IS_APPROVED <> 'Y') THEN NULL ELSE CONVERT(VARCHAR, APPROVED_DT) END AS ACTUAL_STAFF,
	   CONVERT(VARCHAR, APPROVAL_INTERVAL) AS PLNLT_STAFF
FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO AND IS_DISPLAY = 'Y' AND APPROVAL_CD = @@STATUS_STAFF) AS STA ON STA.ITEM_NO=TBL.ITEM_NO
LEFT JOIN 
--
(SELECT ITEM_NO, 
	   APPROVER_NAME AS PIC_SH, 
	   [dbo].[fn_date_format]([dbo].[fn_dateadd_workday]((APPROVAL_INTERVAL-1)*(-1), INTERVAL_DATE)) AS PLAN_SH,
	   CASE WHEN(IS_APPROVED <> 'Y') THEN NULL ELSE CONVERT(VARCHAR, APPROVED_DT)  END AS ACTUAL_SH,
	   CONVERT(VARCHAR, APPROVAL_INTERVAL) AS PLNLT_SH
FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO AND IS_DISPLAY = 'Y' AND APPROVAL_CD = @@STATUS_SH) AS SH ON SH.ITEM_NO=TBL.ITEM_NO
LEFT JOIN 
--
(SELECT ITEM_NO, 
	   APPROVER_NAME AS PIC_DPH, 
	   [dbo].[fn_date_format]([dbo].[fn_dateadd_workday]((APPROVAL_INTERVAL-1)*(-1), INTERVAL_DATE)) AS PLAN_DPH,
	   CASE WHEN(IS_APPROVED <> 'Y') THEN NULL ELSE CONVERT(VARCHAR, APPROVED_DT)  END AS ACTUAL_DPH,
	   CONVERT(VARCHAR, APPROVAL_INTERVAL) AS PLNLT_DPH
FROM TB_R_WORKFLOW WHERE DOCUMENT_NO = @PR_NO AND IS_DISPLAY = 'Y' AND APPROVAL_CD = @@STATUS_DPH) AS DPH ON DPH.ITEM_NO=TBL.ITEM_NO

)AS D
WHERE D.NUMBER >= @start AND D.NUMBER <= @length

END