CREATE PROCEDURE sp_PRApproval_GetNoticeUserList
    @docNo VARCHAR(11)
AS
BEGIN
	DECLARE @docType VARCHAR(2) = ''
	
	SELECT TOP 1 @docType = DOC_TYPE FROM TB_M_STATUS WHERE STATUS_CD = (
		SELECT TOP 1 APPROVAL_CD FROM TB_R_WORKFLOW rw 
		WHERE rw.DOCUMENT_NO = @docNo ORDER BY rw.DOCUMENT_SEQ ASC
	)

	IF(@docType = 'PR')
	BEGIN
		SELECT DISTINCT
			APPROVED_BY AS 'NOTICE_TO_USER',
			APPROVER_NAME AS 'NOTICE_TO_ALIAS'
		FROM TB_R_WORKFLOW
		WHERE DOCUMENT_NO = @docNo
		ORDER BY APPROVER_NAME ASC
	END
	BEGIN
		--Added By : FID) Intan Puspitasari
		--Added Dt : 13/06/2016
		--Note : If doc type = PO then get user from purchasing group too

		SELECT dt.NOTICE_TO_USER, dt.NOTICE_TO_ALIAS FROM (
			SELECT DISTINCT
				APPROVED_BY AS 'NOTICE_TO_USER',
				APPROVER_NAME AS 'NOTICE_TO_ALIAS'
			FROM TB_R_WORKFLOW
			WHERE DOCUMENT_NO = @docNo
			UNION
			SELECT DISTINCT
				cm.NOREG AS 'NOTICE_TO_USER',
				cm.PIC_NAME AS 'NOTICE_TO_ALIAS'
			FROM TB_M_COORDINATOR_MAPPING cm
				JOIN TB_R_PO_H poh ON cm.COORDINATOR_CD = poh.PURCHASING_GRP_CD
			WHERE poh.PO_NO = @docNo
		)dt ORDER BY dt.NOTICE_TO_ALIAS ASC
	END
END