DECLARE @@STATUS VARCHAR(10) = 'SUCCESS',
		@@MESSAGE VARCHAR(MAX) = '',
		@@EXISTS INT = 0

--1. Check if PO <> null
IF(@@STATUS = 'SUCCESS')
BEGIN
	SELECT @@EXISTS = COUNT(1) FROM TB_R_ASSET WHERE PR_NO = @PR_NO AND PR_ITEM_NO = @ITEM_NO AND SEQ_NO = @SEQ_NO AND ISNULL(PO_NO, '') <> ''
	IF(@@EXISTS > 0)
	BEGIN
		SET @@STATUS = 'ERR'
		SET @@MESSAGE = 'Item already used by Purchase Order'
	END
END

--2. Check if asset in progress used by PO
IF(@@STATUS = 'SUCCESS')
BEGIN
	SET @@EXISTS = 0
	SELECT @@EXISTS = COUNT(1) FROM TB_R_ASSET WHERE PR_NO = @PR_NO AND PR_ITEM_NO = @ITEM_NO AND SEQ_NO = @SEQ_NO AND ISNULL(PROCESS_ID, '') <> ''
	IF(@@EXISTS > 0)
	BEGIN
		SET @@STATUS = 'ERR'
		SET @@MESSAGE = 'Item is being used by Purchase Order'
	END
END

IF(@@STATUS = 'SUCCESS')
BEGIN
	DELETE FROM TB_R_ASSET WHERE PR_NO = @PR_NO AND PR_ITEM_NO = @ITEM_NO AND SEQ_NO = @SEQ_NO
END

SELECT @@STATUS + '|' + @@MESSAGE