SELECT PR_NO
	   ,PR_ITEM_NO AS ITEM_NO
	   ,SEQ_NO
	   ,ASSET_CATEGORY
	   ,ASSET_CLASS
	   ,ASSET_LOCATION
	   ,ASSET_NO
	   ,SUB_ASSET_NO AS SUBASSET_NO
	   ,SERIAL_NO
	   ,CASE WHEN(VALID_FLAG = 'Y') THEN 'Valid' ELSE 'Invalid' END AS VALID_FLAG
	   ,SYSTEM_MSG AS MESSAGE
FROM TB_T_ASSET WHERE PROCESS_ID = @PROCESS_ID AND DELETE_FLAG = 'N'