EXEC [dbo].[sp_asset_getList] 
		@PR_NO, 
		@STATUS_CD,
		@ITEM_NO,
		@ASSET_NO,
		@ASSET_CATEGORY,
		@SUBASSET_NO,
		@ASSET_CLASS,
		@REGISTRATION_DATE_FROM,
		@REGISTRATION_DATE_TO,
		@Start, 
		@Length