BEGIN TRANSACTION
BEGIN TRY
	INSERT INTO [dbo].[TB_R_ASSET]
			   ([PR_NO]
			   ,[PR_ITEM_NO]
			   ,[SEQ_NO]
			   ,[PROCESS_ID]
			   ,[REGISTRATION_DT]
			   ,[ASSET_CATEGORY]
			   ,[ASSET_CLASS]
			   ,[ASSET_LOCATION]
			   ,[ASSET_NO]
			   ,[SUB_ASSET_NO]
			   ,[SERIAL_NO]
			   ,[PO_NO]
			   ,[PO_ITEM_NO]
			   ,[ASSET_STATUS]
			   ,[CREATED_BY]
			   ,[CREATED_DT]
			   ,[CHANGED_BY]
			   ,[CHANGED_DT])
		SELECT PR_NO
			   ,PR_ITEM_NO
			   ,SEQ_NO
			   ,NULL
			   ,REGISTRATION_DT
			   ,ASSET_CATEGORY
			   ,ASSET_CLASS
			   ,ASSET_LOCATION
			   ,ASSET_NO
			   ,SUB_ASSET_NO
			   ,SERIAL_NO
			   ,NULL
			   ,NULL
			   ,'51' --status diisi apa?
			   ,CREATED_BY
			   ,CREATED_DT
			   ,CHANGED_BY
			   ,CHANGED_DT
		FROM TB_T_ASSET WHERE PROCESS_ID = @PROCESS_ID AND DELETE_FLAG = 'N' AND VALID_FLAG = 'Y'

	DELETE FROM TB_T_ASSET WHERE PROCESS_ID = @PROCESS_ID

	COMMIT TRANSACTION

	SELECT 'SUCCESS' AS PROCESS_STATUS, '' AS [MESSAGE]
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	SELECT 'ERR' AS PROCESS_STATUS, ERROR_MESSAGE() AS [MESSAGE]
END CATCH