DECLARE @@PR_NO VARCHAR(12),
		@@PR_ITEM_NO VARCHAR(5),
		@@PR_QTY DECIMAL(7, 2),
		@@ASSET_QTY DECIMAL(7, 2)

DECLARE db_cursor_temp CURSOR FOR
	SELECT DISTINCT TA.PR_NO, TA.PR_ITEM_NO, PRI.PR_QTY
	FROM TB_T_ASSET TA JOIN TB_R_PR_ITEM PRI ON TA.PR_NO = PRI.PR_NO AND TA.PR_ITEM_NO = PRI.PR_ITEM_NO
		WHERE TA.PROCESS_ID = @PROCESS_ID AND TA.VALID_FLAG = 'Y' AND TA.DELETE_FLAG = 'N'
OPEN db_cursor_temp
FETCH NEXT FROM db_cursor_temp
		INTO @@PR_NO, @@PR_ITEM_NO, @@PR_QTY
WHILE @@@FETCH_STATUS = 0
BEGIN
	SELECT @@ASSET_QTY = ISNULL(COUNT(DISTINCT dt.SEQ_NO), 0) FROM (
		SELECT SEQ_NO FROM TB_T_ASSET TA WHERE TA.PROCESS_ID = @PROCESS_ID AND TA.PR_NO = @@PR_NO AND TA.PR_ITEM_NO = @@PR_ITEM_NO UNION
		SELECT SEQ_NO FROM TB_R_ASSET RA WHERE RA.PR_NO = @@PR_NO AND RA.PR_ITEM_NO = @@PR_ITEM_NO
	) dt

	IF(@@ASSET_QTY > @@PR_QTY)
	BEGIN
		UPDATE TB_T_ASSET SET VALID_FLAG = 'N', SYSTEM_MSG = 'Total uploaded asset for this item is more than PR Quantity.' WHERE PROCESS_ID = @PROCESS_ID AND VALID_FLAG = 'Y'
	END

	FETCH NEXT FROM db_cursor_temp 
		INTO @@PR_NO, @@PR_ITEM_NO, @@PR_QTY
END
CLOSE db_cursor_temp
DEALLOCATE	db_cursor_temp