SELECT
	(SELECT SYSTEM_VALUE FROM dbo.TB_M_SYSTEM WHERE FUNCTION_ID = 'FTP' AND SYSTEM_CD = 'URL_VENDOR_SAP_OUT') + ';' +
	(SELECT SYSTEM_VALUE FROM dbo.TB_M_SYSTEM WHERE FUNCTION_ID = 'FTP' AND SYSTEM_CD = 'URL_VENDOR_SAP_ARC') + ';' +
    (SELECT SYSTEM_VALUE FROM dbo.TB_M_SYSTEM WHERE FUNCTION_ID = 'FTP' AND SYSTEM_CD = 'UNAME') + ';' +
    (SELECT SYSTEM_VALUE FROM dbo.TB_M_SYSTEM WHERE FUNCTION_ID = 'FTP' AND SYSTEM_CD = 'PASSW')