Select  A.PARENT_CD,	
		A.PROC_USAGE_CD,
		A.MODEL,
		A.GENTANI_HEADER_TYPE,
		A.GENTANI_HEADER_CD,			  
		A.MULTIPLY_USAGE,			  		  
		REPLACE(CONVERT(varchar(10),A.VALID_DT_FR,102),'.','-') VALID_DT_FR,	
	    REPLACE(CONVERT(varchar(10),A.VALID_DT_TO,102),'.','-') VALID_DT_TO			  
FROM TB_M_PARENT_GENTANI_HEADER_HIKIATE A
WHERE A.PARENT_CD = @ParentCd AND
      A.PROC_USAGE_CD = @ProcUsage AND
	  A.GENTANI_HEADER_TYPE = @HeaderType AND
	  A.GENTANI_HEADER_CD = @HeaderCd AND	 
	  A.MODEL = @Model AND	 
	  A.VALID_DT_FR = @ValidDt	