USE [PAS_DB_QA]
GO
/****** Object:  StoredProcedure [dbo].[sp_prcreation_datalist_getWBSList]    Script Date: 12/5/2017 8:57:47 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_prcreation_datalist_getCostCenterList] 
	@PR_COORDINATOR varchar(20),
	@DIVISION_ID int,
	@REGNO VARCHAR(30)
AS
BEGIN
	IF(ISNULL(@PR_COORDINATOR, '') = 'AD-TRV')
	BEGIN
		IF EXISTS(SELECT 1 FROM TB_M_COORDINATOR_MAPPING WHERE COORDINATOR_CD = 'AD-TRV' AND NOREG = @REGNO)
		BEGIN
			SELECT DISTINCT 
				COST_CENTER_CD as COST_CENTER, 
				COST_CENTER_DESC 
			FROM TB_M_COST_CENTER WHERE GETDATE() BETWEEN VALID_DT_FROM AND VALID_DT_TO
		END
		ELSE
		BEGIN
			-- Tampilkan structure data nya dengan data null
			SELECT DISTINCT 
				COST_CENTER_CD as COST_CENTER, 
				COST_CENTER_DESC 
			FROM TB_M_COST_CENTER WHERE 1 = 0
		END
	END
	ELSE
	BEGIN
		SELECT DISTINCT 
			COST_CENTER_CD as COST_CENTER, 
			COST_CENTER_DESC 
		FROM TB_M_COST_CENTER WHERE DIVISION_ID = @DIVISION_ID AND GETDATE() BETWEEN VALID_DT_FROM AND VALID_DT_TO
	END
END



