USE [PASS_DB_DEV]
GO
/****** Object:  StoredProcedure [dbo].[sp_prinquiry_validationeditPR]    Script Date: 1/14/2016 10:19:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[sp_prinquiry_validationeditPR] 
		@PR_NO VARCHAR(12),
		@USER_ID VARCHAR(20), 
		@NOREG VARCHAR(20)
AS
BEGIN
DECLARE @STATUS_FLAG VARCHAR(1),
		@PROCESS_ID BIGINT,
		@COUNT INT,
		@POSITION_LEVEL INT,
		@ORG_ID INT,
		@SQLTEXT NVARCHAR(MAX),
		@APPROVAL_CD VARCHAR(5),
		@ANOTHER_USER VARCHAR(100),
		@ANOTHER_PID BIGINT,
		@ANOTHER_CREATED_DT DATETIME,
		@IS_DRAFT CHAR(1),
		@IS_CANCELLED CHAR(1),
		@MODULE VARCHAR(4) = '2',
		@FUNCTION VARCHAR(6) = '201002'

--SET @SQLTEXT = N'SELECT 
--					@POSITION_LEVEL_0 = POSITION_LEVEL, 
--					@ORG_ID_0 = ORG_ID 
--				FROM OPENQUERY ([SANBOX-SQL\SANDBOXSQL], 
--			   ''SELECT DISTINCT 
--						POSITION_LEVEL, 
--						ORG_ID 
--				 FROM [DATAMASTER].[dbo].[vw_Organization] 
--				 WHERE 
--					   GETDATE() BETWEEN VALID_FROM AND VALID_TO 
--					   AND NOREG = ''''' + @NOREG + ''''''');'
--EXEC sp_executesql @SQLTEXT, 
--				   N'@POSITION_LEVEL_0 INT OUTPUT, 
--				     @ORG_ID_0 INT OUTPUT',
--				   @POSITION_LEVEL_0 = @POSITION_LEVEL OUTPUT, 
--				   @ORG_ID_0 = @ORG_ID OUTPUT

BEGIN TRY
	SELECT @IS_DRAFT = CASE WHEN (PR_STATUS = '94' OR PR_STATUS = '00') THEN 'Y' ELSE 'N' END 
			FROM TB_R_PR_H WHERE PR_NO = @PR_NO

	SELECT @IS_CANCELLED = CASE WHEN (PR_STATUS = '95') THEN 'Y' ELSE 'N' END 
			FROM TB_R_PR_H WHERE PR_NO = @PR_NO

	IF(@IS_DRAFT = 'N' AND @IS_CANCELLED = 'N')
	BEGIN
		SELECT  
			@POSITION_LEVEL = POSITION_LEVEL,
			@ORG_ID = ORG_ID
		FROM TB_R_SYNCH_EMPLOYEE
		WHERE 
			GETDATE() BETWEEN VALID_FROM AND VALID_TO AND 
			NOREG =  @NOREG

		SELECT 
			@PROCESS_ID = PROCESS_ID
		FROM TB_R_PR_H 
		WHERE PR_NO = @PR_NO
		IF(ISNULL(@PROCESS_ID, 0) <> 0)
		BEGIN
			-- Modified By : FID.Intan [2015-10-22]
			-- Added TB_T_LOCK user_id checking & TB_T_LOCK and TB_T_PR_H, TB_T_PR_ITEM, TB_T_PR_SUBITEM deletion
			UPDATE PRI SET PROCESS_ID = NULL FROM TB_R_PR_ITEM PRI JOIN TB_T_LOCK TL 
				ON PRI.PROCESS_ID = TL.PROCESS_ID AND TL.MODULE_ID = @MODULE AND TL.FUNCTION_ID = @FUNCTION
				   AND PRI.PR_NO = @PR_NO
			
			SELECT @COUNT = COUNT(1) 
			FROM TB_T_LOCK 
			WHERE PROCESS_ID = @PROCESS_ID AND 
				  [USER_ID] <> @USER_ID

			DELETE B FROM TB_T_PR_ITEM B 
			INNER JOIN TB_T_LOCK A
				ON A.PROCESS_ID = B.PROCESS_ID AND
				   A.USER_ID = @USER_ID AND
				   A.MODULE_ID = @MODULE AND
				   A.FUNCTION_ID = @FUNCTION

			DELETE B FROM TB_T_PR_SUBITEM B 
			INNER JOIN TB_T_LOCK A
				ON A.PROCESS_ID = B.PROCESS_ID AND
				   A.USER_ID = @USER_ID AND
				   A.MODULE_ID = @MODULE AND
				   A.FUNCTION_ID = @FUNCTION

			DELETE FROM TB_T_LOCK 
			WHERE USER_ID = @USER_ID AND
				  MODULE_ID = @MODULE AND
				  FUNCTION_ID = @FUNCTION

			IF(@COUNT > 0)
			BEGIN
				SELECT 
					@ANOTHER_USER = [USER_NAME],
					@ANOTHER_PID = PROCESS_ID
				FROM TB_T_LOCK
				WHERE PROCESS_ID = @PROCESS_ID
				SELECT '<p>User ' + @ANOTHER_USER + ' is Still Processing Document ' + 
					   @PR_NO + ' With</p><p>Process ID : ' + CONVERT(VARCHAR, @ANOTHER_PID) + '</p>'
				RETURN
			END
		END
	
		SELECT @COUNT = COUNT(*) 
		FROM TB_R_WORKFLOW 
		WHERE DOCUMENT_NO = @PR_NO AND 
			  STRUCTURE_ID = @ORG_ID AND 
			  APPROVER_POSITION = @POSITION_LEVEL
		IF(@COUNT <= 0)
		BEGIN
			SELECT 'User ID ' + @USER_ID + ' Is Not Listed in Workflow with Document No ' + @PR_NO
			RETURN
		END
	
		SELECT @STATUS_FLAG = PR_STATUS FROM TB_R_PR_H WHERE PR_NO = @PR_NO
		IF(@STATUS_FLAG >= '92')
		BEGIN
			SELECT 'PR No ' + @PR_NO + ' Already Complete, Cannot Be Edited'
			RETURN
		END
	
		SELECT TOP 1 
				@APPROVAL_CD = APPROVAL_CD 
		FROM TB_R_WORKFLOW 
		WHERE DOCUMENT_NO = @PR_NO AND 
			  STRUCTURE_ID = @ORG_ID AND 
			  APPROVER_POSITION = @POSITION_LEVEL
		ORDER BY DOCUMENT_SEQ ASC

		SELECT @COUNT = COUNT(*) 
		FROM TB_R_WORKFLOW A 
			JOIN TB_R_PR_ITEM B 
				ON B.PR_NO = A.DOCUMENT_NO AND 
				   A.APPROVAL_CD = B.PR_NEXT_STATUS
		WHERE A.DOCUMENT_NO = @PR_NO AND 
			  A.STRUCTURE_ID = @ORG_ID AND 
			  A.APPROVER_POSITION = @POSITION_LEVEL
		IF(@COUNT <= 0)
		BEGIN
			IF(@APPROVAL_CD <> '10')
			BEGIN
				SELECT 'User ' + @USER_ID + ' Cannot Edit PR No ' + @PR_NO + ', Only Next Approver and PR Creator can edit this Document'
				RETURN
			END
		END

		/*SELECT @COUNT = COUNT(*) 
		FROM TB_R_PR_H
			WHERE RELEASED_FLAG = 'Y' AND PR_NO = @PR_NO
		IF(@COUNT > 0)
		BEGIN
			SELECT 'Cannot Edit PR No ' + @PR_NO + ', PR Already Released'
			RETURN
		END*/
	END
	ELSE
	BEGIN
		SELECT @COUNT = COUNT(1) FROM TB_R_PR_H WHERE PR_NO = @PR_NO AND (CREATED_BY = @USER_ID OR CREATED_BY = @NOREG)
		IF(@COUNT = 0)
		BEGIN
			SELECT 'User ' + @USER_ID + ' Cannot Edit PR No ' + @PR_NO
			RETURN
		END
	END
 
	SELECT 'SUCCESS'
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE()
END CATCH
END