ALTER PROCEDURE [dbo].[sp_prinquiry_getListPRH] 
		@PR_NO VARCHAR(MAX), 
		@PR_TYPE VARCHAR(5),
		@VENDOR_CD VARCHAR(MAX), 
		@PLANT_CD VARCHAR(MAX), 
		@SLOC_CD VARCHAR(MAX), 
		@DIVISION_CD VARCHAR(MAX), 
		@DATEFROM VARCHAR(MAX), 
		@DATETO VARCHAR(MAX), 
		@PROJECT_NO VARCHAR(MAX), 
		@PR_STATUS_FLAG VARCHAR(MAX), 
		@PR_DESC VARCHAR(MAX), 
		@PR_COORDINATOR VARCHAR(MAX), 
		@WBS_NO VARCHAR(MAX), 
		@DETAIL_STS VARCHAR(MAX),
		@CREATED_BY VARCHAR(MAX),
		@ORDER_BY VARCHAR(MAX),
		@PO_NO VARCHAR(MAX), 
		@Start INT, 
		@Length INT
AS
BEGIN
DECLARE @SQL_QUERY VARCHAR(MAX),
		@LIMIT VARCHAR(10)

--TO DO : SELECT @LIMIT = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'MAX_SELECTED_DATA'
SELECT @LIMIT = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'MAX_SEARCH'

--TO DO : Adjust joined table to get Division Name 
SET @SQL_QUERY = 
'SELECT * FROM (
SELECT DISTINCT TOP ' + @LIMIT + '
	CASE ''' + ISNULL(@ORDER_BY, '') + ''' 
				WHEN ''TYPE|ASC'' THEN DENSE_RANK() OVER (ORDER BY E.PROCUREMENT_DESC ASC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''TYPE|DESC'' THEN DENSE_RANK() OVER (ORDER BY E.PROCUREMENT_DESC DESC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''NO|ASC'' THEN DENSE_RANK() OVER (ORDER BY A.PR_NO ASC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''NO|DESC'' THEN DENSE_RANK() OVER (ORDER BY A.PR_NO DESC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''DESC|ASC'' THEN DENSE_RANK() OVER (ORDER BY A.PR_DESC ASC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''DESC|DESC'' THEN DENSE_RANK() OVER (ORDER BY A.PR_DESC DESC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''DATE|ASC'' THEN DENSE_RANK() OVER (ORDER BY A.DOC_DT ASC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''DATE|DESC'' THEN DENSE_RANK() OVER (ORDER BY A.DOC_DT DESC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''STATUS|ASC'' THEN DENSE_RANK() OVER (ORDER BY B.STATUS_DESC ASC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''STATUS|DESC'' THEN DENSE_RANK() OVER (ORDER BY B.STATUS_DESC DESC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''COORDINATOR|ASC'' THEN DENSE_RANK() OVER (ORDER BY F.COORDINATOR_DESC ASC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''COORDINATOR|DESC'' THEN DENSE_RANK() OVER (ORDER BY F.COORDINATOR_DESC DESC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''PLANT|ASC'' THEN DENSE_RANK() OVER (ORDER BY A.PLANT_CD ASC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''PLANT|DESC'' THEN DENSE_RANK() OVER (ORDER BY A.PLANT_CD DESC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''STORAGE|ASC'' THEN DENSE_RANK() OVER (ORDER BY A.SLOC_CD ASC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''STORAGE|DESC'' THEN DENSE_RANK() OVER (ORDER BY A.SLOC_CD DESC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''DIVISION|ASC'' THEN DENSE_RANK() OVER (ORDER BY A.DIVISION_NAME ASC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				WHEN ''DIVISION|DESC'' THEN DENSE_RANK() OVER (ORDER BY A.DIVISION_NAME DESC, A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
				ELSE DENSE_RANK() OVER (ORDER BY A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC)
	END AS NUMBER,
	A.PR_NO as PR_NO,
	E.PROCUREMENT_DESC AS PR_TYPE,
	A.DOC_DT AS docdt,
	[dbo].[fn_date_format](A.DOC_DT) as DOC_DT,
	A.PR_DESC as PR_DESC,
	A.PR_STATUS as STATUS_CD,
	B.STATUS_DESC as STATUS_DESC,
	A.PLANT_CD as PLANT_CD,
	A.SLOC_CD as SLOC_CD,
	F.COORDINATOR_DESC AS PR_COORDINATOR,
	CONVERT(VARCHAR,A.DIVISION_ID) as DIVISION_ID,
	A.DIVISION_NAME as DIVISION_NAME,
	A.PROJECT_NO as PROJECT_NO,
	A.CREATED_BY,
	A.CREATED_DT as createddt,
	[dbo].[fn_date_format](A.CREATED_DT) AS CREATED_DT,
	A.CHANGED_BY,
	A.CHANGED_DT as changeddt,
	[dbo].[fn_date_format](A.CHANGED_DT) AS CHANGED_DT,
	A.PROCESS_ID AS PROCESS_ID,
	D.USER_NAME AS LOCKED_BY
FROM TB_R_PR_H A 
	JOIN TB_M_STATUS B ON B.STATUS_CD = A.PR_STATUS
	JOIN TB_R_PR_ITEM C ON C.PR_NO = A.PR_NO
	JOIN TB_M_PROCUREMENT_TYPE E ON A.PR_TYPE = E.PROCUREMENT_TYPE
	JOIN TB_M_COORDINATOR F ON A.PR_COORDINATOR = F.COORDINATOR_CD
	LEFT JOIN TB_M_VENDOR G ON C.VENDOR_CD = G.VENDOR_CD
	LEFT JOIN TB_T_LOCK D ON A.PROCESS_ID = D.PROCESS_ID
WHERE
	((A.PR_NO LIKE ''%' + ISNULL(@PR_NO,'') + '%'' 
	AND isnull(''' + ISNULL(@PR_NO,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@PR_NO,'') + ''', '''') = '''')))
AND ((A.PR_TYPE = ''' + ISNULL(@PR_TYPE,'') + '''
	AND isnull(''' + ISNULL(@PR_TYPE,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@PR_TYPE,'') + ''', '''') = '''')))
AND ((A.PLANT_CD = ''' + ISNULL(@PLANT_CD,'') + '''
	AND isnull(''' + ISNULL(@PLANT_CD,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@PLANT_CD,'') + ''', '''') = '''')))
AND ((A.SLOC_CD = ''' + ISNULL(@SLOC_CD,'') + '''
	AND isnull(''' + ISNULL(@SLOC_CD,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@SLOC_CD,'') + ''', '''') = '''')))
AND ((A.DIVISION_ID = ''' + ISNULL(@DIVISION_CD,'') + '''
	AND isnull(''' + ISNULL(@DIVISION_CD,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@DIVISION_CD,'') + ''', '''') = '''')))
AND ((A.PROJECT_NO LIKE ''%' + ISNULL(@PROJECT_NO,'') + '%''
	AND isnull(''' + ISNULL(@PROJECT_NO,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@PROJECT_NO,'') + ''', '''') = '''')))
AND ((A.PR_STATUS = ''' + ISNULL(@PR_STATUS_FLAG,'') + '''
	AND isnull(''' + ISNULL(@PR_STATUS_FLAG,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@PR_STATUS_FLAG,'') + ''', '''') = '''')))
AND ((A.DOC_DT >= ''' + ISNULL(@DATEFROM,'') + '''
	AND isnull(''' + ISNULL(@DATEFROM,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@DATEFROM,'') + ''', '''') = '''')))
AND ((A.DOC_DT <= ''' + ISNULL(@DATETO,'') + '''
	AND isnull(''' + ISNULL(@DATETO,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@DATETO,'') + ''', '''') = '''')))
AND (((C.VENDOR_CD LIKE ''%' + ISNULL(@VENDOR_CD,'') + '%''
	AND isnull(''' + ISNULL(@VENDOR_CD,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@VENDOR_CD,'') + ''', '''') = '''')))
	OR ((G.VENDOR_NAME LIKE ''%' + ISNULL(@VENDOR_CD,'') + '%''
	AND isnull(''' + ISNULL(@VENDOR_CD,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@VENDOR_CD,'') + ''', '''') = ''''))))
AND ((A.PR_DESC LIKE ''%' + ISNULL(@PR_DESC,'')  + '%''
	AND isnull(''' + ISNULL(@PR_DESC,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@PR_DESC,'') + ''', '''') = '''')))
AND ((A.PR_COORDINATOR = ''' + ISNULL(@PR_COORDINATOR,'') + '''
	AND isnull(''' + ISNULL(@PR_COORDINATOR,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@PR_COORDINATOR,'') + ''', '''') = '''')))
AND ((C.WBS_NO LIKE ''%' + ISNULL(@WBS_NO,'') + '%''
	AND isnull(''' + ISNULL(@WBS_NO,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@WBS_NO,'') + ''', '''') = '''')))
AND ((C.PR_STATUS = ''' + ISNULL(@DETAIL_STS, '') + '''
	AND isnull(''' + ISNULL(@DETAIL_STS, '') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@DETAIL_STS, '') + ''', '''') = '''')))
AND ((A.CREATED_BY LIKE ''%' + ISNULL(@CREATED_BY, '') + '%''
	AND isnull(''' + ISNULL(@CREATED_BY, '') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@CREATED_BY, '') + ''', '''') = '''')))
AND ((C.PO_NO LIKE ''%' + ISNULL(@PO_NO,'') + '%'' 
	AND isnull(''' + ISNULL(@PO_NO,'') + ''', '''') <> ''''
	OR (isnull(''' + ISNULL(@PO_NO,'') + ''', '''') = '''')))
ORDER BY A.DOC_DT DESC, A.CREATED_DT DESC, A.CHANGED_DT DESC
	)TBL1 WHERE number >= ' + CONVERT(VARCHAR(MAX),@Start) + ' AND number <= ' + CONVERT(VARCHAR(MAX),@Length) + ' ORDER BY TBL1.number ASC'
--+ 'ORDER BY DOC_DT DESC'
EXEC (@SQL_QUERY)
END