USE [NCP_QA]
GO
/****** Object:  StoredProcedure [dbo].[sp_quotaCalculation]    Script Date: 12/18/2015 9:16:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		FID.Intan Puspitasari
-- Create date: 27/10/2015
-- Description:	Quota Processing
-- TO DO	  : What to do with REFF_DOC_NOTE??
-- =============================================
ALTER PROCEDURE [dbo].[sp_quotaCalculation]
	@TYPE VARCHAR(20), --COMMIT / RELEASE / UPDATE
	@WBS_NO VARCHAR(30),
	@VALUATION_CLASS VARCHAR(4),
	@MAT_NO VARCHAR(23),
	@MAT_DESC VARCHAR(25),
	@DIVISION INT,
	@MONTH VARCHAR(6),
	@AMOUNT DECIMAL(18, 4),
	@LAST_AMOUNT DECIMAL(18, 4),
	@REFF_DOC VARCHAR(11),
	@REFF_DOC_NOTE VARCHAR(11),
	@USER_ID VARCHAR(20),
	@STATUS VARCHAR(MAX) OUTPUT
AS
BEGIN
DECLARE @MSG VARCHAR(MAX),
		@DIFF_AMOUNT DECIMAL(18, 4),
		@AVAILABLE_AMOUNT DECIMAL(18, 4),
		@SEQ_NO INT

SET NOCOUNT ON;

BEGIN TRY
	SELECT @AVAILABLE_AMOUNT = COUNT(*) FROM TB_R_QUOTA WHERE CONSUME_MONTH = @MONTH AND WBS_NO = @WBS_NO 
		   AND DIVISION_ID = @DIVISION AND QUOTA_TYPE = @VALUATION_CLASS
	IF(@AVAILABLE_AMOUNT = 0)
	BEGIN
		SET @MSG = 'Quota Not Available for WBS No ' + @WBS_NO + ' and Valuation Class ' + @VALUATION_CLASS
		RAISERROR(@MSG, 16, 1)
	END

	SELECT @SEQ_NO = 
			CASE WHEN EXISTS ( SELECT 1 FROM TB_R_QUOTA_CONSUME WHERE DOC_NO = @REFF_DOC) 
			THEN (SELECT ISNULL(MAX(SEQ_NO), 0) + 1 FROM TB_R_QUOTA_CONSUME WHERE DOC_NO = @REFF_DOC)
			ELSE 1 END
			
	IF(@TYPE = 'UPDATE')
	BEGIN
		SET @DIFF_AMOUNT = (@AMOUNT - @LAST_AMOUNT) 
		IF(@DIFF_AMOUNT < 0)
		BEGIN
			SELECT @AVAILABLE_AMOUNT = (ISNULL(QUOTA_AMOUNT, 0) + ISNULL(ADDITIONAL_AMOUNT, 0)) - ISNULL(USAGE_AMOUNT, 0) FROM TB_R_QUOTA
			   WHERE CONSUME_MONTH = @MONTH AND WBS_NO = @WBS_NO AND QUOTA_TYPE = @VALUATION_CLASS
			
			IF(@AVAILABLE_AMOUNT < ABS(@DIFF_AMOUNT))
			BEGIN
				SET @MSG = 'Quota Not Available for WBS No ' + @WBS_NO + ' and Valuation Class ' + @VALUATION_CLASS
				RAISERROR(@MSG, 16, 1)
			END
		END
	END
	
	IF(@TYPE = 'RELEASE' OR @TYPE = 'UPDATE')
	BEGIN
		SELECT @SEQ_NO = 
			CASE WHEN EXISTS ( SELECT 1 FROM TB_R_QUOTA_CONSUME WHERE DOC_NO = @REFF_DOC) 
			THEN (SELECT ISNULL(MAX(SEQ_NO), 0) + 1 FROM TB_R_QUOTA_CONSUME WHERE DOC_NO = @REFF_DOC)
			ELSE 1 END
		UPDATE TB_R_QUOTA SET USAGE_AMOUNT = (ISNULL(USAGE_AMOUNT, 0) - ISNULL(@LAST_AMOUNT, 0)) WHERE CONSUME_MONTH = @MONTH AND WBS_NO = @WBS_NO AND 
			   DIVISION_ID = @DIVISION AND QUOTA_TYPE = @VALUATION_CLASS
		INSERT INTO [dbo].[TB_R_QUOTA_CONSUME]
					   ([DOC_NO]
					   ,[SEQ_NO]
					   ,[DOC_DT]
					   ,[QUOTA_MONTH]
					   ,[DIVISION_ID]
					   ,[QUOTA_TYPE]
					   ,[MAT_NO]
					   ,[MAT_DESC]
					   ,[TRANS_STATUS]
					   ,[AMOUNT]
					   ,[CREATED_BY]
					   ,[CREATED_DT]
					   ,[CHANGED_BY]
					   ,[CHANGED_DT])
				VALUES (@REFF_DOC
					   ,@SEQ_NO
					   ,GETDATE()
					   ,@MONTH
					   ,@DIVISION
					   ,@VALUATION_CLASS
					   ,@MAT_NO
					   ,@MAT_DESC
					   ,'R'
					   ,@LAST_AMOUNT
					   ,@USER_ID
					   ,GETDATE()
					   ,null
					   ,null)
	END

	IF(@TYPE = 'COMMIT' OR @TYPE = 'UPDATE')
	BEGIN
		SELECT @SEQ_NO = 
			CASE WHEN EXISTS ( SELECT 1 FROM TB_R_QUOTA_CONSUME WHERE DOC_NO = @REFF_DOC) 
			THEN (SELECT ISNULL(MAX(SEQ_NO), 0) + 1 FROM TB_R_QUOTA_CONSUME WHERE DOC_NO = @REFF_DOC)
			ELSE 1 END
		
		SELECT @AVAILABLE_AMOUNT = (ISNULL(QUOTA_AMOUNT, 0) + ISNULL(ADDITIONAL_AMOUNT, 0)) - ISNULL(USAGE_AMOUNT, 0) FROM TB_R_QUOTA
			   WHERE CONSUME_MONTH = @MONTH AND WBS_NO = @WBS_NO AND DIVISION_ID = @DIVISION AND QUOTA_TYPE = @VALUATION_CLASS
		
		IF(@AVAILABLE_AMOUNT < @AMOUNT)
		BEGIN
			SET @MSG = 'Not Enough Quota Amount for WBS No ' + @WBS_NO + ' and Valuation Class ' + @VALUATION_CLASS + ' , Remaining Quota Amount After Calculation is ' + CONVERT(VARCHAR, @AVAILABLE_AMOUNT)
			RAISERROR(@MSG, 16, 1)
		END
		ELSE
		BEGIN
			UPDATE TB_R_QUOTA SET USAGE_AMOUNT = (ISNULL(USAGE_AMOUNT, 0) + @AMOUNT) WHERE CONSUME_MONTH = @MONTH AND WBS_NO = @WBS_NO
				   AND DIVISION_ID = @DIVISION AND QUOTA_TYPE = @VALUATION_CLASS
			INSERT INTO [dbo].[TB_R_QUOTA_CONSUME]
					   ([DOC_NO]
					   ,[SEQ_NO]
					   ,[DOC_DT]
					   ,[QUOTA_MONTH]
					   ,[DIVISION_ID]
					   ,[QUOTA_TYPE]
					   ,[MAT_NO]
					   ,[MAT_DESC]
					   ,[TRANS_STATUS]
					   ,[AMOUNT]
					   ,[CREATED_BY]
					   ,[CREATED_DT]
					   ,[CHANGED_BY]
					   ,[CHANGED_DT])
				VALUES (@REFF_DOC
					   ,@SEQ_NO
					   ,GETDATE()
					   ,@MONTH
					   ,@DIVISION
					   ,@VALUATION_CLASS
					   ,@MAT_NO
					   ,@MAT_DESC
					   ,'C'
					   ,@AMOUNT
					   ,@USER_ID
					   ,GETDATE()
					   ,null
					   ,null)
		END 
	END
	SET @STATUS = 'SUCCESS|'
END TRY
BEGIN CATCH
	SET @STATUS = 'FAILED|' + ERROR_MESSAGE()
END CATCH
END