/****** Object:  StoredProcedure [dbo].[sp_worklist_getApprovalData]    Script Date: 12/18/2015 9:17:39 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		FID)Reggy
-- Create date: 3/19/2015
-- Description:	Get Approval By
-- =============================================
ALTER PROCEDURE [dbo].[sp_worklist_getApprovalData]
	@DOCUMENT_NO VARCHAR(15)
AS
BEGIN
DECLARE @SQL_QUERY VARCHAR(MAX)

	SET NOCOUNT ON;

		--UPDATE TB_R_WORKFLOW 
		--	SET APPROVED_BY = B.PERSONNEL_NAME,
		--		APPROVER_NAME = B.PERSONNEL_NAME,
		--		NOREG = B.NOREG,
		--		STRUCTURE_NAME = B.ORG_TITLE
		--FROM TB_R_WORKFLOW A INNER JOIN
		--OPENQUERY ([SANBOX-SQL\SANDBOXSQL], 
		--'SELECT DISTINCT 
		--		PERSONNEL_NAME,
		--		NOREG,
		--		ORG_ID, 
		--		POSITION_LEVEL, 
		--		ORG_TITLE
		--FROM [DATAMASTER].[dbo].[vw_Organization] B 
		--WHERE GETDATE() BETWEEN VALID_FROM AND VALID_TO') B
		--ON B.POSITION_LEVEL = A.APPROVER_POSITION AND 
		--   B.ORG_ID = A.STRUCTURE_ID AND
		--   A.DOCUMENT_SEQ > 1
		--WHERE DOCUMENT_NO = @DOCUMENT_NO
		
		UPDATE TB_R_WORKFLOW 
			SET APPROVED_BY = B.NOREG,
				APPROVER_NAME = B.PERSONNEL_NAME,
				NOREG = B.NOREG,
				STRUCTURE_NAME = B.ORG_TITLE
		FROM TB_R_WORKFLOW A INNER JOIN
		TB_R_SYNCH_EMPLOYEE B 
			ON B.POSITION_LEVEL = A.APPROVER_POSITION 
			   AND (B.ORG_ID = A.STRUCTURE_ID OR SUBSTRING(A.APPROVAL_CD, 1, 1) = '3')
			   AND GETDATE() BETWEEN B.VALID_FROM AND B.VALID_TO
			   AND A.DOCUMENT_SEQ > 1
			   AND (((SUBSTRING(A.APPROVAL_CD, 1, 1) <> '2' AND SUBSTRING(A.APPROVAL_CD, 1, 1) <> '3'))
					OR
					((SUBSTRING(A.APPROVAL_CD, 1, 1) = '2' OR SUBSTRING(A.APPROVAL_CD, 1, 1) = '3')
					AND A.NOREG <> 'N' AND A.NOREG = B.NOREG)
				   )
		WHERE DOCUMENT_NO = @DOCUMENT_NO
END