  /* FID.Ridwan: 20220704*/
 DECLARE @@PR_DATE_FROM_PAR DATE = CAST(@PR_DATE_FROM AS DATE)
 , @@PR_DATE_TO_PAR DATE = CAST(@PR_DATE_TO AS DATE)
 , @@PR_NO_PAR VARCHAR(100) = LTRIM(RTRIM(@PR_NO))
 , @@VENDOR_PAR VARCHAR(100) = LTRIM(RTRIM(@VENDOR))
 , @@CREATED_BY_PAR VARCHAR(100) = LTRIM(RTRIM(@CREATED_BY))
 , @@PO_NO_PAR VARCHAR(100) = LTRIM(RTRIM(@PO_NO))
 , @@GR_NO_PAR VARCHAR(100) = LTRIM(RTRIM(@GR_NO))
 , @@INV_NO_PAR VARCHAR(100) = LTRIM(RTRIM(@INV_NO))
 , @@PCS_GRP_PAR VARCHAR(100) = LTRIM(RTRIM(@PCS_GRP))
 , @@DIVISION_ID_PAR VARCHAR(100) = LTRIM(RTRIM(@DIVISION_ID))
 , @@WBS_NO_PAR VARCHAR(100) = LTRIM(RTRIM(@WBS_NO))
 , @@CLEARING_NO_PAR VARCHAR(100) = LTRIM(RTRIM(@CLEARING_NO))
 , @@CLEARING_DATE_PAR DATE = CAST(@CLEARING_DATE AS DATE)
 , @@CLEARING_DATE_TO_PAR DATE = CAST(@CLEARING_DATE_TO AS DATE)
 , @@PO_DT_PAR DATE = CAST(@PO_DT AS DATE)
 , @@PO_DT_TO_PAR DATE = CAST(@PO_DT_TO AS DATE)
 , @@INV_DT_PAR DATE = CAST(@INV_DT AS DATE)
 , @@INV_DT_TO_PAR DATE = CAST(@INV_DT_TO AS DATE)
 , @@GR_DATE_PAR DATE = CAST(@GR_DATE AS DATE)
 , @@GR_DATE_TO_PAR DATE = CAST(@GR_DATE_TO AS DATE)
 , @@STATUS_CD_PAR VARCHAR(100) = LTRIM(RTRIM(@STATUS_CD))

;with tmp AS (
	select 
		ROW_NUMBER() OVER (ORDER BY A.PR_NO DESC) Data_No
	
	from 
	TB_R_PR_H A 
	inner join TB_R_PR_ITEM B on A.PR_NO=B.PR_NO
	left join TB_R_PR_SUBITEM C on A.PR_NO = c.PR_NO
	left join TB_R_PO_H D on b.PO_NO=d.PO_NO
	left join TB_R_PO_ITEM e on d.PO_NO=e.PO_NO
	left join TB_R_PO_SUBITEM f on d.PO_NO=f.PO_NO
	left join TB_R_GR_IR g on d.PO_NO = g.PO_NO
	left join TB_R_INVOICE_INFO h on h.GR_NUMBER = g.MAT_DOC_NO
	where 1=1 
	AND (ISNULL(@@PR_NO_PAR, '') = '' OR ISNULL(A.PR_NO, '') LIKE '%' + ISNULL(@@PR_NO_PAR, '') + '%')
	AND (ISNULL(@@VENDOR_PAR, '') = '' OR ISNULL(D.VENDOR_CD, '') LIKE '%' + ISNULL(@@VENDOR_PAR, '') + '%')
	AND (ISNULL(@@CREATED_BY_PAR, '') = '' OR ISNULL(A.CREATED_BY, '') LIKE '%' + ISNULL(@@CREATED_BY_PAR, '') + '%')
	AND (ISNULL(@@PO_NO_PAR, '') = '' OR ISNULL(d.PO_NO, '') LIKE '%' + ISNULL(@@PO_NO_PAR, '') + '%')
	AND (ISNULL(@@GR_NO_PAR, '') = '' OR ISNULL(g.MAT_DOC_NO, '') LIKE '%' + ISNULL(@@GR_NO_PAR, '') + '%')
	AND a.DOC_DT BETWEEN @@PR_DATE_FROM_PAR AND @@PR_DATE_TO_PAR
	AND (ISNULL(@@PO_DT_PAR, '') = '' OR d.DOC_DT BETWEEN @@PO_DT_PAR AND @@PO_DT_TO_PAR)
	AND (ISNULL(@@INV_DT_PAR, '') = '' OR h.INVOICE_DATE BETWEEN @@INV_DT_PAR AND @@INV_DT_TO_PAR)
	AND (ISNULL(@@GR_DATE_PAR, '') = '' OR g.DOCUMENT_DT BETWEEN @@GR_DATE_PAR AND @@GR_DATE_TO_PAR)
	AND (ISNULL(@@GR_NO_PAR, '') = '' OR ISNULL(g.MAT_DOC_NO, '') LIKE '%' + ISNULL(@@GR_NO_PAR, '') + '%')
	AND (ISNULL(@@INV_NO_PAR, '') = '' OR ISNULL(h.INVOICE_NO, '') LIKE '%' + ISNULL(@@INV_NO_PAR, '') + '%')
	--AND (ISNULL(@@PCS_GRP_PAR, '') = '' OR ISNULL(d.PURCHASING_GRP_CD, '') LIKE '%' + ISNULL(@@PCS_GRP_PAR, '') + '%')
	AND (ISNULL(@@PCS_GRP_PAR, '') = '' OR d.PURCHASING_GRP_CD IN (select splitdata From dbo.fnSplitString(@@PCS_GRP_PAR, ';')) )
	AND (ISNULL(@@DIVISION_ID_PAR, '') = '' OR ISNULL(A.DIVISION_ID, '') = ''+ ISNULL(@@DIVISION_ID_PAR, '')+ '') 
	AND (ISNULL(@@WBS_NO_PAR, '') = '' OR ISNULL(b.WBS_NO, '') LIKE '%' + ISNULL(@@WBS_NO_PAR, '') + '%')
	AND (ISNULL(@@CLEARING_NO_PAR, '') = '' OR ISNULL(h.LOG_DOC_NO, '') LIKE '%' + ISNULL(@@CLEARING_NO_PAR, '') + '%')
	AND (ISNULL(@@CLEARING_DATE_PAR, '') = '' OR h.CLEARING_DOC_DT BETWEEN @@CLEARING_DATE_PAR AND @@CLEARING_DATE_TO_PAR)
	AND (@@STATUS_CD_PAR IN ('', '2') OR (@@STATUS_CD_PAR = '1' AND D.PO_STATUS = '44'))
	AND (@@STATUS_CD_PAR IN ('', '1') OR (@@STATUS_CD_PAR = '2' AND h.INVOICE_ID IS NULL))
	AND (@@STATUS_CD_PAR IN ('', '2') 
		OR (@@STATUS_CD_PAR = '1' 
			AND (EXISTS (SELECT 1 FROM TB_R_PO_SUBITEM POS WHERE D.PO_NO = POS.PO_NO AND POS.PO_QTY_ORI = POS.PO_QTY_REMAIN)
					OR
				EXISTS (SELECT 1 FROM TB_R_PO_ITEM POI WHERE D.PO_NO = POI.PO_NO AND POI.PO_QTY_ORI = POI.PO_QTY_REMAIN))
			)
		)
) SELECT count(*) FROM tmp 