BEGIN TRY
	DELETE FROM TB_T_CALCULATION_MAPPING 
		WHERE PROCESS_ID IN(SELECT PROCESS_ID FROM TB_R_LOG_H WHERE CREATED_BY = @USER_ID)
	SELECT 'SUCCESS'
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE()
END CATCH