SELECT ROW_NUMBER() OVER (ORDER BY COMP_PRICE_CD ASC) AS SEQ_NO,
	   A.ITEM_STATUS,
	   A.COMP_PRICE_CD,
	   A.COMP_PRICE_TEXT,
	   A.BASE_VALUE_FROM,
	   A.BASE_VALUE_TO,
	   CONVERT(VARCHAR, A.BASE_VALUE_FROM) + CASE WHEN(ISNULL(CONVERT(VARCHAR, A.BASE_VALUE_TO), '') <> '') THEN ' - ' + CONVERT(VARCHAR, A.BASE_VALUE_TO) ELSE '' END AS BASE_VALUE,
	   A.INVENTORY_FLAG,
	   A.PLUS_MINUS_FLAG,
	   D.SYSTEM_REMARK AS PLUS_MINUS_SIGN,
	   A.QTY_PER_UOM,
	   CASE WHEN (A.CONDITION_CATEGORY = 'H') THEN 'Base Value' ELSE 'Additional Value' END AS CONDITION_CATEGORY,
	   C.SYSTEM_REMARK AS CALCULATION_TYPE_DESC,
	   A.ACCRUAL_FLAG_TYPE,
	   A.CONDITION_RULE
FROM TB_M_CALCULATION_MAPPING A 
	INNER JOIN TB_M_CALCULATION_SCHEME B
		ON A.CALCULATION_SCHEME_CD = B.CALCULATION_SCHEME_CD
		AND A.CALCULATION_SCHEME_CD = @CALCULATION_SCHEME_CD
	INNER JOIN TB_M_SYSTEM C
		ON A.CALCULATION_TYPE = C.SYSTEM_VALUE AND C.FUNCTION_ID = '114001' AND C.SYSTEM_CD LIKE 'CALCULATION_TYPE_%'
	INNER JOIN TB_M_SYSTEM D
		ON A.PLUS_MINUS_FLAG = D.SYSTEM_VALUE AND D.FUNCTION_ID = '114001' AND D.SYSTEM_CD LIKE 'PLUS_MINUS_FLAG_%'