DECLARE @@NEW_SEQ_NO INT,
	    @@COMP_PRICE_TEXT VARCHAR(MAX)


BEGIN TRY
	SELECT @@COMP_PRICE_TEXT = [COMP_PRICE_DESC] 
	FROM TB_M_COMP_PRICE 
		WHERE COMP_PRICE_CD = @COMP_PRICE_CD

	IF(@SEQ_NO <= 0)
	BEGIN
		SELECT @@NEW_SEQ_NO = ISNULL(MAX(SEQ_NO), 0) + 1 FROM TB_T_CALCULATION_MAPPING WHERE PROCESS_ID = @PROCESS_ID
	 
		INSERT INTO [dbo].[TB_T_CALCULATION_MAPPING]
			   ([PROCESS_ID]
			   ,[COMP_PRICE_CD]
			   ,[ITEM_STATUS]
			   ,[SEQ_NO]
			   ,[COMP_PRICE_TEXT]
			   ,[BASE_VALUE_FROM]
			   ,[BASE_VALUE_TO]
			   ,[INVENTORY_FLAG]
			   ,[QTY_PER_UOM]
			   ,[CALCULATION_TYPE]
			   ,[PLUS_MINUS_FLAG]
			   ,[CONDITION_CATEGORY]
			   ,[ACCRUAL_FLAG_TYPE]
			   ,[CONDITION_RULE]
			   ,[CREATED_BY]
			   ,[CREATED_DT]
			   ,[CHANGED_BY]
			   ,[CHANGED_DT]
			   ,[NEW_FLAG])
		 VALUES
			   (@PROCESS_ID
			   ,@COMP_PRICE_CD
			   ,@ITEM_STATUS
			   ,@@NEW_SEQ_NO
			   ,@@COMP_PRICE_TEXT
			   ,@BASE_VALUE_FROM
			   ,@BASE_VALUE_TO
			   ,@INVENTORY_FLAG
			   ,@QTY_PER_UOM
			   ,@CALCULATION_TYPE
			   ,@PLUS_MINUS_FLAG
			   ,@CONDITION_CATEGORY
			   ,@ACCRUAL_FLAG_TYPE
			   ,@CONDITION_RULE
			   ,@uid
			   ,GETDATE()
			   ,null
			   ,null
			   ,'Y')
	END
	ELSE
	BEGIN
		UPDATE TB_T_CALCULATION_MAPPING
			SET COMP_PRICE_CD = @COMP_PRICE_CD,
			    COMP_PRICE_TEXT = @@COMP_PRICE_TEXT,
				ITEM_STATUS = @ITEM_STATUS,
				BASE_VALUE_FROM = @BASE_VALUE_FROM,
				BASE_VALUE_TO = @BASE_VALUE_TO,
				INVENTORY_FLAG = @INVENTORY_FLAG,
				QTY_PER_UOM = @QTY_PER_UOM,
				CALCULATION_TYPE = @CALCULATION_TYPE,
				PLUS_MINUS_FLAG = @PLUS_MINUS_FLAG,
				CONDITION_CATEGORY = @CONDITION_CATEGORY,
				ACCRUAL_FLAG_TYPE = @ACCRUAL_FLAG_TYPE,
				CONDITION_RULE = @CONDITION_RULE,
				CHANGED_BY = @uid,
				CHANGED_DT = GETDATE(),
				UPDATE_FLAG = 'Y'
		WHERE PROCESS_ID = @PROCESS_ID AND SEQ_NO = @SEQ_NO
	END
	SELECT 'SUCCESS'
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE()
END CATCH