--untuk get error data hasil dari balikan sap
/*
SELECT [ERROR_MESSAGE]
FROM [dbo].TB_R_ERR_RECEIVING
WHERE [RECEIVING_NO] = @ReceivingNo
*/
--20200130 jika balikan dari sap multi line untuk receiving yang sama

IF EXISTS (SELECT TOP 1 ERROR_MESSAGE 
	FROM TB_R_ERR_RECEIVING where RECEIVING_NO = @ReceivingNo 
	AND[ERROR_MESSAGE] LIKE 'General error%'
	AND [ERROR_MESSAGE] NOT LIKE '%Please Enter%'
	)
BEGIN
	SELECT STUFF((SELECT ', ' + US.[ERROR_MESSAGE]
	FROM TB_R_ERR_RECEIVING US WHERE US.[RECEIVING_NO] = ss.[RECEIVING_NO] FOR XML PATH('')), 1, 1, '')
	[ERROR_MESSAGE] from TB_R_ERR_RECEIVING ss where ss.[RECEIVING_NO] = @ReceivingNo group by ss.[RECEIVING_NO]
	UNION
	SELECT MESSAGE_TEXT AS [ERROR_MESSAGE] 
	FROM TB_M_MESSAGE WHERE MESSAGE_ID = 'MAP13000002'
END
ELSE 
BEGIN
	SELECT STUFF((SELECT ', ' + US.[ERROR_MESSAGE]
	FROM TB_R_ERR_RECEIVING US WHERE US.[RECEIVING_NO] = ss.[RECEIVING_NO] FOR XML PATH('')), 1, 1, '')
	[ERROR_MESSAGE] from TB_R_ERR_RECEIVING ss where ss.[RECEIVING_NO] = @ReceivingNo group by ss.[RECEIVING_NO]
	
END