IF @Type = 1
BEGIN
	SELECT gra.ATTACHMENT_DOC_PATH AttachmentPath
	FROM TB_R_GR_IR_ATTACHMENT gra
	WHERE gra.MAT_DOC_NO = @rcvNo
END ELSE
BEGIN
	SELECT gra.OTHERS_ATTACHMENT_DOC_PATH AttachmentPath
	FROM TB_R_GR_IR_ATTACHMENT gra
	WHERE gra.MAT_DOC_NO = @rcvNo
END