DECLARE @@CHG DATETIME = GETDATE();

IF EXISTS(SELECT TOP 1 1 FROM TB_R_GR_IR_ATTACHMENT WHERE MAT_DOC_NO=@RcvNo)
BEGIN
	UPDATE 
		TB_R_GR_IR_ATTACHMENT
	SET 
		ATTACHMENT_DOC_PATH = (CASE WHEN @Type = 1 THEN @Path ELSE ATTACHMENT_DOC_PATH END)
		,ATTACHMENT_DOC_FILE_NM = (CASE WHEN @Type = 1 THEN @FileName ELSE ATTACHMENT_DOC_FILE_NM END)
		,OTHERS_ATTACHMENT_DOC_PATH = (CASE WHEN @Type = 2 THEN @Path ELSE OTHERS_ATTACHMENT_DOC_PATH END)
		,OTHER_ATTACHMENT_DOC_FILE_NM = (CASE WHEN @Type = 2 THEN @FileName ELSE OTHER_ATTACHMENT_DOC_FILE_NM END)
		, CHANGED_DT = @@CHG
		, CHANGED_BY = @UpdateBy
	WHERE 
		1 = 1
		and MAT_DOC_NO=@RcvNo
END ELSE 
BEGIN
	INSERT INTO TB_R_GR_IR_ATTACHMENT
	(MAT_DOC_NO
	,ATTACHMENT_DOC_PATH
	,ATTACHMENT_DOC_FILE_NM
	,OTHERS_ATTACHMENT_DOC_PATH
	,OTHER_ATTACHMENT_DOC_FILE_NM
	,CREATED_BY
	,CREATED_DT
	,CHANGED_BY
	,CHANGED_DT)
	SELECT @RcvNo MAT_DOC_NO
	,(CASE WHEN @Type = 1 THEN @Path ELSE '' END) ATTACHMENT_DOC_PATH
	,(CASE WHEN @Type = 1 THEN @FileName ELSE '' END) ATTACHMENT_DOC_FILE_NM
	,(CASE WHEN @Type = 2 THEN @Path ELSE '' END) OTHERS_ATTACHMENT_DOC_PATH
	,(CASE WHEN @Type = 2 THEN @FileName ELSE '' END) OTHER_ATTACHMENT_DOC_FILE_NM
	,@UpdateBy CREATED_BY
	,@@CHG CREATED_DT
	,@UpdateBy CHANGED_BY
	,@@CHG CHANGED_DT

END

UPDATE A
SET STATUS_CD = '67',
	CHANGED_BY = @UpdateBy,
	CHANGED_DT = @@CHG
FROM TB_R_GR_IR A
WHERE MAT_DOC_NO = @RcvNo

SELECT replace(convert(varchar(8), @@CHG, 112)+convert(varchar(8), @@CHG, 114), ':','')