DECLARE @@PROCESS_ID BIGINT,
		@@PR_STATUS_FLAG INT,
		@@ORG_ID INT,
		@@POSITION_LEVEL INT,
		@@SQLTEXT NVARCHAR(MAX),
		@@MSG VARCHAR(MAX),
		@@MSG_ID VARCHAR(12),
		@@LOCATION VARCHAR(50) = 'Upload Attach Init',
		@@MODULE VARCHAR(4) = '5',
		@@FUNCTION VARCHAR(6) = '501003'

SET @@MSG = 'Receiving List Upload Attachment Process Initialization'
SET @@MSG_ID = 'INF00001'
EXEC dbo.sp_PutLog @@MSG, @USERID, @@LOCATION, @@PROCESS_ID OUTPUT, @@MSG_ID, 'INF', @@MODULE, @@FUNCTION, 1;

SELECT @@PROCESS_ID