CREATE TABLE [dbo].[TB_H_NOTIFICATION](
	[NOTIFICATION_GRP_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar](255) NOT NULL,
	[CONTENT] [text] NOT NULL,
	[AUTHOR] [varchar](50) NOT NULL,
	[PROCESS_ID] [bigint],
	[CREATED_BY] [varchar](20) NOT NULL,
	[CREATED_DT] [datetime] NOT NULL,
	[CHANGED_BY] [varchar](20) NULL,
	[CHANGED_DT] [datetime] NULL,
	[VALID_FROM] [datetime] NULL,
	[VALID_TO] [datetime] NULL,
 CONSTRAINT [PK_TB_H_NOTIFICATION] PRIMARY KEY CLUSTERED 
(
	[NOTIFICATION_GRP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO