CREATE TABLE TB_M_PROC_USAGE
(
    PROC_USAGE_CD VARCHAR(5) NOT NULL,
    [DESCRIPTION] VARCHAR(50) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_DT DATETIME NOT NULL,
    CHANGED_BY VARCHAR(20),
    CHANGED_DT DATETIME,

    CONSTRAINT PK_TB_M_PROC_USAGE PRIMARY KEY (PROC_USAGE_CD)
)