USE [PAS_DB_QA]
GO

/****** Object:  Table [dbo].[TB_R_ATTACHMENT]    Script Date: 12/18/2017 11:54:08 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_M_SOP_DOCUMENT](
	[DOCUMENT_ID] int iDENTITY(1,1),
	[DOC_TYPE] [varchar](5) NOT NULL,
	[FILE_NAME] [varchar](max) NOT NULL,
	[FILE_NAME_ORI] [varchar](max) NOT NULL,
	[FILE_DESC] [varchar](max) NOT NULL,
	[FILE_EXTENSION] [varchar](5) NOT NULL,
	[FILE_SIZE] [bigint] NOT NULL,
	[CREATED_BY] [varchar](20) NOT NULL,
	[CREATED_DT] [datetime] NOT NULL,
	[CHANGED_BY] [varchar](20) NULL,
	[CHANGED_DT] [datetime] NULL,
 CONSTRAINT [PK_TB_M_SOP_DOCUMENT] PRIMARY KEY CLUSTERED 
(
	[DOCUMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


