CREATE TABLE TB_M_MATERIAL
(
    PROC_USAGE_GROUP VARCHAR(10) NOT NULL,
    MAT_NO VARCHAR(23) NOT NULL,
    MAT_DESC VARCHAR(50) NOT NULL,
    UOM VARCHAR(3) NOT NULL,
    MRP_TYPE VARCHAR(2) NOT NULL,
    MINIMUM_STOCK INT NOT NULL,
    RE_ORDER_POINT INT NOT NULL,
    RE_ORDER_METHOD VARCHAR(2) NOT NULL,
    FIXED_MRP_QTY INT,
    STD_DELIVERY_TIME INT,
    AVG_DAILY_CONSUMPTION INT,
    MAX_STOCK INT NOT NULL,
    PCS_PER_KANBAN INT NOT NULL,
    MRP_FLAG CHAR(1) NOT NULL,
    STOCK_FLAG CHAR(1) NOT NULL,
    ASSET_FLAG CHAR(1) NOT NULL,
    QUOTA_FLAG CHAR(1) NOT NULL,
    DELETION_FLAG CHAR(1) NOT NULL,
    VALUATION_CLASS VARCHAR(4) NOT NULL,
    CONSIGNMENT_CD VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_DT DATETIME NOT NULL,
    CHANGED_BY VARCHAR(20),
    CHANGED_DT DATETIME,

    CONSTRAINT PK_T_B_M_MATERIAL PRIMARY KEY (PROC_USAGE_GROUP, MAT_NO)
)
