CREATE TABLE TB_M_PARENT
(
    PARENT_CD VARCHAR(23) NOT NULL,
    PARENT_TYPE VARCHAR(3) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_DT DATETIME NOT NULL,
    CHANGED_BY VARCHAR(20),
    CHANGED_DT DATETIME,

    CONSTRAINT PK_TB_M_PARENT PRIMARY KEY (PARENT_CD, PARENT_TYPE)
)
