CREATE TABLE TB_M_MATERIAL_PRICE
(
    MAT_NO VARCHAR(23) NOT NULL,
    SUPP_CD VARCHAR(10) NOT NULL,
    WARP_BUYER_CD VARCHAR(5) NOT NULL,
    PRICE_STATUS VARCHAR(1) NOT NULL,
    APPROVE_DT DATETIME NOT NULL,
    APPROVE_STS VARCHAR(1) NOT NULL,
    DELETION_FLAG VARCHAR(1),
    SOURCE_TYPE VARCHAR(1) NOT NULL,
    VALID_DT_FR DATETIME NOT NULL,
    VALID_DT_TO DATETIME NOT NULL,
    PC_NO VARCHAR(21),
    SOURCE_DATA VARCHAR(1) NOT NULL,
    DRAFT_DF VARCHAR(1),
    WARP_REF_NO VARCHAR(10), -- Ask Pak Bayu length
    CPP_FLAG VARCHAR(1),
    PROD_PURPOSE_CD VARCHAR(5) NOT NULL,
    PART_COLOR_SFX VARCHAR(2) NOT NULL,
    CURR_CD VARCHAR(3),
    PRICE_AMT DECIMAL(15,4) NOT NULL,
    PACKING_TYPE VARCHAR(1) NOT NULL,
    SENT_PIECE_PO_DT DATETIME,
    DATA_SEQUENCE INT, -- Ask Pak Bayu length
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_DT DATETIME NOT NULL,
    CHANGED_BY VARCHAR(20),
    CHANGED_DT DATETIME,

    CONSTRAINT PK_TB_M_MATERIAL_PRICE PRIMARY KEY (MAT_NO, SUPP_CD, WARP_BUYER_CD, SOURCE_TYPE,
        VALID_DT_FR, PROD_PURPOSE_CD, PART_COLOR_SFX, PACKING_TYPE)
)
