CREATE TABLE TB_M_NON_COMPONENT_PART_LIST
(
    PROC_USAGE_CD VARCHAR(5) NOT NULL,
    GENTANI_HEADER_TYPE VARCHAR(3) NOT NULL,
    GENTANI_HEADER_CD VARCHAR(23) NOT NULL,
    MAT_NO VARCHAR(23) NOT NULL,
    USAGE_QTY INT NOT NULL,
    UOM VARCHAR(10) NOT NULL,
    PLANT_CD VARCHAR(5) NOT NULL,
    STORAGE_LOCATION VARCHAR(10) NOT NULL,
    VALID_DT_FR DATETIME NOT NULL,
    VALID_DT_TO DATETIME NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_DT DATETIME NOT NULL,
    CHANGED_BY VARCHAR(20),
    CHANGED_DT DATETIME,

    CONSTRAINT PK_TB_M_NON_COMPONENT_PART_LIST PRIMARY KEY (PROC_USAGE_CD, GENTANI_HEADER_TYPE, GENTANI_HEADER_CD, MAT_NO, VALID_DT_FR)
)