CREATE TABLE TB_M_SOURCE_LIST
(
    MAT_NO VARCHAR(5) NOT NULL,
    VENDOR_CD VARCHAR(3) NOT NULL,
    VALID_DT_FR DATETIME NOT NULL,
    VALID_DT_TO DATETIME NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_DT DATETIME NOT NULL,
    CHANGED_BY VARCHAR(20),
    CHANGED_DT DATETIME,

    CONSTRAINT PK_TB_M_SOURCE_LIST PRIMARY KEY (MAT_NO, VENDOR_CD, VALID_DT_FR)
)