CREATE TABLE TB_R_MRP_PROCESS_LIST
(
    PROC_USAGE_CD INT NOT NULL,
    [MONTH] VARCHAR(6) NOT NULL,
    MRP_EXECUTION_DT DATETIME NOT NULL,
    MRP_EXECUTION_BY VARCHAR(20) NOT NULL,
    PR_NO VARCHAR(50),
    PR_APPROVAL_DT DATETIME,
    PR_APPROVAL_BY VARCHAR(20),
    PO_CREATION_DT DATETIME,
    PO_CREATION_BY VARCHAR(20),
    PO_APPROVAL_DT DATETIME,
    PO_APPROVAL_BY VARCHAR(20),

    CONSTRAINT PK_TB_R_MRP_PROCESS_LIST PRIMARY KEY (PROC_USAGE_CD, [MONTH])
)