select splitdata
into #s
from dbo.fnSplitString(@MAT_DOC_NO,';')

IF not EXISTS(SELECT 1 from #s)
BEGIN
	insert into #s values ('')
END

SELECT COUNT(1) AS N FROM
(
select A.MAT_DOC_NO,DOCUMENT_DT,HEADER_TEXT,A.VENDOR_CD,A.PO_NO,ITEM_CURRENCY,STATUS_CD,M.VENDOR_NAME
,SUM(A.GR_IR_AMOUNT) AMOUNT,MAX(A.CHANGED_BY) CHANGED_BY, MAX(A.CHANGED_DT) CHANGED_DT
,MAX(A.CREATED_BY) CREATED_BY, MAX(A.CREATED_DT) CREATED_DT
from TB_R_GR_IR A
inner join TB_R_PO_ITEM B ON A.PO_NO=B.PO_NO
inner join TB_R_PR_H C ON B.PR_NO=C.PR_NO
inner join TB_M_COORDINATOR_MAPPING D ON C.PR_COORDINATOR=D.COORDINATOR_CD
inner join TB_R_SYNCH_EMPLOYEE SE ON D.NOREG=SE.NOREG
left join TB_R_GR_IR_ATTACHMENT E ON A.MAT_DOC_NO=E.MAT_DOC_NO
left join TB_M_VENDOR M ON A.VENDOR_CD=M.VENDOR_CD
cross apply #s S 
WHERE A.COMPONENT_PRICE_CD = 'PB00'
AND A.STATUS_CD = 67
AND EXISTS
(
select 1 from TB_M_SYSTEM E 
cross apply dbo.SplitString(E.SYSTEM_VALUE,';') F
where FUNCTION_ID='V0601' and SYSTEM_CD='APPROVE_AUTH'
AND F.Split=D.POSITION_LEVEL_NAME
)
AND (ISNULL(@PLANT_CD,'') = '' OR A.PLANT_CD=@PLANT_CD)
AND (ISNULL(@SLOC_CD,'') = '' OR A.SLOC_CD=@SLOC_CD)
AND (ISNULL(@DIVISION_ID,'') = '' OR C.DIVISION_ID=@DIVISION_ID)
AND (ISNULL(@PR_COORDINATOR,'') = '' OR C.PR_COORDINATOR=@PR_COORDINATOR)
AND (ISNULL(@START_DOC_DATE,'') = '' OR A.DOCUMENT_DT >= @START_DOC_DATE )
AND (ISNULL(@END_DOC_DATE,'') = '' OR A.DOCUMENT_DT <= @END_DOC_DATE )
AND A.MAT_DOC_NO LIKE '%'+S.splitdata+'%'
AND A.HEADER_TEXT like '%'+ISNULL(@HEADER_TEXT,'')+'%'

GROUP BY A.MAT_DOC_NO,DOCUMENT_DT,HEADER_TEXT,A.VENDOR_CD,A.PO_NO,ITEM_CURRENCY,STATUS_CD,M.VENDOR_NAME
) t1