

select distinct SE.NOREG
from TB_R_GR_IR A
inner join TB_R_PO_ITEM B ON A.PO_NO=B.PO_NO
inner join TB_R_PR_H C ON B.PR_NO=C.PR_NO
inner join TB_M_COORDINATOR_MAPPING D ON C.PR_COORDINATOR=D.COORDINATOR_CD
inner join TB_R_SYNCH_EMPLOYEE SE ON D.NOREG=SE.NOREG
WHERE A.COMPONENT_PRICE_CD = 'PB00'
AND A.STATUS_CD = 67
AND EXISTS
(
select 1 from TB_M_SYSTEM E 
cross apply dbo.SplitString(E.SYSTEM_VALUE,';') F
where FUNCTION_ID='V0601' and SYSTEM_CD='APPROVE_AUTH'
AND F.Split=D.POSITION_LEVEL_NAME
)