
IF EXISTS (SELECT TOP 1 ERROR_MESSAGE 
	FROM TB_R_ERR_PO where PO_NO = @PONO 
	AND[ERROR_MESSAGE] LIKE '%G/L account%' 
	AND [ERROR_MESSAGE] NOT LIKE '%Please Enter%'
	)
BEGIN
	SELECT STUFF((SELECT ', ' + US.[ERROR_MESSAGE] 
	FROM TB_R_ERR_PO US WHERE US.PO_NO = ss.po_no FOR XML PATH('')), 1, 1, '')
	[ERROR_MESSAGE] from TB_R_ERR_PO ss where ss.PO_NO = @PONO group by ss.PO_NO
	UNION
	SELECT MESSAGE_TEXT AS [ERROR_MESSAGE] 
	FROM TB_M_MESSAGE WHERE MESSAGE_ID = 'MAP13000001'
END
ELSE 
BEGIN
	SELECT STUFF((SELECT ', ' + US.[ERROR_MESSAGE] 
	FROM TB_R_ERR_PO US WHERE US.PO_NO = ss.po_no FOR XML PATH('')), 1, 1, '')
	[ERROR_MESSAGE] from TB_R_ERR_PO ss where ss.PO_NO = @PONO group by ss.PO_NO
END